### ISSUE TITLE
Client.shutdown claims to close cluster, but doesn't

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#1085]
Client.shutdown claims in its docstring to tear down the cluster.  This isn't currently the case.  It only closes its own connection.   We can either

1.  Change the docstring
2.  Change the behavior

If we change only the docstring, then should we also add the shutdown functionality to the client?  

If we change the behavior then should we also add a close method?

http://stackoverflow.com/questions/44021931/stopping-dask-ssh-created-scheduler-from-the-client-interface

**Comment by martindurant** [comment]
I believe there should be a method to tear down the cluster from the client. "shutdown" seems like the best name for this, so I would go for option 2. "close" would be the same thing as what happens on del?

**Comment by pitrou** [comment]
I believe things would be less confusing if cluster-affecting methods would be named explicitly, such as `restart_cluster` instead of `restart` and `shutdown_cluster` instead of `shutdown`. If I were to read code without perusing the docs, I would never guess that `Client.restart` restarts the cluster, not the client.

Agreed to also have a separate `close` method that does what `shutdown` does right now, and have `__del__` call it. It's good to allow explicit resource cleanup when an object can keep many resources alive.

**Comment by eriknw** [comment]
I'm in favor of `restart_cluster`, `shutdown_cluster`, and `close` methods.  I'll work on a PR.

**Comment by xsqian** [comment]
Hi there, any progress on this?

**Comment by jrbourbeau** [comment]
There have been some related updates and today `client.shutdown()` does close the cluster

```python

In [1]: from distributed import Client, LocalCluster

In [2]: cluster = LocalCluster()

In [3]: client = Client(cluster)

In [4]: cluster.status
Out[4]: <Status.running: 'running'>

In [5]: client.shutdown()

In [6]: cluster.status
Out[6]: <Status.closed: 'closed'>
```

Closing as resolved, though we can reopen as needed
