### ISSUE TITLE
Policy for Python 3 only features

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#1107]
Some projects have started to develop new features in Python 3 only.  Do we want to do the same?  This would not affect existing functionality.  Some pros and cons as I see them.

### Pros

-  Reduced maintenance cost
-  Access to new features (async-await, typing annotations)
-  Smooths out async interface a bit if we use it more in development
-  Pushes users towards Python 3

### Cons

-  Limits Python 2 users
-  Makes it confusing what features are available on which version

Feedback, especially critical feedback, would be welcome.

**Comment by pitrou** [comment]
Can you elaborate? Do you mean to release Python 3-only new versions? Or to have Python 2-compatible versions with a minority of Python 3-only features in them?

If the latter, we have already started doing so :-) But I agree it will be confusing.

**Comment by mrocklin** [comment]
I mean including Python 3 only features.  For a concrete case I was thinking of this in regards to #1106

**Comment by vishsangale** [comment]
Having python-3 only features is a good step since python-2 is becoming too old and the lot of new features of python-3 are attracting most of the developers. 
Most of the scientific libraries are already moving towards it to reduce the cost of maintaining python-2 compatible code http://www.python3statement.org/

**Comment by jrbourbeau** [comment]
Closing since we've dropped Python 2 support
