### ISSUE TITLE
Can run, cannot debug

### ISSUE THREAD

**Issue by kuzlovsky** [dask/distributed#1174]
Hello,

I am not able to debug a dask program in pycharm.

I have this simple code:
```
import distributed

if __name__ == '__main__':
    print('start')
    client = distributed.Client()
    print('OK')
```

If I **run** it I get the expected output
```
start
OK
```

If I press **debug** I only it get's stuck after the start line in the following callstack:
```
Client.__init__
start
sync
e.wait(1000000)
```

If I use a distributed client:
`client = distributed.Client('192.168.1.163:8786')`
then debugging works, so I assume the issue is with creating a local cluster, which I also tested
`cluster = distributed.LocalCluster()`
also works in run but gets stuck in debug mode at the same location.

_I wish I could just use a distributed cluster, unfortunately I have to rely on creating a LocalCluster. I am also using a (popular) library that is not able to clean up it's resources properly so as a workaround their only existing recommendation is to terminate the process. There are multiple clients. The only workable solution I can think of is to have a remote cluster for clean jobs where the workers are not terminated so the multiple clients can share and not terminate each others workers. Then to create a temporary localculter per client with a dask's worker resource feature and run the 'dirty' jobs on the temporary local cluster with  tagging them with the resource, and have the cluster terminated after a big job is done to reclaim resources. This solution works, except that I am not able to debug this solution :(_

Any help to get around this issue or figure out how to do the debugging in pycharm would be appreciated.

Thank you,
Joe

**Comment by kuzlovsky** [comment]
Tracked the bug down, does not seem to be with dask/multiprocessing

**Comment by davidas85** [comment]
@kuzlovsky Did you find a way to get debugging in pycharm working with a LocalCluster?

**Comment by mrocklin** [comment]
I would not expect debugging to work through dask.distributed.  You might want to try the local synchronous scheduler instead

    dask.set_options(get=dask.local.get_sync)

The distributed scheduler executes in separate threads or separate processes.  It does deliver back a traceback that *looks* like it came from your machine, but unfortunately none of the intermediate state is accessible.

**Comment by davidas85** [comment]
It's not possible to run the code in debug mode (for example, in order to debug other parts of the code that don't use dask) - any Client (with LocalCluster) initialization freezes the entire process and it must be killed.

I read somewhere that it has something to do with the way pydevd (used by pycharm) tries to debug child processes.
Your suggestion should circumvent the issue, by not creating additional processes.

**Comment by baverhey** [comment]
I just made an issue linking to this: https://intellij-support.jetbrains.com/hc/requests/1337354

**Comment by davidas85** [comment]
Reported in PyCharm's issue tracker:
https://youtrack.jetbrains.com/issue/PY-29607

**Comment by mrocklin** [comment]
I suspect that they'll be happier if you're able to change the example to
only include the multiprocessing module.  Removing Dask from the picture
should make it more clear that this is a fundamental problem, and not an
issue with an external package.

**Comment by davidas85** [comment]
Updating back with response from the helpful staff at JetBrains - as I expected, PyCharm is monkey patching process creation methods, in order to enable tracing:
https://github.com/JetBrains/intellij-community/blob/master/python/helpers/pydev/_pydev_bundle/pydev_monkey.py#L500

That can probably break whichever method distributed is using to nanny child processes or something like that.. I'm not familiar enough with the inner workings to know what's going on.

**Comment by kuzlovsky** [comment]
my workaround was to change the dask settings:
#multiprocessing-method: forkserver
multiprocessing-method: fork
