### ISSUE TITLE
Running offline  - client dashboard not loading

### ISSUE THREAD

**Issue by sephib** [dask/distributed#1246]
Hi,
I'm running a miniconda environment in an offline environment. 
After installing on the relevant packages, I'm not able to view the client dashboard when running in Jupyter notebook.
Details:
1. I'm importing `bokeh` with the output_notebook argument `resources=INLINE` 
2. When running `import distributed`  I get the following warning
`RuntimeWarning: Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1'...`  
this is from the `/utils.py` function `_get_ip` file.
3. When I rune ` client = distribtued.Client()` I get a `client` object
4. When getting the Dashboard URL like http://127.0.0.1:8787 I get a bare page - looking at the web console I see an error: `Failed to load resource: net::ERR_INTERNET_DISCONNECTED`
5. When trying to load a subpage (i.e. system or workers etc.) I get a an empty page that does load anything.

I guess that it may be caused by running offline (and that the client dashboard doesn't manage to get the `INLINE` parameter.

Any suggestions?

Thx

Update

When I run the following code  
```python
client = distributed.Client('scheduler-address:8786')
```
I get the following error
```OSError: Timed out trying to connect to tcp://scheduler-address:8786' after 5s: [errno 1101] getaddrinfo failed```

my OS is Window Server 2012 R2

**Comment by mrocklin** [comment]
Running the dashboard offline works fine for me except that the Dask logo doesn't show up.  Generally speaking Dask is commonly run in networks that are cut off from the internet and this hasn't yet been a problem.

I hadn't tried while the `output_notebook` flag had been set, but tried this now and things seemed to work fine.  

The warning `Couldn't detect a suitable IP address for reaching '8.8.8.8', defaulting to '127.0.0.1'...` is telling you that Dask can't reach a fairly typical address, so it's just going to run on localhost.  This seems in line with your expected behavior.

I don't know what the `resources=INLINE` feature in Bokeh is, and so am not sure if I can help you there.

**Comment by sephib** [comment]
Thx for your prompt reply!
1. How should I be configuring Bokeh when running in Jupyter Notebook?
2. I'm noticing that I have a load of  TCP connections running `python.exe` with `IPv4 loopback` - is that reasonable ?

**Comment by mrocklin** [comment]
> How should I be configuring Bokeh when running in Jupyter Notebook?

I don't do anything special and things seem to work fine.  I can't speak to your environment though.

> I'm noticing that I have a load of TCP connections running python.exe with IPv4 loopback - is that reasonable ?

By default calling `Client()` forks a number of processes that communicate with each other with sockets.  I would expect at least two open sockets per core to start out and probably more after non-trivial communication.  If you wish to avoid this you can start with `Client(processes=False)` which will start all of the workers in the same memory space and communicate data over queues rather than sockets.

**Comment by sephib** [comment]
Thx
Will try tomorrow and update.

**Comment by sephib** [comment]
After reinstalling the  dask framework with all of it's dependencies I'm able to access the dashboard.
Thanks for all the great work!

**Comment by mrocklin** [comment]
Thanks for following up!
