### ISSUE TITLE
Support for ORC Format

### ISSUE THREAD

**Issue by hussainsultan** [dask/distributed#1388]
Since ORC format is the go-to choice for some of the Hadoop distributions, support for  ORC format akin  to Parquet will be great.

**Comment by jcrist** [comment]
There isn't a solid library for working with ORC files in python yet. However, there is a [C++ reader and writer](https://github.com/apache/orc/tree/master/c%2B%2B) in the main ORC repo that could probably be wrapped.

**Comment by mrocklin** [comment]
Pinging @wesm in case he has any desire to add to his current workload :)  Would any Arrow folks be interested in this?

**Comment by wesm** [comment]
I think @cpcloud has looked at this. The incremental work of adding an Arrow-based connector should not be too great. It would be logistically simple to transfer ORC-decoded data into Arrow en route to pandas vs. building a bespoke-for-pandas reader. Anyone from the Dask side that can help with any aspect of this (e.g. packaging of the library in conda-forge)?

**Comment by mrocklin** [comment]
> Anyone from the Dask side that can help with any aspect of this (e.g. packaging of the library in conda-forge)?

Maybe.  I believe that folks are still at a stage of just estimating costs and seeking funding.

**Comment by wesm** [comment]
We're going to be building a native Avro-Arrow adapter before the end of the year, and completing nested data support in Parquet. So there will be some work happening in and around here where collaborations can be aligned well toward progress in many areas.

**Comment by wesm** [comment]
I'm happy to discuss funding for this offline, I may be able to help there in 2018

**Comment by majidaldo** [comment]
why isn't this conversation happening in the odo project?

**Comment by jcrist** [comment]
An ORC adapter now exists in pyarrow master (not yet available on the nightlies or current release). I've tested wrapping this with dask and everything works smoothly. Once that's released we can discuss adding a wrapper for this functionality in the dask project (where this code would live).

> why isn't this conversation happening in the odo project?

An equivalent conversation could happen in `odo`. Dask and odo are different libraries, and have little connection besides some similar developers. If you'd like to file an issue in odo, conversation on odo and ORC could continue there.

---

Since the code for using ORC and dask together will live in the dask repo, I'm going to close this for now. Once the next pyarrow release is out we can discuss adding support for dask.

**Comment by timarmstrong** [comment]
@jcrist thanks for fixing the vendored library stuff upstream in ORC. I was curious what downstream project was using it, followed the breadcrumbs and ended up here. We've been working on ORC support in Impala and I ran into the same issues as you did.
