### ISSUE TITLE
Adaptive cluster for Kubernetes

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#1619]
In https://github.com/cedadev/jasmin-dask/blob/master/docker/k8s-adaptive.py there is an adaptive cluster system for Kubernetes, I believe jointly developed by @mkjpryor-stfc ,  @jacobtomlinson, and @niallrobinson .  This was brought up in https://github.com/dask/distributed/pull/1618 .  I'm also interested in this so I thought I'd raise an issue to discuss potential design.

**Comment by mrocklin** [comment]
OK, so looking at the Jasmin implemenation in particular here are some questions/comments:

1.  I've never used the `kubernetes` Python package before, how do you like it?
2.  It seems odd to me to have a Kubernetes spec defined in Python rather than in some yaml file. I'm new to this space though and so don't really know what's common.
3.  How can we generalize something like this to work with other dask-kubernetes deployments?  I would expect different groups to be somewhat opinionated about how they set things up.
4.  In my ideal world when we create a Kubernetes Dask cluster manager we provide it with the name of some group of pods/containers and have it just change the number of active replicas rather than hand-crafting individual pods on its own
5.  However, I really like the ability of the Jasmin cluster manager to destroy particular pods that are identified by the `Scheduler.close_workers` method
6.  What kinds of permissions do you need to give to the scheduler container so that it can perform kubernetes operations like this?

**Comment by mrocklin** [comment]
I'm inclined to make a different adaptive strategy that targets a particular number of workers based on time estimates in `Scheduler.total_occupancy` and on current memory use.  This would avoid a slow ramp-up of workers and would instead jump directly to an appropriate number.

**Comment by mkjpryor-stfc** [comment]
@mrocklin: Here's my take on the points you made:

1. It's OK - better than making the API requests myself. However, the API is generated by Swagger from the API documentation, so it is very verbose and not very "Pythonic". A bespoke Python API might be better but risks falling out of step with what is currently a very rapidly changing API.

2. There are some dynamic aspects to the pod spec, defined using environment variables to the scheduler, which is why it is defined in Python. I suppose you could template it instead - Jinja would probably make most sense from Python - but including and configuring Jinja seemed like a lot of effort for one template.

3. I think it is already quite configurable - you can set namespace, labels, image, image pull policy, and worker resources are all configurable using environment variables to the scheduler. We could add more.

4/5. I agree with this - in an ideal world we would. @jacobtomlinson originally had an implementation based on a worker `Deployment` that was scaled up and down. However, when a `Deployment` is scaled down, the pods to terminate are picked randomly (I think), and Jacob saw issues where a pod with an important result was killed before passing it off, and the whole calculation had to be spun up again. Hence the solution we came up with where the pods themselves are managed - it allows us to be targeted when terminating pods. As far as I am aware, there isn't a way to do this with deployments.

6. The permissions are granted in here - https://github.com/cedadev/jasmin-dask/blob/master/helm/templates/rbac.yaml. Basically, list/create/delete pods is all it needs.

Scaling straight out to a suitable number of workers does seem to make sense at first glance.

**Comment by mrocklin** [comment]
> 4/5. I agree with this - in an ideal world we would. @jacobtomlinson originally had an implementation based on a worker Deployment that was scaled up and down. However, when a Deployment is scaled down, the pods to terminate are picked randomly (I think), and Jacob saw issues where a pod with an important result was killed before passing it off, and the whole calculation had to be spun up again. Hence the solution we came up with where the pods themselves are managed - it allows us to be targeted when terminating pods. As far as I am aware, there isn't a way to do this with deployments.

What if we terminate pods directly like you do here and then immediately afterwards scale down the deployment?  I would hope that Kubernetes would do the right thing and only remove the recently terminated pods.

**Comment by mkjpryor-stfc** [comment]
> What if we terminate pods directly like you do here and then immediately afterwards scale down the deployment? I would hope that Kubernetes would do the right thing and only remove the recently terminated pods.

That could work, but then we're basically managing the pods _and_ a deployment. It doesn't buy us the convenience that we would want from using a container.

**Comment by mkjpryor-stfc** [comment]
> >What if we terminate pods directly like you do here and then immediately afterwards scale down the deployment? I would hope that Kubernetes would do the right thing and only remove the recently terminated pods.

> That could work, but then we're basically managing the pods and a deployment. It doesn't buy us the convenience that we would want from using a container.

Plus we leave ourselves potentially subject to race conditions in the API causing us to lose results.

**Comment by mrocklin** [comment]
What if someone else separately wants to change the deployment, say by modifying the image or resources.  Theywould also need to tell us about these changes so that we can create containers appropriately, yes?

What if people want to define their deployment with a normal Yaml file (I get the sense that this is standard in the community).  How does that affect things here?

These may not be normal concerns (I don't know what is standard in this community), but I'm generally wary any time we pull things into a custom system, no matter how customizable it is.  We're asking people to confom to our way of doing things.  I'm looking for the least intrusive set of information we need to specify within a Python package, leaving as much as possible in the specification to the user with their normal workflow.

**Comment by martindurant** [comment]
From my experience, using objects with the python API is not particularly convenient, although it probably works better with "in code" modelling. I agree that people will still want access to YAML files that they edit in a way that is easily understood and thoroughly documented in the kube docs. Of course, converting between objects and YAML is simple enough, and tools like helm (and dask-kubernetes) do their own templating anyway.

**Comment by mkjpryor-stfc** [comment]
@mrocklin:

The scheduler deployment can be created however the user wants, and they can use any Dask container they want as long as it has `k8s-adaptive.py` installed and `dask-worker` and `dask-scheduler` in the `$PATH`.

If they create the deployment using the Helm chart, they can still customise things (e.g. image, worker resources) by passing a `values.yaml` to `helm install`. The Helm charts then make sure these things are passed into the deployment properly.

To a certain extent, I don't have that much of a problem with the Helm chart having _some_ opinions. Users can always do their own manifests if they disagree.

@martindurant:

I'm happy to look at ways we could template the worker pods in YAML if that is the consensus.

**Comment by mrocklin** [comment]
Let's say someone hands me a Dask deployment running on their Kubernetes system.  I don't really know anything about how they set it up beforehand, but it's running now and they want me to make it adaptive.  How can I accomplish this?  How little intrusion / inspection of their system can I get away with while still accomplishing this task?

I will run some function that sets up some `KubernetesAdaptive` class on their scheduler using the `Client.run_on_scheduler` command.  I suspect that I'll need the namespace and deployment name of their workers.  Is that enough?  Is this possible?  If so then this is more-or-less the kind of system that I would want to build for Dask if we want to include something like this in the main github org.  

Note that I'm not at all suggesting that this is something that all should do.  You're in a different situation in which you can specify a particular way that things are done.  Your constraints are, I think, likely to be somewhat different.

**Comment by martindurant** [comment]
^ I'd say "yes", you can do what you suggest for an existing Deployment (or ReplicationController or whatever): probe the scheduler to see it's state, and call kubernetes scale appropriately.

**Comment by mkjpryor-stfc** [comment]
@mrocklin: I'm confused whether you mean making changes on the fly to make an existing cluster adaptive, or tearing down the cluster and re-launching an adaptive one?

Because the former sounds really difficult and potentially unwise. I think the second can be achieved by providing enough flexibility in the Helm chart for changing images etc.

**Comment by mkjpryor-stfc** [comment]
> ^ I'd say "yes", you can do what you suggest for an existing Deployment (or ReplicationController or whatever): probe the scheduler to see it's state, and call kubernetes scale appropriately.

@martindurant: See my point 4/5 in my first comment. I would love to do the scaling like this, but we saw issues when we implemented it.

**Comment by mrocklin** [comment]
> I'm confused whether you mean making changes on the fly to make an existing cluster adaptive

I'm using the example above as an example of how general I think things can be.  If we can make this work then it means that our adaptive solution doesn't need to be baked in to peoples' infrastructure.  It means that we're entirely composable.  The amount to which they need to buy in to the way that we see the world is minimal, so minimal in fact that it doesn't require them to change their deployment at all, we can even come in after the fact if necessary.

**Comment by martindurant** [comment]
Indeed, it seems that kubernetes still doesn't allow you to scale down by removing specific pods (one [issue](https://github.com/kubernetes/kubernetes/issues/45509) on this), and we probably don't want to assume the role of the deployment itself. Indeed, if you were to delete workers you know you don't need, kubernetes would probably move others around, restarting some worker processes along the way.

**Comment by mkjpryor-stfc** [comment]
@mrocklin:

You could potentially have one Helm chart that could deploy adaptive or not adaptive clusters depending on a flag in the `values.yaml`. Although it would need some thinking about because you suddenly switch from a "static" worker deployment created by Helm to "something dynamic" managed by the scheduler.

But I think attempting to retrofit adaptive behaviour to a running cluster would be very difficult, and I'm not even sure you would want to do it.

**Comment by mrocklin** [comment]
> But I think attempting to retrofit adaptive behaviour to a running cluster would be very difficult, and I'm not even sure you would want to do it.

To be clear, I'm not saying that I want to do this in particular, I'm saying that this is a constraint that I think gets us to a point of minimal intrusion.  If we can accomplish this, then I am confident that our system doesn't require others to buy into our way of doing things.  

> You could potentially have one Helm chart that could deploy adaptive or not adaptive clusters depending on a flag in the values.yaml. Although it would need some thinking about because you suddenly switch from a "static" worker deployment created by Helm to "something dynamic" managed by the scheduler.

We probably can't even tell people that they need to use helm.  When building tools for the general library we need to be very very unopinionated.  Particular deployments have strong opinions (TLS, filesystem permissions, user permissions, etc.) and I don't want to get anywhere near having to be responsible for those.

**Comment by mkjpryor-stfc** [comment]
@mrocklin:

IMHO, there comes a point where you just need to say to people "here is this thing, it's pretty customisable, but if you want something really specific you might have to use it as a jumping-off point to do your own thing". For me, the most important thing is that we have something easy for the 90% use case.

**Comment by mrocklin** [comment]
In general I agree with you.  I think that mostly disagree on what the 90% use case is, and on the ease of customization.

**Comment by jacobtomlinson** [comment]
Wow this thread has gotten interesting since I left on Friday.

A few thoughts from my end:
- When running an adaptive cluster on Kubernetes the scheduler tells the worker containers to exit when they are no longer needed. My initial version would scale down the deployment in the hope that these containers wouldn't be recreated, however due to race conditions this would sometimes happen. @mkjpryor-stfc's version uses pods outside a deployment which need to be garbage collected but there is no risk of them being recreated. To be clear having them be accidentally resurrected isn't a problem, it's just pointless.
- As @mkjpryor-stfc said we do have issue when the underlying kubernetes infrastructure scales down because the scheduler and workers can be stateful and if they get terminated we can get long calculations starting from the beginning. This can be resolved by making our AWS scaling more intelligent. I see this as a separate concern to this thread (and separate to distributed I guess).
- I personally would encourage the use of helm for the "official" packaging as it is becoming the defacto for kubernetes installs. I think it is analogous to providing a pip/conda install as the "official" method. People can install from source if they wish, but they're on their own.
- I appreciate you're not actually suggesting retrofitting adaptive to an existing cluster. I would propose that a good test for it being general enough is for a user to be able to replace the container image in the helm chart with the one they are currently using and for everything to work as expected. This means that `k8s-adaptive.py` shouldn't be a requirement in the image, it should be added via a `ConfigMap`.

**Comment by mkjpryor-stfc** [comment]
@mrocklin, @jacobtomlinson:

I think that is a _great_ test for whether we are general enough. The vast majority of the time, the customisation users will want to make is to change the image. What they want from the Helm chart is the mechanics of taking that image and turning it into an cluster (fixed or adaptive). I agree that in the adaptive case, `k8s-adaptive.py` should be injected using a `ConfigMap`. I only built it into the image as I was building my own image anyway for other dependencies - if I'd been using the standard `dask` image, I would have used a `ConfigMap`.

We should definitely focus on Helm as the deployment mechanism.

**Comment by mrocklin** [comment]
OK, checking back in here again. @mkjpryor-stfc what changes would you make to your current deployment to make it more configurable? Are there changes you can imagine people would want to make that would be difficult to support?  Where should this code live long term?

There is some work with JupyterHub folks to make a particular deployment (similar to Jade or Jasmin) and that might be a nice use case so that we would have at least two different groups trying to use the same dask kubernetes deployment (jasmin and this other thing called pangeo).  We might learn something by engaging on this a bit.

What is the right way to try this out on an existing kubernetes cluster with a pre-existing docker image?

**Comment by mkjpryor-stfc** [comment]
@mrocklin 

If we are going by the definition of "sufficiently configurable" proposed by @jacobtomlinson, i.e. users should be able to drop in a different Dask image that they have used elsewhere and it should work, then I believe that the only significant change required is to inject k8s-adaptive.py using a ConfigMap instead of building it into the image. Other than that, I think it is configurable enough. After all, the whole point of using the Helm chart is to defer to someone else's expertise with the Kubernetes parts!

As to where the Helm chart should like, in its own project under a Dask organisation on Github would seem to make sense... :-)

**Comment by rbubley** [comment]
Nearly a year on, what’s the recommended way to get started with an adaptive Kubernetes cluster: dask-kubernetes or dask-helm?

**Comment by mrocklin** [comment]
See https://docs.dask.org/en/latest/setup/kubernetes.html

This issue is quite old and out of date now. Closing.
