### ISSUE TITLE
'import distributed' causes eating of bokeh server exceptions

### ISSUE THREAD

**Issue by timothydmorton** [dask/distributed#1683]
Not sure if this issue is better for here or for bokeh (pinging @bryevdv), but the simplest bokeh app I can think of does not print exceptions to the command line if I import distributed.  The app looks like 
```python
from bokeh.io import curdoc
import distributed

def modify_doc(doc):
    raise ValueError
    return doc


doc = modify_doc(curdoc()) 
```
When you run this with `bokeh serve <filename>` and try to access the app, the exception does not get printed to the command line (as it should, and as it does when the `distributed` import does not occur).

**Comment by mrocklin** [comment]
We definitely screw around with logging.  If we do this on import then I
agree that this is a problem.

**Comment by timothydmorton** [comment]
Yes, this happens on import.  I've just been poking around to see if I can figure out where, but no luck yet.

**Comment by timothydmorton** [comment]
OK, found it: https://github.com/dask/distributed/blob/master/distributed/config.py#L165

**Comment by mrocklin** [comment]
So what is the right thing to do here?  Call initialize logging only when starting a dask process?  Find some other way to avoid mucking about with Bokeh logs?

**Comment by EtsuNDmA** [comment]
Hi, this issue is still actual

**Comment by philippjfr** [comment]
This is still a major issue and makes debugging bokeh apps which use distributed or any library that imports it (e.g. xarray) really difficult. I'll take a look at fixing this.

**Comment by mrocklin** [comment]
Thank you @philippjfr !

**Comment by philippjfr** [comment]
Not entirely sure how to proceed here, so let me clarify a few things. What's the reasoning behind raising the bokeh log levels to critical?

One simple suggestion I have is that we simply solve this by raising the log level of code execution errors to critical here: https://github.com/bokeh/bokeh/blob/master/bokeh/application/application.py#L180. That makes sense to me anyway since an error when running the bokeh app code is indeed a critical error.

That said I think raising log levels of some external library on import is not a good thing to do in general.  I get that a user may not want to see low-level errors for the dask monitoring dashboard but does the log-level really need to be set that high, would ERROR level logging be okay? Could we at least defer raising the bokeh log level until the dask monitoring dashboard is started?

**Comment by mrocklin** [comment]
As long as the user experience is pleasant I don't personally have strong thoughts on what should happen.  There are two common usage patterns:

Naive use from Python.  In this case we probably want no logging:

```python
from dask.distributed import Client

client = Client()
```

CLI use, in which case we want sensible amounts of logging, for some definition of sensible.

```
$ dask-scheduler
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Local Directory: /var/folders/mg/t1rcmgbx2139c_r2ypf1nbyrjz871k/T/scheduler-pcoh4s0t
distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state
distributed.scheduler - INFO -   Scheduler at:   tcp://10.2.160.196:8786
distributed.scheduler - INFO -   dashboard at:                     :8787
```

Other than that, please use your best judgement

**Comment by philippjfr** [comment]
Okay, I just did a survey of the conditions when bokeh raises ERROR level log messages:

* The application code couldn't be parsed: Won't affect the dask dashboard since it's started programmatically and tests verify the dashboard starts
* Various situations where the bokeh server couldn't start: These will only be issued once and they are something a user might want to know about
* Various bokeh model validation errors: Should be caught before release but may arise on a new bokeh release which adds or changes validation code.
* Websocket and connection errors: These may occur due to network issues.

I think lowering the default log level to ERROR from CRITICAL would be a reasonable change in general. That said if you want different behaviors for Python vs CLI usage then I'd be happy to make the default dependent on that and then override then also override the default in our CLI commands.

**Comment by mrocklin** [comment]
We handle interactive Python usage separately here:

https://github.com/dask/distributed/blob/4953f81d7b6856f6a22f00e27476d4a554a120c2/distributed/utils.py#L681

https://github.com/dask/distributed/blob/4953f81d7b6856f6a22f00e27476d4a554a120c2/distributed/deploy/spec.py#L212-L213
