### ISSUE TITLE
Bokeh applications hang when using a TLS-secured scheduler

### ISSUE THREAD

**Issue by dkillick** [dask/distributed#1767]
Hi, we've been investigating using TLS encryption for securing schedulers running on our cluster. We've managed to get almost everything working (which is great!) apart from bokeh applications. When the scheduler starts up, part of what it tells me is this:
```
distributed.scheduler - INFO -   Scheduler at:   tls://10.0.0.83:33881
distributed.scheduler - INFO -       bokeh at:          10.0.0.83:8787
```
I can connect to the bokeh applications homepage at that address but if I try to navigate to one of the application pages (`/status`, say), it doesn't connect and the browser tells me it's "`Waiting for 10.0.0.83...`" Any ideas what's causing this or how we could work around it?

Note: we're using distributed v1.19.3, which I'm aware is not the latest release (and I haven't tested the latest release for this behaviour).

**Comment by mrocklin** [comment]
As far as I know no work has been done to support TLS in Dask's use of the bokeh server.  This isn't due to any fundamental limitation, just due to a lack of time.  Fortunately Bokeh's server is just a Tornado server, and so my guess is that anyone familiar with using TLS with Tornado (of which presumably there are a few) could probably find their way around.  I suspect that it is a matter of routing the right address and arguments around.  Some relevant sections of code in case you (or someone else) is interested in taking this on:

- https://github.com/dask/distributed/blob/e2c3328c9b146f163206eaa3d0360ceafeda53e9/distributed/scheduler.py#L738-L741
-  https://github.com/dask/distributed/blob/e2c3328c9b146f163206eaa3d0360ceafeda53e9/distributed/scheduler.py#L962-L982
-  https://github.com/dask/distributed/blob/e2c3328c9b146f163206eaa3d0360ceafeda53e9/distributed/bokeh/core.py#L12-L30

If you're at all interested in routing the appropriate options and then submitting a PR we would really appreciate it.

> Note: we're using distributed v1.19.3, which I'm aware is not the latest release (and I haven't tested the latest release for this behaviour).

I wouldn't expect anything in recent updates to change this behavior.

**Comment by dkillick** [comment]
Thanks @mrocklin! I'd love to get involved and submit a PR to add this functionality but I suspect a lack of time might be the limiting factor for me as well. I'll see what I can do.

**Comment by mrocklin** [comment]
I wonder if there are others at the Met Office that might be able to help?  cc @niallrobinson @jacobtomlinson

**Comment by jacobtomlinson** [comment]
We tend to run things behind an nginx reverse proxy which handles SSL/TLS termination. I know that isn't really an answer but it results in this being low priority for us.

**Comment by dkillick** [comment]
Actually, further investigation of this has shown this to just be due to us using an older version of bokeh - it all works fine with the latest version of bokeh 👍 As such I don't think there's anything to do here so I'm going to go ahead and close this issue. Thanks @mrocklin for engaging with us on this.
