### ISSUE TITLE
Rename Executor -> Client

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#187]
We use the term `Executor` to refer to the user interface object because it presents mostly the same API as the `concurrent.futrues.*Executor` objects.  However, this term conflicts a bit with a distributed systems point of view where the term `Executor` can refer to the thing actually doing the computation.  

The term `Client` would likely be a less creative and ambiguous name for what we now call `Executor`.

Do we want to rename `Executor` to `Client`?  We can keep the Executor term around for backwards compatibility.

cc @minrk this might apply to ipyparallel as well.  Thoughts?

**Comment by minrk** [comment]
In IPython Parallel, we have three classes:

1. Client - the object you create for connecting to the cluster
2. View - these present IPython's API for execution in different patterns (LoadBalancedView, DirectView, etc.)
3. Executor - this only exists as a compatibility wrapper around a View, to provide the `concurrent.futures.Executor` API

Working with IPython typically looks like:

```python
import ipyparallel as ipp
client = ipp.Client() # connect a client
view = client.load_balanced_view() # create a view
view.map(...) # run code
# or use the Executor interface
with view.executor as ex:
    ex.submit(...)
```

So I like the idea of reserving Executor for the common API, currently implemented as `CompatibleExecutor`. However, since your Executor *almost* matches the futures API, there is a benefit to people familiar with Executors recognizing the name.

**Comment by mrocklin** [comment]
The confusion with Spark is, I think, overly large.  I also find myself referring to Executor as "a client object" with people unfamiliar with dask or concurrent.futures (which is the majority.)

I plan to rename Executor to Client and keep Executor around as an alias.

**Comment by minrk** [comment]
Given the audience for this project, I think that makes sense. I still think it's appropriate to have references to concurrent.futures.Executor in documentation so people familiar with that interface know that they are using something they already know, but it doesn't need to be in the name of the class.

**Comment by mrocklin** [comment]
Implemented in https://github.com/dask/distributed/pull/492

**Comment by mrocklin** [comment]
Resolved
