### ISSUE TITLE
Add Client.open_dashboard

### ISSUE THREAD

**Issue by TomAugspurger** [dask/distributed#2083]
As an alternative to clicking on the repr link.

Roughly

```python
def open_dashboard(self):
    info = client.scheduler_info()
    base = info['address']
    port = info['services']['bokeh']

    # there's probably already a way to get this URL.
    url = "http://{}:{}/status".format(urlparse(base).netloc.split(":")[0],
                                       port)
    webbrowser.open(url)
```

**Comment by mrocklin** [comment]
This might be nice for tutorials

**Comment by martindurant** [comment]
We found in tutorials that the URL reported by the kubernetes cluster object and the client did not match, that the former was correct - presumably because the client doesn't know it's running inside a cluster. Maybe the parallel discussions on relative addresses fixed that, but think it needs pointing out here.

**Comment by TomAugspurger** [comment]
This approach will have the same limitations as the link in
`Client._repr_html_`.

Personally, I would use it for debugging sessions when I'm repeatedly
creating new clients / clusters, and would like to have a dashboard open
while the computation is running.

**Comment by jakirkham** [comment]
@martindurant, have struggled with this as well. Lately my solution to that problem is [`nbserverproxy`]( https://github.com/jupyterhub/nbserverproxy ), which proxies the scheduler port under the Jupyter Notebook service. Running `dask.config.set({"distributed.dashboard.link": "/proxy/{port}/status"})` sets the URL to the scheduler relative to the current URL and seems to work well regardless of the particular network config (in my limited experience). Would be curious to know if this works for you.

**Comment by mrocklin** [comment]
Conversation in this issue has separated into two equally valid points:

1.  We should have a method to open the dashboard from the client
2.  Finding the right address can sometimes be difficult

I think that conversation should continue mostly around point 1, which people seem to think is a nice idea.  Marking this as a good first issue.

**Comment by douglasdavis** [comment]
Pinging this slightly old issue -- should this still be considered a feature request? If so, @TomAugspurger do you think the PR you started is a still useful to draw some inspiration?

**Comment by TomAugspurger** [comment]
I think that we now have `Client.dashboard_link`. So in theory `webbrowser.open(client.dashboard_link)` should work just fine.

**Comment by jakirkham** [comment]
Also if this URL is rendered in a notebook, Jupyter will create a link. So that itself might be enough

**Comment by martindurant** [comment]
OK, closing this. That may still be something interesting to do here because of https://github.com/dask/distributed/pull/3744 and finding the endpoints for worker-X.

**Comment by martindurant** [comment]
(oh, but I notice that `dashboard_link` is not in the API docs)

**Comment by jakirkham** [comment]
Added to the docs with PR ( https://github.com/dask/distributed/pull/4572 )
