### ISSUE TITLE
Msgpack reports not being installed, despite being installed

### ISSUE THREAD

**Issue by Jvalal** [dask/distributed#2086]
I have competing messages on the screen. one says requirement met and the other says "distributed 1.21.8 requires msgpack, which is not installed."

So frustrating! 

<img width="788" alt="screen shot 2018-07-01 at 8 42 28 pm" src="https://user-images.githubusercontent.com/3803053/42144315-48b450b8-7d6f-11e8-9bb1-3abbac199bd2.png">

**Comment by dhirschfeld** [comment]
If you want help with that you'll have to provide a lot more context - show all the commands you entered and the complete, un-truncated output.

Also, rather than posting a screenshot it's helpful if you instead copy the complete text and paste it in the issue, using the markdown [triple-backtick syntax](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting) to ensure it's formatted properly.

**Comment by rbubley** [comment]
Try uninstalling `msgpack-python` and installing `msgpack`.

**Comment by Jvalal** [comment]
@rbubley there doesn't seem to be any msgpack installed. So confusing. How can I get an error saying it's not installed AND the requirement is met??

**Comment by Jvalal** [comment]
@dhirschfeld I'm on the install guide linked from the project page and can't get the cert installed, problem 1. Let's start there.  There were no other commands before this. I opened the terminal and this was the first thing I did. Python is installed

![screen shot 2018-07-02 at 9 59 38 am](https://user-images.githubusercontent.com/3803053/42176689-a895d2c6-7dde-11e8-896b-e276f6e02b2d.png)

**Comment by rbubley** [comment]
I really can't comment, because, as @dhirschfeld wrote, you haven't provided the context.

In the image you posted the message says `distributed 1.21.8 requires msgpack which is not installed`. You then try to install a different package, `msgpack-python` which is already installed, and then wonder why distributed is still saying that msgpack isn't installed. Maybe something isn't working, but we really can't tell.

**Comment by mrocklin** [comment]
I believe that something happened recently with how msgpack packages were named, which has resulted in this unfortunate message which, as @Jvalal points out correctly, confuses people.  

It would be great to see a solution.

**Comment by xhochy** [comment]
@Jvalal note the message is from `pip` and not distributed and also correct. The package is nowadays named `msgpack`, its previous name was `msgpack-python`. Codewise both work but `pip` would like to see `msgpack` installed to get rid of the message.

**Comment by xhochy** [comment]
@Jvalal note the message is from `pip` and not distributed and also correct. The package is nowadays named `msgpack`, its previous name was `msgpack-python`. Codewise both work but `pip` would like to see `msgpack` installed to get rid of the message.

**Comment by Jvalal** [comment]
@rbubley  what additional context is needed. Here are the steps I've taken per the install file.

# If you do not have it already, install git from https://git-scm.com/download/mac- **DONE**
	# Install the latest version of python 3 from https://www.python.org/downloads/ - **DONE**
	# and run this on the command line so that python3 can access https:// URLs:
	sudo /Applications/Python\ 3.6/Install\ Certificates.command **Get an error here.** 

That's everything I've done and as far as I've gotten. 

![screen shot 2018-07-02 at 11 33 29 am](https://user-images.githubusercontent.com/3803053/42180373-cfc16fce-7deb-11e8-8182-ecd17a3b6c04.png)

**Comment by martindurant** [comment]
@Jvalal , please refrain from posting screenshots, text annotated with back-ticks much preferred:
 ```example```

We do not know what installation recipe you are trying to follow, but that thing about Certificates does not seem to have anything to do with Dask.

**Comment by Jvalal** [comment]
@martindurant I don't know what text annotated with back-ticks much preferred means.

this install recipe >. https://github.com/GoogleCloudPlatform/tensorflow-without-a-phd/blob/master/tensorflow-mnist-tutorial/INSTALL.txt

**Comment by martindurant** [comment]
This is a back-tick: `
Use them around code in the text input box, so that we know that it is indeed code or other machine text.

Since you are apparently having problems with the recipe in tensorflow-without-a-phd , suggest you raise an issue there. For most Dask users, [conda](https://conda.io/docs/index.html) is the smoothest path to installing all requirements.

**Comment by Jvalal** [comment]
@martindurant got it. Why is that preferred over screenshots?

**Comment by martindurant** [comment]
> Why is that preferred over screenshots?

Less clutter, and the ability for us to copy your code, if there is something specific to debug.

> submitted somethint there too

Happy to close this issue?

**Comment by Jvalal** [comment]
sure. Hopefully if someone can help they'll go there.
