### ISSUE TITLE
Diagnostics

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#21]
### Motivation

When optimizing complex problems on `distributed` I run into performance issues that seem unintuitive.
In these cases it would be valuable to have more visibility into the functioning of the network both at the per-worker level and at the communication level.  

A snappy visualization here would be valuable both for performance tuning and, if it is sufficiently flashy, then also for demonstration purposes.

### Some things I would like to know per worker

1.  What is the CPU utilization?
2.  What is the RAM use?
3.  What kinds of tasks are running? (similar to the coloring used in the dask Profiler)
4.  How much time is spent communicating and serializing/deserializing?

### Information about inter-node communication

4.  How much communication is there between workers?  
5.  Which workers seem to be innudated?
6.  Which data elements are moving around the most? (again coloring similar to what is used in the dask Profiler)

### Visual Design

What is the right way to present this information to a user?  What information should be immediately visible and what other information should require some kind of interaction, either with links, hover tool-tips, etc..  It would be nice to dogfood bokeh here.

### Possible approaches

It's on me to collect this data (this is not hard) but I'm not sure what the right thing is to do with it after or during collection.  We could approach this in at least the following ways:

1.  We could have the workers record and send logs to a central point.  We could analyze these in bulk after a large set of computations.
2.  We could use existing socket mechanisms already within `distributed` to send a stream of information real time to some diagnostic process.
3.  We could have each of the workers use the web functionality of tornado to serve their diagnostic information as web endpoints.  A client application could poll from these periodically (can bokeh handle this?)

This is of moderately high priority for `distributed` development.  My hope is that @jcrist can work on this (he worked on the diagnostics for dask) but it would also be nice to get some input from some Bokeh or web developers as well, perhaps @bryevdv can recommend a good contact person to work with on this (if anyone is available.)

**Comment by minrk** [comment]
This is the kind of pattern I like using zmq PUB/SUB for. You can either connect your diagnostic collection service(s) to workers, or run a central SUB that workers connect to. A collector can then re-publish to visualization/computation/etc. as well, if you want to keep that as a separate operation. One nice thing is that there is minimal cost if the receiver of the diagnostics isn't running, since messages with no recipient are dropped.

In IPython parallel, I use a combination of broadcasting events from the schedulers and attaching metadata to the request/reply messages of each computation. I find having a handle on the diagnostics associated with a particular computation on the object wrapping the AsyncResult to be particularly useful.

**Comment by mrocklin** [comment]
Yeah this, and some of the operations I might want Nanny's to perform are the first cases where pub/sub start to become interesting.  I'll probably still stick with straight sockets for the immediate future, just to minimize the number of moving parts, but I think that moving to ZeroMQ in the near-moderate future might make sense.  

BTW, thank you for the recent pyzmq-tornado work.

**Comment by minrk** [comment]
If you are doing it with mostly a nanny and you have a central diagnostics-collecting service, you can also notify the collector via a REST API. Each request would be relatively heavy compared to persistent sockets (zmq or otherwise), but you would get to reuse very common/standard patterns.

**Comment by mrocklin** [comment]
@broxtronix brought up the idea of asynchronous diagnostics that work within the notebook.  E.g.

```python
>>> futures = e.map(function, seq)
>>> progress(futures)  # this continues to look good
[|||||||||___________]  34 %

>>>  do(some, stuff)  # even while we work on other things
```

Previously with dask our diagnostics would often block until a computation finished.  Now we can spin up things, splat a diagnostic onto the screen, and go off and do other work.  What is required to do this?  Can we integrate with an event loop within the Jupyter notebook?  Should we go with straight JavaScript instead and talk directly to the scheduler?

**Comment by minrk** [comment]
IPython kernels run a tornado eventloop, so you can hook up with that, though there are a bunch of caveats for integrating with the IPython eventloop. The main one being that computation runs in the eventloop thread, so async updates won't arrive while a blocking computation is running. You can also use threads, though the update frequency can be a bit confusing. I have a plan to make the threaded case better.

**Comment by mrocklin** [comment]
OK, sounds like we would want to run in a separate thread (which is fine and cheap)

**Comment by mrocklin** [comment]
@broxtronix @freeman-lab if you two have some time it would be great to get your thoughts on what distributed diagnostic information you've found valuable in the past, what novel information you'd like to see, and intuitive ways to present that information.

**Comment by broxtronix** [comment]
Here are a few thoughts that spring to mind:

**Scheduling / Job Diagnostics**

The most important diagnostic I would use on *every* computation is an indication of the current progress of a distributed job (i.e. a progress bar or similar).  In Spark progress is measured by stage and the job within a stage.  In `distributed` this would be a little different since the graph representing the computation does not always break down into stages (which is adds great flexibility that I am beginning to really like).  Probably the most intuitive progress update would simply report the number of completed nodes in the computation graph vs. the total.  As already discussed above, an asynchronous progress bar in the iPython notebook that updates in the background as the user calls the `compute()` method would be a-m-a-z-i-n-g!

Brainstorming for a sec here: if the user wants more customized progress updates, perhaps they could decorate their functions to help `distributed` to know which computational steps they want to track.  What if the user could annotate certain functions in their computational graphs as "checkpoints," and thereby specify which steps in their algorithms represent notable computational steps worth monitoring?  For example:

```
def low_level_function():
     ... do some low-level work not worthy of a progress update ...

@checkpoint
def high_level_function():
     ... do some high-level work ...

deferred_result1  = [ do(low_level_function)(z) for z in MOVIE_Z_SAMPLES ]
deferred_result2  = [ do(high_level_function)(elem) for elem in deferred_result1 ]
with Progress(checkpoints = True) as progress:
    final_results = deferred_result2.compute()
```
This would only report progress when high level functions are called.  Perhaps users could also supply arguments to this decorator to further enrich this functionality.  One use of this would be to allow the user to form their own ad-hoc notion of computational "stages" by allowing them to annotate certain functions as being part of certain stages.
```
@checkpoint(stage = 1)
def low_level_function():
     ... do some low-level work ...

@checkpoint(stage = 2)
def high_level_function():
     ... do some high-level work ...
```
If you really wanted to get fancy (and I realize this is asking a lot), you could allow the decorator to take a callback function as an argument that would be called with the result of the (remote) function just after it is finished running.  This would be a great hook for quickly check results, collect them (for later analysis), or to dynamically update visualizations while computations are running. 

For example, this callback could be used to check for NaNs in some intermediate step in the computational graph:
```
def check_for_nans(result):
     assert(not np.any(result != result)) # Check for NaNs!

@checkpoint(callback = check_for_nans)
def low_level_function():
     ... do some work...
```
This whole callback idea is half-baked and probably very difficult to implement.  I'm just throwing it out there as an example of a flexible user-facing debugging interface.

**Memory, Network, and CPU Diagnostics**

When using Spark, I tend to monitor the state of the machines in the cluster using [ganglia](http://ganglia.sourceforge.net/).  I track CPU usage, network transfer rates, and memory usage.  From these I am able to pretty quickly determine when a computation has gone off the rails.  Usually his also helps me narrow down the source of the problem to one of the big three: cpu, network, or memory.  In general, I find Ganglia quite useful, but it is a pain to set up and is only really useful for high-level monitoring. 

There is plenty of fine-grained monitoring to be had in the Spark web console, but I find I won't resort to looking at this information unless I'm really stumped as to why a particular algorithm is not working or performing well.  It's difficult to wade through that type of fine-grained information in their web interface.  I think it would be more useful if I had access to it in the iPython notebook.  (I suppose I could pull it in through their web API, but that is a lot of work.)   

Here are a few thoughts on tools that might be useful for debugging code in `distributed`:

Having the `dask` profiler working on the `distributed` scheduler would provide incredible visibility into CPU usage on the cluster, so this would be my top feature request.  Consistently hitting 100% CPU utilization across a cluster is actually very hard to do, and a proper time profiling tool would make it a lot easier to tune algorithms up to achieve more even utilization across all nodes in a cluster.  Time profiling also gives immediate insight into the run times for various individual computational blocks, making it easier to drill down and optimize the most expensive functions first.

CPU profiling tells half the story, but network time profiling is also important in a distributed, asynchronous system.  I would love a tool similar to the "network" tab of the Chrome developer tools, except for tracking network traffic on my cluster.  Combining the network and CPU profiling into one visualization would be particularly handy.  Such tools would be useful for addressing issues like https://github.com/blaze/distributed/issues/32.

When it comes to monitoring memory usage, it would be handy to be able to call up a series of bar charts (one for each worker) showing current memory usage.  (There are [various ways](http://stackoverflow.com/questions/938733/total-memory-used-by-python-process) this information might be harvested at the worker level, some better than others.)  An asynchronous bar chart visualization or a updating strip chart that evolves, showing memory usage as the computation runs would be even cooler (these would be close relatives of the progress bar, perhaps?).  At a low level, it would also be handy to be able to query the size of allocated memory associated with any given `Future` object, so that you could determine how big it was before fetching it from the worker to the executor.

I can probably think of more things, but that's a start!

**Comment by mrocklin** [comment]
I'm going to artificially separate diagnostics information into the following three categories

1.  Progress information on a particular set of tasks
2.  Resource use of the workers (CPU, memory, disk, network)
3.  Arbitrary querying of the scheduler state (e.g. who is working on what, how many bytes is this thing?)

### Progress information

I like the idea of diving in a bit more deeply than a progressbar.  Instead of stages (dask schedulers try very very hard to interleave everything) we could transpose this idea a bit and consider individual progress on different types of tasks, e.g.

```python
>>> executor.progress(futures)
all:      [|||||||||------------------] 30%
load:     [|||||||||||||||||||||||----] 90%
compute:  [||||-----------------------] 10%
store:    [||-------------------------]  5%
other:    [|||||||||||||||------------] 50%
```

We could get these identifiers either through decorators or actually just through the functions used.  It's typical to see only a small number of functions used in any given computation.  We do this now in the dask `Profiler`.

It's a bit tricky to know what goes into a computation because all computations are in the same soup.  It's not clear how to handle tasks that have already run when we first call progress.  We could either initialize all of the bars at `0%` and only watch progress from now or we could consider all tasks that went in to creating the result futures and so our bars would start at some possibly large percentage.

This information isn't available to the `Executor`; it must come from the scheduler.  This means that we either open up a `Queue` or, if we switch to having a remote scheduler, open up a separate stream.  This will be true of most of the diagnostics.

### Resource usage

We already record some things in the dask `ResourceProfiler`.  Presumably we can reuse that logic.  I suggest that we add this monitoring to the `Nanny` and have nannies report this information down to the scheduler.  This can also serve as regular heartbeating.  It would be up to the scheduler to digest this information and send it out as appropriate.

### Arbitrary querying of scheduler state

* What kinds of jobs is everyone working on?
* Who has a lot of tasks in their stack?
* How many bytes does this type of data take up?

There are an endless number of questions we might want to ask.  Currently I just dive into the scheduler state directly but this is a bad approach if:

1.  people unfamiliar with the guts of the scheduler were interested
2.  the scheduler lived on a remote node

This is, I think where a lot of the design work comes in and where we can start thinking about novel diagnostics and visualizations.

**Comment by mrocklin** [comment]
http://stackoverflow.com/questions/34033652/create-jupyter-notebook-object-that-changes-after-the-cell-has-run

**Comment by mrocklin** [comment]
@jcrist just pointed me to this slick video of a distributed database's diagnostic tool.  https://vimeo.com/127110709

How might views like this be useful outside of a database and within a more ad-hoc system like distributed?

**Comment by broxtronix** [comment]
Wow, Perfopticon is pretty sweet.  I particularly like the 2D heatmap (with 1D histograms projected on each axis) showing communication patterns during shuffle operations.  That's very intuitive, and conveys a lot of useful information at a glance.  The linkage between the nodes and edges and the graph and the current visualization is very nice too.  For complex graphs, drilling down interactively would be a nice feature.  

However, given how large and complex graphs can become, I'm not sure how well such a visualization would scale.  One thing I've noticed from looking at the Dask dot graphs is that it takes some effort sometimes to map the graph nodes onto the underlying bits code I am running. Everything gets a bit jumbled up in there.  This is great for interleaving computations (the top priority, obviously), but does make deciphering debugging information a bit challenging.  Perhaps it would help to color-code them based on the task type (as you suggest above for breaking out the different progress bars, which I think would be a fine way to break things down in diagnostics).  Or, by laying out the nodes in the graph so that similar task types are placed in different horizontal rows of the graph visualization, it would help to create some visual groupings.  I'm not exactly sure what will work best for the graphs, but little tweaks to the visualization would go a long way towards making information more decipherable at a glance.

Regarding progress bars:  the code bits that @mathisonian posted on StackOverflow look extremely promising!   I did not realize that Jupyter had these `Comm` objects to help bridge between Python and Javascript.  This seems like the ideal mechanism for pushing information from a Python diagnostic thread over into Javascript-land (if that does indeed work).

**Comment by mrocklin** [comment]
@fperez pointed me to this example using an asynchronous progressbar already built into IPython.

```python
from IPython.html.widgets import FloatProgress
from IPython.display import display
from time import sleep
f = FloatProgress(min=0, max=100)
display(f)
for i in xrange(100):
   sleep(0.1)
   f.value = i
```

(source https://www.reddit.com/r/Python/comments/34tdr2/a_simple_progress_bar_for_ipython_notebooks/)

By feeding this from a separate thread we were successfully able to get the progress bar to progress asynchronously to the main interactive thread.

**Comment by broxtronix** [comment]
Hey @mrocklin, I had time today to take the changes you made in #36 out for a spin, but I'm afraid I am having some trouble.  This may be due to my not understand how to properly use the new progress bar objects, but here is a quick overview of the issues:

When I follow the `dask` progress idiom, creating a temporary progress object with a `with` statement:

```
with distributed.diagnostics.progress(colormapped_images):
    results = compute(*colormapped_images, get = executor.get);
```
I get this somewhat cryptic error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-37-8e0ea946e2d2> in <module>()
      2 #with distributed.diagnostics.TextProgressBar(results):
      3 #with distributed.diagnostics.progress(colormapped_images):
----> 4 with distributed.diagnostics.progress(colormapped_images):
      5     results = compute(*colormapped_images, get = executor.get);

AttributeError: __exit__
```

I also tried this:
```
pg = distributed.diagnostics.progress(colormapped_images)
results = compute(*colormapped_images, get = executor.get);
```
This ran, but no progress bar appeared in the ipython notebook.

I was curious whether I could get the text progress bar to show up, so I also tried: 
```
results = compute(*colormapped_images, get = executor.get);
distributed.diagnostics.progress(colormapped_images, notebook = False)
```
this generated an error that looks to me like a bug [here](https://github.com/mrocklin/distributed/blob/5e06756b0acf955681d0e853785395622cdacd41/distributed/diagnostics.py#L355)?
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-52-219a6875bf95> in <module>()
      3 #with distributed.diagnostics.progress(colormapped_images):
      4 results = compute(*colormapped_images, get = executor.get);
----> 5 distributed.diagnostics.progress(colormapped_images, notebook = False)

/home/ec2-user/anaconda3/lib/python3.4/site-packages/distributed-1.5.0-py3.4.egg/distributed/diagnostics.py in progress(futures, notebook, multi)
    353         bar = TextProgressBar(futures)
    354         bar.start()
--> 355         bar._timer.join()
    356 
    357 

AttributeError: 'NoneType' object has no attribute 'join'
```
I may be totally confused here, though.  My `colormapped_images` variable is a list of futures built up from `dask.imperative`s.  What is the best way to generate a progress bar for this computation?  Thanks for your help!

**Comment by mrocklin** [comment]
Sorry, at the moment `progress` only works with futures, not with dask-y things.  Give me a bit and I'll cook up a dask->futures solution.

**Comment by broxtronix** [comment]
Roger that!  If is any help, I'm still baselining my work with `distributed` on computations that are similar in spirit to the example workflow notebook I sent out last time.  The `dask.imperative` abstraction is very powerful, and I expect I'll use it most of the time.  So, if it works in that notebook it will likely work for me in general.  

For now I'll be in good shape working without progress bars, but looking forward to having 'em!  Thank you again for adding all of these complex features!  This is some seriously impressive progress.

**Comment by mrocklin** [comment]
Noted.  I should have something for you in a small number of hours.

I have a bit more time to respond now (had something on the stove.)  I've more or less decide to embrace asynchronicity.  `progress` only operates as  a function, not a context manager.  It *must* be given an asynchronous `Future` like result.  At the moment this kills typical dask get/compute style execution, which is a synchronous API.  My intention is to produce a function like the following:

```python
>>> futures = executor.compute(*dask_vaues, sync=False)
```

I suspect that this will satisfy your immediate needs.  I also hope that it will open up more async behavior.

It's not clear that this approach will also work for existing dask workflows like `xray` but I suspect that, after we have the async system set up we can wrap around it appropriately.

**Comment by broxtronix** [comment]
Sounds great.  I'm fully in support of the asynchronous approach.  As we've discussed, I think there is great promise to be discovered there, and this framework is uniquely suited to exploring that space.

So if I'm understanding correctly, using `sync=False` will cause `executor.compute()` to return a `Future` rather than a computed result, and then I would magic up a progress bar like so?

```
futures = executor.compute(*dask_vaues, sync=False)  # Return immediately
distributed.diagnostics.progress(futures)   # Also returns immediately, but creates JS progress bar
```
That all sounds good to me!

**Comment by mrocklin** [comment]
Yes, that's correct.  I have this up in https://github.com/blaze/distributed/pull/39 , which also depends on https://github.com/blaze/dask/pull/869

**Comment by mrocklin** [comment]
I've been thinking about how to remove myself from the creation of visual diagnostics.  I'm not skilled at visual design but currently I'm required in order to expose state from the scheduler and worker. 

So how about each worker/scheduler grows a new HTTP server to host JSON/msgpack views of the data?  This server will run alongside the current TCPServer used for computation.  This is a bit less efficient / responsive because a visual diagnostic will have to query the HTTPServer repeatedly but will probably be easier to allow others to spin up basic diagnostic pages without my active engagement.

Thoughts?  Suggestions?

**Comment by mrocklin** [comment]
There is now a decent web UI.  Closing.
