### ISSUE TITLE
Merging of distributed scheduler creation tools

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/distributed#2132]
> cc @lesteve @jhamman (dask-jobqueue) @jcrist (dask-yarn) @jacobtomlinson (dask-kubernetes)

As highlighted by @mrocklin in #2118 there are a few projects which allow users to create schedulers and spawn workers into a particular cluster type. 

I would be interested in exploring how to bring these together into a single tool as I expect there is a reasonable amount of duplicated code and effort.

Does anyone have any thoughts?

**Comment by mrocklin** [comment]
There is the Cluster object in distributed/deploy/cluster.py which shares some logic, like the widget and scale/adaptive logic.  This would also be a good target for future shared development.

There are some other things that could be done, like supporting schedulers that are remote from the client, multiple queues of workers, etc..

Were there particular things that you had in mind that could be shared among the different projects?

**Comment by jacobtomlinson** [comment]
Yes an I am definitely keen to find some time to work on remote schedulers for dask-kubernetes. But I'm aware this is something which would benefit them all.

I guess I'm keen to understand the overlap of the three projects. My gut feeling is that it is quite a lot and that they could probably be merged into a single library.

**Comment by mrocklin** [comment]
I think that merging them into a single library might be tricky due more to
testing and cultural concerns rather than technical ones.  They evolve at
different paces and it would be unfortunate if the SGE developers had to
deal with YARN and vice versa.

That being said, I think that it makes sense to put as much common
functionality into dask/distributed as possible.  We've done this a couple
of times when one library develops functionality from which all of them can
benefit (like the widget that was moved from dask-kubernetes to
dask/distributed's Cluster object)

**Comment by guillaumeeb** [comment]
I agree that it would be good to have as much as possible in common here in distributed. I don't know what to put in there right know, but am interested in the discussion.

**Comment by jacobtomlinson** [comment]
With many cluster managers moving to `SpecCluster` I feel like this could be closed. 

As we have discussed here there are many reasons why merging into a single library might not be desirable, and now with `SpecCluster` we have a clearer path of inheritance where features can be pushed upstream and better consistency can be guaranteed.
