### ISSUE TITLE
Worker initialization function

### ISSUE THREAD

**Issue by dhirschfeld** [dask/distributed#2140]
As discussed in #2110 it would be able to register a function with the scheduler which is guaranteed to run on a worker when it first connects.

> Eventually it would be nice to allow clients to register functions to be run at worker start time with the scheduler that could be passed to workers as they start up.
>
> 1. Client registers func with the scheduler as a preload operation
> 2. Scheduler holds on to func
> 3. Scheduler also sends func to all workers to have them run func
> 4. Workers run func
> 5. New worker arrives, tells Scheduler that it exists
> 6. As part of saying "Hi" the scheduler also gives the worker func and tells it to run it
>
> If anyone is interested in implementing this let me know and I'll point to the various locations in the client, scheduler, and worker, where these changes would have to be made. It's a modest amount of work and would be a good introduction to the distributed system.

**Comment by mrocklin** [comment]
Agreed

**Comment by guillaumeeb** [comment]
Hi @dhirschfeld, @mrocklin, I'd like to contribute to distributed directly, is this a good place to start?

**Comment by mrocklin** [comment]
Hi @guillaumeeb , yes I think that this could be an educational place to start.  FWIW I'd love to get more people engaged in the distributed scheduler, and I think that you would be a great help to the project.

This topic would be educational because it touches the client, scheduler, and worker, and will force you to become familiar with a bit of async programming.  However, it also isn't a trivial issue and will require some work to get right.  I would expect this to take some time and a fair amount of interaction (unless you're already familiar with the codebase)

I would expect this to require the following steps:

### Test

Build a `gen_cluster` style test that uses the client to submit a startup function, verify that that function affects existing workers (two are started up by default).  Then create a new worker and verify that that worker has also been affected.

I would place this in `tests/test_worker.py`, but this is somewhat arbitrary

### Write some code

Affect code the following three places:
    
Where the worker registers with the scheduler, and receives a response back from it.  This is a good time to run code after it has connected, but before it has had a chance to do any work.

https://github.com/dask/distributed/blob/770b4afa51bbc8e5fbe77d6f6b5d2fbe1f69a7bc/distributed/worker.py#L299-L320

Where the scheduler hears the worker's initial message, and where it sends data down to it

https://github.com/dask/distributed/blob/770b4afa51bbc8e5fbe77d6f6b5d2fbe1f69a7bc/distributed/scheduler.py#L1294-L1296

Separately the client will need to add a method that takes a function from the user and submits that to the scheduler for storage.  This will require changes on the client, I recommend looking at `_cancel` and `cancel` for a simple example of how to create a dual async/sync function on the client side.  This will also require changes on the scheduler, look at `self.handlers`

https://github.com/dask/distributed/blob/master/distributed/scheduler.py#L902

The method on the scheduler should be a coroutine that does the following:

1.  Uses the `Scheduler.broadcast` method to run the function on all of the existing workers (this will use the worker's `'run'` route, see `Client.run` for an example)
2.  Stores the serialized function on the scheduler in a place to be used later in `add_worker`

### Setting expectations

Getting all of that to work well on the first try is likely to be challenging.  I recommend checking in with a WIP PR early and often.  Given how you've stuck around and helped with dask-jobqueue I'm more than willing to spend time helping out here.  I suspect that if you try to do everything without asking for help then you will quickly become frustrated and burn out.

**Comment by guillaumeeb** [comment]
Thanks @mrocklin, I'll try to look at all that calmly next week!

**Comment by Pballen** [comment]
It might be nice to extend this functionality to upload_file (so that you can upload a file to all existing workers and have that file also be uploaded to all new workers). As far as I can tell (and I'm not an expert on Dask by any stretch of the imagination), `client.run` and `client.upload_file` are very similar (the only difference is the msg they ask the scheduler to broadcast), so maybe these two features are also very similar.

**Comment by guillaumeeb** [comment]
PR submitted for this one. Have some questions about the discussion here:
- Should we add the registering of a shutdown method to the open PR?
- Same for upload_file modification, but my opinion here is to open another issue/PR.
