### ISSUE TITLE
concatenating bag of data frames does not work

### ISSUE THREAD

**Issue by petacube** [dask/distributed#2231]
I am testing this code 
from dask import data frame as dd
dd.multi.concat(list_of_dask_dd, axis=0)

where the list_of_dask is bag of dask dataframes. 
it tells me I can't use bag only python list. 

so how do I concatenate a bag of huge dataframes? without downloading and converting bag to list

**Comment by mrocklin** [comment]
You should avoid nesting dask collections within each other, generally it
often only makes sense to be lazy once.  It might make more sense to talk
about what you're trying to achieve and then maybe people can come up with
a better solution.  Often people use solutions like dask.delayed to
construct large dataframes.  The various mechanisms to construct dask
dataframes are available in this document:
http://dask.pydata.org/en/latest/dataframe-create.html

Also, we tend to prefer that people use Stack Overflow for usage questions
of the form "how do I do X?" and reserve Github for bug reports or issues
that require discussion.

**Comment by petacube** [comment]
well, I am trying to do two things
a. on the big picture assess the maturity of Dask to be used in production environment vs Spark. 
b. on a small scale  do a POC project to dive in into maturity question. 
c. dive into community size and estimate number of projects using dask on GitHub

my evaluation shows Dask is easier to use than Spark but not nessessary more mature.  Your support is very valuable and you have been far more responsive and on point than Spark dev team. However,  in my assessment  lack of "out of core algorithms" makes both of limited value to large scale data science eg machine learning. but even for simple ETL, trying to concatenate 100 million tiny data frames held in distributed bag into a single one and write it to a file does not work. I had to write them to file one by one.  Laziness as strategy seems to be limited as there are limits to nesting collections as seen above. the system that will implement out-of-core mathematics will be far robust than laziness-driven.   These are my conclusions. As for the stack overflow I am not just trying to figure how  to do one specific thing but comprehend the whole foundational ideas and their weakness which are certainly not listed in very nice documentation.
Finally, on the topic of community size I did see a few projects using dask on GitHub.  So the question of adoption is pretty open.

**Comment by TomAugspurger** [comment]
>  lack of "out of core algorithms" makes both of limited value to large scale data science

Libraries like [Dask-ML](http://ml.dask.org/) build on top of dask. What algorithms do you find missing?

> trying to concatenate 100 million tiny data frames held in distributed bag into a single one and write it to a file does not work.

Purely from a pandas point of view, this sounds inefficient. There's a decent amount of overhead to creating a DataFrame.

> As for the stack overflow I am not just trying to figure how to do one specific thing but comprehend the whole foundational ideas and their weakness which are certainly not listed in very nice documentation.

To expand on Matt's reply, your question is a perfect example of a good Stack Overflow question. It's a natural question for a newcomer to ask (especially coming from Spark), and Stack Overflow tends to get good search results. So having it there is a valuable resource for future learners.

The docs [homepags](http://dask.pydata.org/en/latest/docs.html) lays out the foundational idea, and. The array and dataframe pages list the scope of those collections, which includes things that don't work well. Perhaps you could write a similar "Scope" section for `dask.bag` with your findings?

Since you mention spark, did you see http://dask.pydata.org/en/latest/spark.html?

**Comment by Ablu** [comment]
> It might make more sense to talk
about what you're trying to achieve and then maybe people can come up with
a better solution.  Often people use solutions like dask.delayed to
construct large dataframes.

Being in the same boat:

I am trying to load a large number of files (where most process very quickly, but a few are pretty big) and then merge them together.

delayed functions add a very large overhead here since in most cases the parsing is way faster than the overhead of the delayed function.

There is a discussion at https://stackoverflow.com/questions/59324581/convert-dask-bag-of-pandas-dataframes-to-a-single-dask-dataframe that discusses a few options. But most do not look particulary great to me...

Is there something in dask that allows me to avoid batching delayed functions manually?
