### ISSUE TITLE
Unstable cluster for 200+ workers

### ISSUE THREAD

**Issue by olivier-lacroix** [dask/distributed#2252]
Hey there,

Using dask helm chart on kubernetes (latest versions), the cluster is unstable with 200+ workers, even idling: workers keep dying randomly.

I found out that setting a --death-timeout option to a higher value in the worker-deployment file seems to solve the problem (default is 3s).

- Is this expected? and is increasing death-timeout enough or are there other things to tweak for larger clusters?
- Would it make sense to set a higher default and/or to include timeout as a chart option?

Thanks,

Olivier

**Comment by mrocklin** [comment]
There is no fundamental reason that comes to mind why having a few hundred
workers would cause things to fail.

One thing to check would be that you have set resource limits on the worker
pods so that you don't get too many of them on the same node.

Assuming that that is resolved you might want to look at the dashboard of
the scheduler process and see if it is under stress (by looking at the
system tab) and if so by what (by looking at /profile-server)

**Comment by mrocklin** [comment]
@olivier-lacroix any update on this?
