### ISSUE TITLE
Create Prometheus Endpoint

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#2332]
We might consider publishing metrics at an endpoint for [Prometheus](https://prometheus.io).  This would allow standard logging and visualization tools to easily get some information about Dask.

cc @jacobtomlinson 

It might be helpful to look at [our code to host normal static pages](https://github.com/dask/distributed/blob/master/distributed/bokeh/scheduler_html.py)

**Comment by jacobtomlinson** [comment]
In order to implement this all the metrics we wish to cover need to be exposed in the [prometheus text based format](https://prometheus.io/docs/instrumenting/exposition_formats/#text-based-format) at `/metrics`.

It looks like the [`CountsJSON`](https://github.com/dask/distributed/blob/master/distributed/bokeh/scheduler_html.py#L96) endpoint is already providing the metrics we would want, so a new endpoint needs creating in the right format.

There is a prometheus [python client library](https://github.com/prometheus/client_python) which can handle the text formatting.

**Comment by xhochy** [comment]
The `CountsJSON` endpoint is very interesting on the scheduler side of things. Is there also a similar thing for the workers? Are there any metrics besides CPU/RAM usage that we want to scrape from the workers? I could think of currently:

- Stored bytes (RAM & disk)
- running tasks

**Comment by mrocklin** [comment]
There isn't anything like CountsJSON for workers, but there could be.  We
could do this by replicating the content in
distributed/bokeh/scheduler_html.py file, and then adding a listen method
to the disributed/bokeh/worker.py::BokehWorker class that is similar to the
listen method on the distributed/bokeh/scheduler.py::BokehScheduler class.

**Comment by mrocklin** [comment]
We'll probably need to add a normal HTTP server to the workers for this.  The commit that did this for the scheduler is here: 74cebfb9eeaef0b51963879403d094275e3b2b94
