### ISSUE TITLE
Bump minimum Tornado version to 5?

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#2358]
The differences between Tornado 4 and 5 can be significant at times.  This arose in https://github.com/dask/distributed/issues/2351 .  We don't currently test against Tornado 4.5 in our CI, and locally I'm able to get a few tests to fail.  

Rather than investigate these errors further, would it make sense to just drop support for Tornado 4?

If anyone is unable to switch to Tornado 5 we would love to hear about it so that we don't unknowingly break your system.

As a point of reference, both the Jupyter Notebook and Bokeh Server still require Tornado >= 4

**Comment by minrk** [comment]
The main downside that I’ve seen is in a notebook, where tornado 5 means asyncio is already running. This causes code running coroutines in a blocking way by calling `get_event_loop.run_until_complete(coro())` to fail due to the running loop.

With latest IPython and ipykernel, we now have interactive `await`, which I think is better, but I’ve seen at least a few users sticking with tornado 4.5 for a bit to keep the blocking asyncio calls working, at least while waiting for interactive async to work.

FWIW, JupyterHub now requires tornado 5 (and Python 3.5), and this hasn’t proven to be much of an issue, as far as I know.

**Comment by davidbrochart** [comment]
I had some issues with Tornado 5 and its running event loop in the Notebook, when I was running async code. But https://github.com/erdewit/nest_asyncio solved it and is as simple as adding a couple of lines.

**Comment by mrocklin** [comment]
This has been done.  Closing.
