### ISSUE TITLE
Stateful streaming operators in Dask

### ISSUE THREAD

**Issue by Yiliang-Shi** [dask/distributed#2381]
We want to build a parallel, distributed workflow management system for analyzing neural networks and we are wondering if Dask would be the right framework to build upon.

The system we envision is based on streaming — we would build pipelines of data generators and data processors (dozens of them) that continuously transfer batches of NumPy arrays between each other. Most of those processors would to maintain some state (for instance, they would maintain statistics about the data or update a statistical model). Is there a recommended "Dask way" to support this type of operations?

The Dask doc mentions Python queues, but we would like to transfer large amounts of data. Another option would be to create pipelines of actors (as in Ray), where each actor pulls data from the previous one, but the doc implies that the feature is unstable.

**Comment by mrocklin** [comment]
## Futures

The most straightforward way to do this today is with the [concurrent.futures interface](https://docs.dask.org/en/latest/futures.html).   Probably something like the following:

```python
import numpy as np
from dask.distributed import Client, as_completed
import operator

client = Client()

def acquire_data():
    return np.random.random((1000, 1000))

def accumulate(state, new):
    state = state + new
    result = state.mean()
    return state, result

accumulator = client.submit(np.zeros, (1000, 1000))

results = []
for i in range(10):
    data = client.submit(acquire_data, pure=False)
    pair = client.submit(accumulate, accumulator, data)
    accumulator = client.submit(operator.getitem, pair, 0)
    result = client.submit(operator.getitem, pair, 1)
    results.append(result)

for future, result in as_completed(results, with_results=True):
    print(result)
```

```
0.49938128111747304

0.9993265515745767
1.4989590810738218
1.9989562957667029
2.498928258379171
2.999060472612851
3.498790918855656
3.9987598385819
4.498116195139287
4.9985684754377955
```

There are some problems with this.  The scheduler will maintain the entire history of the computation, and eventually that history will grow large enough to be annoying, but that's resolvable with low-to-moderate work. 

## Streamz

There is an unmaintained side project, [streamz](https://streamz.readthedocs.io/en/latest/) that provides various APIs around this kind of work.  I gave a talk about this earlier this year that focused more on pandas workloads, but hopefully you can infer how you would do similar operations with arrays.  

https://www.youtube.com/watch?v=7i4Gcb_-fNU&t=2s

Streamz builds on the concurrent.futures interface that is desmonstrated above.

## Actors

You could also use actors, yes.  There are some benefits and costs to this choice.

1.  Bad: As you've mentioned, actors are new, and we expect that they'll undergo change more rapidly than other APIs in Dask, which are stabilized by their parent APIs (for example, the concurrent.futures API shown above is in the Python standard library).  We reserve the right to break things in the future, but for a research project like yours I wouldn't be too concerned.  The rate of change here is probably very slow relative to what you're comfortable with. 

2.  Good: Actors wouldn't have the long history problem I alluded to above, which is a bit nice

3.  Bad: Actors won't think about data locality.  You're likely to end up moving numpy arrays around your network, rather than moving functions to numpy arrays.  If your computations are fast relative to data movement costs then actors are probably a poor choice in terms of performance.

4.  Good: Actors have lower latency (300us vs 3ms for futures).  My guess is that this doesn't affect you that much, but it's the primary reason why someone might choose actors.

In general if futures work I say go for futures.  Actors are often overly complex for most jobs.  If you're doing mostly data analytic workloads where you're moving lots of data and doing relatively fast computations on them then you probably want to avoid actors and use normal task scheduling which can properly move computations to data.
