### ISSUE TITLE
Closing a client sets dask.config 'shuffle' and 'scheduler' to None

### ISSUE THREAD

**Issue by gsakkis** [dask/distributed#2473]
```
import dask
import dask.dataframe as dd
import distributed
import pandas as pd
import numpy as np


def set_index(msg=''):
    print("{} shuffle: {}".format(msg, dask.config.get('shuffle', 'MISSING')))
    print("{} scheduler: {}".format(msg, dask.config.get('scheduler', 'MISSING')))
    ddf.set_index('A').compute()


if __name__ == '__main__':
    df = pd.DataFrame({'A': np.random.rand(100)})
    ddf = dd.from_pandas(df, npartitions=2)
    set_index("before client")
    with distributed.Client():
        set_index("inside client")
    set_index("after client")
```
```
$ python tmp/dask/shuffle_none.py 
before client shuffle: MISSING
before client scheduler: MISSING
inside client shuffle: tasks
inside client scheduler: dask.distributed
after client shuffle: None
after client scheduler: None
Traceback (most recent call last):
...
NotImplementedError: Unknown shuffle method None
```

**Comment by mrocklin** [comment]
Thank you for the excellent error report @gsakkis .  This makes it very clear what is going on.  

This can be fixed in two places.

1.  We should probably remove the shuffle entry in dask.distributed if the value is None, rather than set it to None.  The relevant lines are here: 
    https://github.com/dask/distributed/blob/90758dcd79182ff7ce0cce4b4c29d46316349836/distributed/client.py#L1078-L1079

2.  Make dask.dataframe and dask.bag robust to shuffle being None, rather than missing

https://github.com/dask/dask/blob/27231f7f7f73ae2425ca8784412f0b3765d384b6/dask/dataframe/shuffle.py#L237

Probably something like 

```python
shuffle = shuffle or config.get('shuffle', None) or 'disk'
```

There might also be something for dask.bag as well

@gsakkis do you have any interest in implementing either or both of these?  (both preferred) . This should be relatively easy to do.

**Comment by gsakkis** [comment]
I'll give it a shot though I'm not sure about the tests; at least for `distributed` they're too slow and quite a few of them fail (that's after pinning pytest to 3.x; with 4.x they don't run at all).

**Comment by gsakkis** [comment]
> There might also be something for dask.bag as well

`dask.bag` actually guards against None and additionally determines shuffle based on scheduler:
```
        if shuffle is None:
            if 'distributed' in config.get('scheduler', ''):
                shuffle = 'tasks'
            else:
                shuffle = 'disk'
```
Does this logic make sense for dataframes too? If yes we should extract and reuse it for both collections.
