### ISSUE TITLE
Configurable Bokeh Host

### ISSUE THREAD

**Issue by quasiben** [dask/distributed#2580]
When creating a dask-scheduler with comm protocols others than TCP the bokeh host uses the same host defined in the scheduler:

> dask-scheduler --host=ucx://QQ.XX.YY.ZZ

`QQ.XX.YY.ZZ` is probably not accessible as a TCP endpoint for the bokeh dashboard.   In this case we should optionally allow users to define where (IP) the bokeh host should spin up

cc @mrocklin @jakirkham

**Comment by mrocklin** [comment]
We deal with this today with the `inproc://` comm used for single-node computation here:

https://github.com/dask/distributed/blob/b36e87d14e75c0cbdd0e3292ac65db2a836f74bd/distributed/scheduler.py#L1115-L1119

This just pins the listen host address to localhost when using inproc.  This is probably not a very good long term general solution, but at least it points to the right place to solve this problem.

Perhaps we need to optionally ask the user for an address to listen on, either for all services (you could imagine other diagnostic servers running) or for each service individually.

We do something similar today in how we accept a `LocalCluster(..., diagnostics_port=)` keyword, or the `--bokeh-port` keyword in the CLI.  Perhaps rather than consume a port we should consume an address.

https://github.com/dask/distributed/blob/b36e87d14e75c0cbdd0e3292ac65db2a836f74bd/distributed/deploy/local.py#L127-L135

This issue also comes up when people use IP over Infiniband in HPC settings.  The host address we pick up from the IB network interface isn't the host we want to use to show the dashboard.  The linking between these two has made HPC users unhappy for a while as well.

So, no solutions yet there, but hopefully the context above gives some information for people to start thinking about what a proper solution would be.  I'd be more than happy to significantly change how we get this information from users.  The current keywords leave something to be desired.

**Comment by quasiben** [comment]
resolved by https://github.com/dask/distributed/pull/2589

**Comment by quasiben** [comment]
tested https://github.com/dask/distributed/pull/2589 and validated the fix
