### ISSUE TITLE
`last_seen` in worker info page

### ISSUE THREAD

**Issue by quasiben** [dask/distributed#2595]
When workers die or halted it can be useful to see when that worker was last seen by the scheduler.  We should bubble this information up to the dashboard

> client.scheduler_info()
```
'tcp://172.17.0.2:43161': {'type': 'Worker',
   'id': 'tcp://172.17.0.2:43161',
   'host': '172.17.0.2',
   'resources': {},
   'local_directory': '/notebooks/dask-worker-space/worker-k540965f',
   'name': 'tcp://172.17.0.2:43161',
   'ncores': 1,
   'memory_limit': 67619300864,
   'last_seen': 1554412409.6942942,
   'services': {'nanny': 46010, 'bokeh': 34120},
   'metrics': {'cpu': 101.7,
    'memory': 472141824,
    'time': 1554412409.1895998,
    'read_bytes': 10374.966431182967,
    'write_bytes': 38095.74065486942,
    'num_fds': 69,
    'executing': 1,
    'in_memory': 2,
    'ready': 2,
    'in_flight': 1}}}}
```

**Comment by mrocklin** [comment]
We might place this here

https://github.com/dask/distributed/blob/master/distributed/bokeh/templates/worker.html

or here

https://github.com/dask/distributed/blob/master/distributed/bokeh/templates/worker-table.html

It might be nice to show not last-seen, but time since last seen or
something similar.

**Comment by andersy005** [comment]
@mrocklin, the links above are broken. When you get a chance, can you update them? It appears that  the `bokeh` directory was renamed to `dashboard`.

**Comment by jrbourbeau** [comment]
Links updated
