### ISSUE TITLE
CPU affinity of multiple workers on one node

### ISSUE THREAD

**Issue by Kobzol** [dask/distributed#264]
I'm experiencing a strange behaviour with (broadcast) scatter.
For development, I launch four workers on my PC (so they share one IP address).
The PC has 2 CPUs, each with 2 cores (so 4 hyper-threads in total).
Because the work for each worker cannot benefit from multithreading, I assign just one core to each worker (`ncores=1`).
If I distribute 4 jobs for them using a simple submit, each worker gets one job - that's fine.
However if I use scatter with broadcast and then use the data future from the scatter, the CPU affinity gets weird, just 2 cores are executing the code at once and the whole process is two times longer, so the workers probably aren't all working in parallel.
I'm using the broadcast in this way because of the use case that I described in issue #85.

Here's a toy MWE:
```python
import distributed
from tornado.ioloop import IOLoop
from threading import Thread

loop = IOLoop()
t = Thread(target=loop.start)
t.daemon = True
t.start()

scheduler = distributed.Scheduler(ip="127.0.0.1")
scheduler.start(1800)

workers = [distributed.Nanny("127.0.0.1", 1800, ncores=1) for i in xrange(4)]
map(lambda w: w.start(0), workers)


class Test(object):
    def __init__(self, x):
        self.x = x


def fn(test, y):
    result = 1
    for x in xrange(10000):
        for u in xrange(50):
            result *= test.x + y * u
    return result

executor = distributed.Executor("127.0.0.1:1800")
test = Test(10)

# Variant A
#[data_future] = executor.scatter([test], broadcast=True)
#tasks = [executor.submit(fn, data_future, i) for i in xrange(4)]

# Variant B
tasks = [executor.submit(fn, test, i) for i in xrange(4)]

data = executor.gather(tasks)
```
Variant A takes two times longer and doesn't execute on all of the cores at once.
I know that this isn't probably a typical usage for distributed, but I don't see why it would behave in this way.
Am I missing something?

**Comment by mrocklin** [comment]
I agree that that behavior looks odd.  

> I know that this isn't probably a typical usage for distributed

As far as I'm concerned this is entirely typical.  I suspect that dask's biggest strength is that it can handle things like this.  So I think that resolving things like this is important.

Out of curiousity, can you try this branch: https://github.com/dask/distributed/pull/257
I've been playing a bit with different balanced scheduling polices that might have an effect here.  I also recommend using `map` if possible (if your actual, non-MWE application permits) the scheduler will be able to balance a bit more effectively in that case.  

You could also verify with `my_executor.nbytes()` (on master branch) that the data has reached all workers after the broadcast.  Or you could do this by using `Worker` in place of `Nanny`.

**Comment by mrocklin** [comment]
I'll be out of contact much of today and busy during the weekend.  So my response on this issue may be slow for the immediate future.

**Comment by Kobzol** [comment]
The data does indeed get to all of the workers after broadcast.
I tried the MWE with the both the master branch and the balanced-scheduling branch, and in both cases even the simple submit causes only 2 cores to execute in parallel (and the broadcast behaves the same).
I double checked it with the pip 1.9.5 version and with that version the submit executes on all 4 cores.
The master and balanced-scheduling branches give me this warning during the execution: Heartbeat failed for worker <IP:port>.

**Comment by mrocklin** [comment]
OK.  I'll check this out in the near future.  Thank you for taking the time to raise the issue with a clear example.

**Comment by mrocklin** [comment]
OK, I've added some tests in https://github.com/dask/distributed/pull/257/commits/4b6b470f9e3d0d0d72be1008086eea9ad4ccea6f

I suspect that these would work with `map` or `dask.delayed` + `compute` rather than many submits.  We can do slightly better reasoning when we receive multiple tasks at a time.  We're forced to be a bit more greedy (and suboptimal) when we get tasks one at a time.  That being said, it should also be fairly straightforward to get this to work with many calls to submit.

**Comment by mrocklin** [comment]
This may be resolved in https://github.com/dask/distributed/pull/257/commits/a1b65967a0ccde8bd082a0e6f671b020baccaff1

Try pulling from `mrocklin/balanced-scheduling`

**Comment by Kobzol** [comment]
Great, now individual submits, broadcast and map use all of the four cores at once :-)
It still gives me the heartbeat warnings, but it works.
Sometimes it oscillates and some of the cores drop near to 0% utilization, but I suspect that's a normal OS dependent situation (I'm running it under virtualized Linux, so that may also cause some stirs).

**Comment by mrocklin** [comment]
I wouldn't worry about the heartbeat warnings for now; especially if there are only one or two when you start or stop your cluster.

**Comment by Kobzol** [comment]
There were about 10-20 warnings during the execution, but I don't think that it's significant, I didn't notice any problems. I will close this issue for now and if I run into any other affinity issues, I might reopen it in the future.

**Comment by mrocklin** [comment]
I'm going to reopen this for a bit, it's not entirely clear what ideal behavior is.  Here are two situations with conflicting optimal behaviors

### Case 1

```python
# with four workers
futures = [e.submit(f, i) for i in range(1000)]
```
### Case 2

```python
# with four workers
futures = [e.submit(f, i) for i in range(4)]
```

In the first case we want to batch futures together, so that neighboring futures on are the same machine.  This helps with downstream operations that might combine nearby futures like reductions or nearest neighbor interactions.

In the second case we want to implement round-robin to ensure occupancy.

The problem with `submit` is that we don't know what case we're in ahead of time.  Under `map` or `compute` we ideally have access to a larger graph and can be more intelligent.  It's not clear which way we should lean when using simple submit, towards grouping tasks together or towards spreading them out.
