### ISSUE TITLE
Notebook progress bars.

### ISSUE THREAD

**Issue by nfaggian** [dask/distributed#274]
I am noticing since an update, to the newest jupyter notebook version, my visuals for progress seem to be delayed until the tasks are finished. Is there some block now in place for updates to progress bars?

**Comment by mrocklin** [comment]
There's no block, but if you have many fast tasks then the scheduler may start to batch results a bit, yielding some stuttering behavior.  Some of this is fixed in https://github.com/dask/distributed/pull/273 . 

If you're seeing nothing for a while (more than a second) and then all complete then something is definitely odd.

**Comment by nfaggian** [comment]
Notch this down as my network.. seems better now.

**Comment by mrocklin** [comment]
Excellent.  Closing.
