### ISSUE TITLE
Extension of Prometheus Metrics Endpoint

### ISSUE THREAD

**Issue by sublinus** [dask/distributed#2792]
Hi @mrocklin,

Would you be willing to accept a contribution regarding the extension of the current metrics endpoints containing:
 
- number of tasks in states
- server tick duration

Looking forward to the contribution.

**Comment by mrocklin** [comment]
I personally don't know much about Prometheus, so I'm not sure that I
personally am the right person to answer this.  I don't know what level of
information is appropriate for prometheus endpoints. Perhaps @beberg can
help here ?

**Comment by Fra-nk** [comment]
Prometheus by default is built to handle a huge amount of metrics and since it's intended as a systems monitoring system, exposing verbose information is (imho) feasible.

- You can see some [metrics examples in the Prometheus documentation](https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-example) where an app exposes statistics on HTTP requests - IMHO a rather verbose thing.
- [Prometheus Node exporter](https://prometheus.io/docs/guides/node-exporter/#node-exporter-metrics) exposes detailed internals with a single system usually exposing 600+ metrics.
- Even the Python Prometheus client library exposes [very detailed statistics](https://github.com/prometheus/client_python/blob/master/prometheus_client/gc_collector.py#L20) on its own internal operation.

→ I think the deciding factors if a metric should (not) be exposed should be
- the cost of _collecting_ the data (usually repeatedly)
- high-level questions like "does exposing this value have security implications"

**Comment by mrocklin** [comment]
Under the criteria that @Fra-nk suggests:

>  the cost of collecting the data (usually repeatedly)

The number of tasks in states requires a full pass over the current tasks.  There are possibly 1000 to 100000 tasks on a worker at any given time.  Checking the status of each is probably fine to do every time prometheus checks in, assuming that happens every second or so.  You might want to consider the `cytoolz.frequencies` function, which is fairly fast at counting things like this.

```python
d = frequencies(self.task_state.values())
```

Tick duration seems fine.  You might consider generalizing this to all current counters and digests.  For background, we keep track of various metrics in code like this:

https://github.com/dask/distributed/blob/991391cb71492c2ecf10366bddd0dc8d526f212e/distributed/worker.py#L1880-L1884

This actually gets plotted in Dask's dashboard in the hidden [`/counters` page](
https://github.com/dask/distributed/blob/991391cb71492c2ecf10366bddd0dc8d526f212e/distributed/dashboard/worker.py#L524).  (mostly for internal development work).  Exposing these same counters and digests through Prometheus seems natural.  I would prefer a general solution here for all of them rather than one that focused on tick duration.

> high-level questions like "does exposing this value have security implications"

From a security perspective I see nothing wrong with publishing this data.

**Comment by crepererum** [comment]
Since I have worked on this, here are some details:

At least `number of tasks in states` should not be a global metric but should rather be generated on demand in the metrics collector, similar to the [implementation on the scheduler](https://github.com/dask/distributed/blob/991391cb71492c2ecf10366bddd0dc8d526f212e/distributed/dashboard/scheduler_html.py#L181-L193) and the [already existing template on the worker](https://github.com/dask/distributed/blob/991391cb71492c2ecf10366bddd0dc8d526f212e/distributed/dashboard/worker_html.py#L8-L20).

For the tick duration, I'm not sure how this should be measured.

**Comment by crepererum** [comment]
Ah, thanks @mrocklin for the insights. So the tick duration could be added in the similar fashion then. Just read it directly into the metric collector (see the linked scheduler implementation for an example).

**Comment by mrocklin** [comment]
Right, here is a minimal example:

```
In [1]: from dask.distributed import Client

In [2]: client = Client(processes=False)

In [3]: worker = client.cluster.workers[0]

In [4]: tdigest = worker.digests['tick-duration'].components[1]  # grab the middle-time component

In [5]: tdigest.quantile(50)
Out[5]: 0.0224759578704834
```

Ideally we would do this for every digest and counter

**Comment by crepererum** [comment]
> Ideally we would do this for every digest and counter

IMHO that would work. The mapped prometheus types are [Counter](https://prometheus.io/docs/concepts/metric_types/#counter) and [Summary](https://prometheus.io/docs/concepts/metric_types/#summary).

**Comment by sublinus** [comment]
> Right, here is a minimal example:
> 
> ```
> In [1]: from dask.distributed import Client
> 
> In [2]: client = Client(processes=False)
> 
> In [3]: worker = client.cluster.workers[0]
> 
> In [4]: tdigest = worker.digests['tick-duration'].components[1]  # grab the middle-time component
> 
> In [5]: tdigest.quantile(50)
> Out[5]: 0.0224759578704834
> ```
> 
> Ideally we would do this for every digest and counter

@mrocklin Thank you very much for the help!
I cannot reproduce your minimal example using python3.7 with distributed version 2.1.0.
For me the values of digests is None using the provided example.

What environment were you using providing the example?

**Comment by mrocklin** [comment]
I think that for digests we also need to install `crick` , which is, I
think, on conda-forge and PyPI (cc @jcrist  )

**Comment by jcrist** [comment]
Yes, crick is available on conda-forge and PyPI.
