### ISSUE TITLE
Persist naming vs Spark

### ISSUE THREAD

**Issue by jseabold** [dask/distributed#281]
I wasn't quite clear on what persist does just by the name. It's something akin to Spark's [parallelize](http://spark.apache.org/docs/latest/programming-guide.html#parallelized-collections) and there isn't yet an equivalent of Spark's [persist](http://spark.apache.org/docs/latest/programming-guide.html#rdd-persistence) (it's a bit of a different model). Is that right?

I'm having a bit of trouble mapping the RDD way of thinking still. I would expect persist to do something like truncate the graph of computations and checkpoint to disk on the workers.

**Comment by mrocklin** [comment]
Persist truncates the graph of computations and checkpoints the computation to *memory* on the workers.  It starts this immediately rather than after the first computation as Spark would do it.

Persisting to disk would also be doable, especially if you're willing to rely on Pickle for everything.  For performance sensitive use cases I would expect this to be handled separately by each of the collections (e.g. arrays will want to serialize themselves differently than bags) which is one reason why this doesn't exist on the scheduler-side.  

It would be easy to implement a new verb.  What do you think would be a useful and sane behavior?

**Comment by jseabold** [comment]
I get it now, and I worry I'm being nitpicky because I wasn't able to immediately grok this.

I also worry that I'm not thinking dask-like enough yet. Let me think a bit more about how I would want to use this and if that makes sense.

**Comment by mrocklin** [comment]
Nit-pickiness is thoroughly welcomed from people using dask to solve actual problems.  Good APIs are hard.

**Comment by ogrisel** [comment]
I think the documentation could better explain how `Executor.compute` and `Executor.persist` differ.

**Comment by mrocklin** [comment]
This is resolved by these docs: http://distributed.readthedocs.io/en/latest/manage-computation.html#dask-collections-to-futures
