### ISSUE TITLE
'PBSCluster' object has no attribute 'worker_spec'

### ISSUE THREAD

**Issue by diallobakary4** [dask/distributed#2817]
Hi!

I have opened [this post ](https://stackoverflow.com/questions/56836497/pbscluster-object-has-no-attribute-workers) on Stackoverflow about an error when setting up a cluster. This happens after updating to Dask 2.0.0. Would like to make sure if it is not related.

Thanks

**Comment by mrocklin** [comment]
This is likely due to the dask 2.0.0 release.  I'll take a look.

**Comment by mrocklin** [comment]
Copying content from stack overflow (also, please raise bug reports here and user questions there.  Please don't double post in the future).  I recommend closing the stack overflow question.

```python
import dask
from dask_jobqueue import PBSCluster
from dask.distributed import Client
cluster = PBSCluster(cores=24,
                     memory="20GB",
                     project='XXXX',
                     queue='smp',
                     local_directory='$TMPDIR',
                     walltime='96:00:00',
                    resource_spec='select=1:ncpus=24:mem=120GB')

max_nodes = 10
cluster.adapt(minimum=0, maximum= max_nodes, wait_count = 3)
# cluster.scale(max_nodes)
client = Client(cluster) 
client
```

I am receiving the following error:

```python-traceback
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <zmq.eventloop.ioloop.ZMQIOLoop object at 0x7fff90fce4a8>>, <Future finished exception=AttributeError("'PBSCluster' object has no attribute 'workers'",)>)
Traceback (most recent call last):
  File "/home/user/.conda/envs/bakbio/lib/python3.6/site-packages/distributed/deploy/adaptive.py", line 216, in recommendations
    current = len(self.cluster.worker_spec)
AttributeError: 'PBSCluster' object has no attribute 'worker_spec'
```

This is a bit odd actually, because we intentionally made this backwards compatible

https://github.com/dask/distributed/blob/9aa0ea60c6ba0fa8dd65b2a8005d3dbf3d65db75/distributed/deploy/adaptive.py#L215-L218

Can you verify that you're using the latest release of distributed?  If so, can you provide a full traceback?

I also tried out this code locally and things ran fine.

**Comment by diallobakary4** [comment]
Ok. I have rerun `pip install dask distributed --upgrade` and restarted the notebook I am working in and things seem to be working again. Thank you.

**Comment by mrocklin** [comment]
Glad to hear it!  Closing.

**Comment by guillaumeeb** [comment]
Just to be fair, there is a problem with Dask 2.0.0 and dask-jobqueue in adaptive mode, as described in https://github.com/dask/dask-jobqueue/issues/280. It's a little more tricky than an exception raised though. I'm going to push a new release of dask-jobqueue with the fix.
