### ISSUE TITLE
Event loop was unresponsive in Worker - using client.submit for long running task in dll

### ISSUE THREAD

**Issue by dickreuter** [dask/distributed#2942]
I have long runnings tasks that are running in a c++ dll. They are distributed onto different machines by dask distributed with a scheduler. 

My issues is that dask sometimes gets stuck. I do get quite frequently a warning "Event loop was unresponsive in Worker for ....".

What is the best way to handle this? Any suggestions are appreciated.

**Comment by mrocklin** [comment]
As that warning states, that is often caused by running code that holds
onto the GIL.  I recommend looking into whatever technology you're using to
wrap the C++ code and find how you can get the wrapping to release the
GIL.  Most technologies that do this like CTypes, Cython, SWIG, PyBind can
do this relatively easily.

**Comment by dickreuter** [comment]
But why is holding onto the GIL a problem? Why can't dask just wait?

**Comment by mrocklin** [comment]
Because the worker has to do many things at the same time, like serve data
to other workers and inform other machines that it is still active.

That's also just a warning, so things may work out just fine, but it's
telling you that odd things are happening.
