### ISSUE TITLE
Style Change to Task Stream

### ISSUE THREAD

**Issue by quasiben** [dask/distributed#3070]
Recently, I've needed more info on communication transfer, namely nbytes on the transfer.  I spent a little bit of time hacking the dashboard to include this information in the hover.  Would folks be interested in this kind of change ?  Maybe @birdsarah has thoughts here ?

<img width="1247" alt="Screen Shot 2019-09-19 at 3 25 53 PM" src="https://user-images.githubusercontent.com/1403768/65274822-36edb680-daf2-11e9-8d39-37ccd809b119.png">

Separately (but still related), I was getting the task stream on the prompt with the following:

> c.cluster.scheduler.get_task_stream() 

Is there a better way of doing this ?

**Comment by TomAugspurger** [comment]
Seems useful.

> Is there a better way of doing this ?

There's also Client.get_task_stream().

**Comment by birdsarah** [comment]
> Maybe @birdsarah has thoughts here ?

Looks nice. What do the different alphas of red imply?

**Comment by quasiben** [comment]
I believe, multiple alpha imply multiple overlapping transfers

<img width="1247" alt="Screen Shot 2019-09-19 at 5 07 10 PM" src="https://user-images.githubusercontent.com/1403768/65281183-ff860680-daff-11e9-9dc4-50873e183e34.png">

**Comment by mrocklin** [comment]
If I can suggest, I don't think that you actually care about the bandwidth of each individual transfer.  Instead, I think you actually care about the bandwidth in aggregate, perhaps grouped by task type (like "shuffle-join-drop") or data type (like `cudf.DataFrame`)

Instead of add more stuff to the task stream plot (which is pretty computationally intense already) I would prefer that we create a new plot, which is aggregated bandwidth over time, perhaps with an exponentially weighted moving average.  This is a larger change, but I think one that will help you answer the question that you want more clearly, and will provide more value in general.  

If we go this route then there are two steps:

1.  Collect bandwidth per task type.  This would be similar to https://github.com/dask/distributed/pull/2658 except that we would probably modify a `defaultdict(float)` rather than a scalar value
2.  Build a dashboard plot.  This might look a bit like the bar charts in `CurrentLoad`.

This doesn't have the immediate satisfaction of being done (I notice #3073 ) but I think it's a better choice/

Thoughts?

**Comment by quasiben** [comment]
I think while I'm debugging things I care about individual transfers.  Ideally, I would be able to easily determine how long a transfer took, how much data was sent, and which worker it was sent to.  But this is for debugging and probably not what we want in dask long term as you noted.  Also, I can probably back this out from the the prompt with `get_task_stream()`

To your point about computationally intensive plotting, wouldn't this also be expensive ?  If so, should we make some dashboards optional and rely on `dask.config` to load them ?

With all that said, I'd be happy to take on this work -- seems fun!

**Comment by mrocklin** [comment]
Individual transfers _are_ currently available through the worker dashboards (Although the UI there isn't the best).

> To your point about computationally intensive plotting, wouldn't this also be expensive ?

Thank you for thinking about performance on the dashboard.  In this case no, I don't think it would be expensive.  The task stream plot includes a glyph per task, which come through quickly (about 1kHz).  A bar plot showing bandwidth per task or bandwidth per worker-pair would have far fewer glyps (10-100), and they could be updated at a regular interval, perhaps 5Hz.

> If so, should we make some dashboards optional and rely on dask.config to load them ?

The dashboards themselves are only active if they are visible.  Bokeh handles this for us.

The computation behind the dashboards will likely occur regardless.  In this case that would be performing the exponentially weighted moving average.  However this is cheap, most of it happens on the worker, with the scheduler only updating things during heartbeats, which are lightweight (we actually intentionally make the heartbeats further apart if there are lots of workers).

**Comment by quasiben** [comment]
resolved by https://github.com/dask/distributed/pull/3094
