### ISSUE TITLE
Multiple argv lists for preload_modules

### ISSUE THREAD

**Issue by pentschev** [dask/distributed#3122]
It looks like we should be allowed to pass multiple modules to `preload_modules`, but `argv` is a list of arguments that is passed to all modules. Should we be allowed to pass a list of lists, such that each of the inner lists will then be passed to the respective module?

Specifically, https://github.com/dask/distributed/blob/master/distributed/preloading.py#L140 is where `argv` is passed to all of the import modules.

**Comment by mrocklin** [comment]
My guess is that this wasn't done because it's hard to pass a list of lists of options through the CLI.  I wonder if it's possible to safely pass extra args to all preload modules and have each only accept those that it needs.

I'm also curious why you need this.  What are you working on where you're using multiple preloads?  If there is an issue somewhere I can see for context, I'd be glad to take a look.

**Comment by pentschev** [comment]
> My guess is that this wasn't done because it's hard to pass a list of lists of options through the CLI. I wonder if it's possible to safely pass extra args to all preload modules and have each only accept those that it needs.

This makes sense. In my case I was specifically thinking of the Python API, I didn't think of the CLI case.

> I'm also curious why you need this. What are you working on where you're using multiple preloads? If there is an issue somewhere I can see for context, I'd be glad to take a look.

I'm working on having two preload scripts in dask-cuda, one to initialize CUDA context, another to initialize UCX context. The first has no arguments, the latter may have various arguments. But I think it will be easier to combine them both in a single preload script which does the trick just the same.

That said, I'm closing this issue for the time being, since this isn't strictly necessary.

Thanks @mrocklin for the clarifications!
