### ISSUE TITLE
Recommended cluster setup (nthreads, n workers) for I/O workloads?

### ISSUE THREAD

**Issue by skeller88** [dask/distributed#3205]
I'm loading millions of image files from GCS into a Kubernetes cluster that runs Dask distributed via helm. Each task loads a batch of images. I see from the [worker deployment template](https://github.com/helm/charts/blob/master/stable/dask/templates/dask-worker-deployment.yaml) that the number of threads for a worker is set to the number of CPUs for a worker, which matches [recommended best practices](https://kubernetes.dask.org/en/latest/#best-practices). To be explicit, a worker cannot have more threads than it has cpus. Am I understanding this correctly? 

That's expensive for my workload though, because then I'm paying for as many vcpus as I need threads. I can use a high cpu instance so memory costs are lower. Other than that, is there any recommended approach here? 

What I really need is a heterogeneous cluster that can do the I/O on a small number of cores, each running multiple threads, and then hand off the data to a high memory cluster with a 1-1 core to thread ratio. I see [that's already being discussed](https://github.com/dask/distributed/issues/2118), which is exciting.

**Comment by mrocklin** [comment]
You can have as many threads as you like.  You may find that there are
diminishing returns for lots of them though.  In principle if your images
are large enough then just one or two threads should be able to saturate
your network.

If you believe yourself to be bandwidth limited then I recommend asking GCP
for a large number of small VMs rather than a small number of large VMs.
My *guess* is that your overall performance won't be greatly determined by
the number of threads per worker, but it's definitely something that you
should investigate.

**Comment by skeller88** [comment]
If nthreads does not have to equal num cpus, then in this part of the documentation:

> Your Kubernetes resource limits and requests should match the --memory-limit and --nthreads parameters given to the dask-worker command. Otherwise your workers may get killed by Kubernetes as they pack into the same node and overwhelm that nodes’ available memory, leading to KilledWorker errors.

what does `requests` refer to? I'm assuming a Kubernetes resource request, but from the helm chart and the documentation it seems to imply num cpus. 

It does not currently seem possible to use a helm chart to create a dask cluster on kubernetes with more worker threads than cpus. So I should use dask-kubernetes instead, correct?

**Comment by mrocklin** [comment]
> If that's the case then it seems like an unfortunate limitation.  Maybe
you could help resolve that problem, or post a bug report there?

I believe that requests there refers to kubernetes resource requests, yes.
The warning there is mostly about memory rather than cores.  I agree though
that it's not clearly worded.  Maybe you can help find a concise way of
being more clear?

> It does not currently seem possible to use a helm chart to create a dask
cluster on kubernetes with more worker threads than cpus.

I don't know.  If that's the case then it seems like an unfortunate
limitation.  Maybe you could help resolve that problem, or post a bug
report there?

> So I should use dask-kubernetes instead, correct?

I don't know if that's best for you.  You might want to read to read these
docs to get a sense for when you might want to use the helm chart vs
dask-kubernetes: https://docs.dask.org/en/latest/setup/kubernetes.html

**Comment by skeller88** [comment]
Ok, I'll confirm the bug/limitation and post a report if so. As far as clarifying the documentation, how about rephrasing that passage to:

> Your Kubernetes resource limits should match the --memory-limit parameter given to the dask-worker command. Otherwise your workers may get killed by Kubernetes as they pack into the same node and overwhelm that nodes’ available memory, leading to KilledWorker errors.

?

**Comment by mrocklin** [comment]
Sounds good

**Comment by mrocklin** [comment]
Closing in favor of the helm issue
