### ISSUE TITLE
Numba Objects in Task Graph

### ISSUE THREAD

**Issue by quasiben** [dask/distributed#3334]
@beckernick @mrocklin and I were chatting about an issue where there seemed to be a lot of serialization of GPU objects happening in the task graph leading to idle workers.  The suspicion was that an UDF in a  `map_partition` call used a cuDF object as an argument and the scheduler was now spending a fair amount of time (de-)serializing this object for each partition.  Something like the following, I believe, captures the issue:

```python
import cudf
from dask.dataframe.utils import make_meta
import numpy as np
import dask.dataframe as dd
from dask.distributed import Client
from dask_cuda import LocalCUDACluster

CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7"
n_workers=len(CUDA_VISIBLE_DEVICES.split(','))

if __name__ == "__main__":
    cluster = LocalCUDACluster(
        interface="enp1s0f0",  # Ethernet interface
        protocol="tcp",
        n_workers=n_workers,
        CUDA_VISIBLE_DEVICES=CUDA_VISIBLE_DEVICES,
    )
    client = Client(cluster)

    cdf = cudf.datasets.timeseries()
    sr = cudf.DataFrame({'A': np.arange(2**10), 'B': np.arange(2**10)})
    ddf = dd.from_pandas(cdf, npartitions=500)

    def noop(part, sr):
        return part

    res = ddf.map_partitions(noop, sr=sr, meta=make_meta(ddf)).compute()
    print(res.head())
```

We tried using a delayed wrapping around the cuDF object (`sr` ) but this did not seem to improve anything.  I think we have been down this road before: https://stackoverflow.com/questions/57274421/how-to-pre-cache-dask-dataframe-to-all-workers-and-partitions-to-reduce-communic

**Comment by beckernick** [comment]
cc @randerzander as well

**Comment by beckernick** [comment]
I did some more exploration on this @quasiben , @mrocklin 

Just executing the no operation UDF with map_partitions seems to cause a significant amount of waiting. The following code:

```python
import time
import cudf
from dask.dataframe.utils import make_meta
import numpy as np
import dask.dataframe as dd
from dask.distributed import Client
from dask_cuda import LocalCUDACluster

CUDA_VISIBLE_DEVICES="0,1,2,3,4,5"
n_workers=len(CUDA_VISIBLE_DEVICES.split(','))

cluster = LocalCUDACluster(
    n_workers=n_workers,
    CUDA_VISIBLE_DEVICES=CUDA_VISIBLE_DEVICES,
)
client = Client(cluster)

cdf = cudf.datasets.timeseries()
ddf = dd.from_pandas(cdf, npartitions=500)

def noop(part):
    return part

res = ddf.map_partitions(noop).compute()
print(res.head())
new = ddf.x.sum().compute()
print(new)
```

causes this task graph:

![Screen Shot 2019-12-20 at 11 24 50 AM](https://user-images.githubusercontent.com/8457388/71268959-1cf38800-231c-11ea-96dc-45d12529c3b9.png)

The following code, running on a standard LocalCluster, has almost no delay in processing:

```python
import time
import cudf
from dask.dataframe.utils import make_meta
import numpy as np
import dask.dataframe as dd
from dask.distributed import Client, LocalCluster

cluster = LocalCluster()
client = Client(cluster)

pdf = cudf.datasets.timeseries().to_pandas()
ddf = dd.from_pandas(pdf, npartitions=500)

def noop(part):
    return part

res = ddf.map_partitions(noop).compute()
print(res.head())
new = ddf.x.sum().compute()
print(new)
```

![Screen Shot 2019-12-20 at 11 34 22 AM](https://user-images.githubusercontent.com/8457388/71269233-dbafa800-231c-11ea-977c-fc376bede51f.png)

Running the same pandas+dask code on the CUDA cluster also has almost no delay:


```python
import time
import cudf
from dask.dataframe.utils import make_meta
import numpy as np
import dask.dataframe as dd
from dask.distributed import Client
from dask_cuda import LocalCUDACluster

CUDA_VISIBLE_DEVICES="0,1,2,3,4,5"
n_workers=len(CUDA_VISIBLE_DEVICES.split(','))

cluster = LocalCUDACluster(
    n_workers=n_workers,
    CUDA_VISIBLE_DEVICES=CUDA_VISIBLE_DEVICES,
)
client = Client(cluster)

pdf = cudf.datasets.timeseries().to_pandas()
ddf = dd.from_pandas(pdf, npartitions=500)

def noop(part):
    return part

res = ddf.map_partitions(noop).compute()
print(res.head())
new = ddf.x.sum().compute()
print(new)
```
![Screen Shot 2019-12-20 at 11 38 56 AM](https://user-images.githubusercontent.com/8457388/71269618-bff8d180-231d-11ea-927c-3c2a2d5121a4.png)

I wonder if it may not be related to (de-)serializing cuDF objects passed to UDFs, but related to serialization behavior occurring due to the UDF itself? cc @ayushdg as well

**Comment by mrocklin** [comment]
The best way to profile these sorts of problems generally is to read through this doc: https://docs.dask.org/en/latest/phases-of-computation.html

It lists each phase of a computation, from constructing the graph, to optimizing it, serializizing it, and then finally computing it, and suggests ways in which you can isolate each phase for profiling.  

In particular, I suspect that the issue is happening in this phase: https://docs.dask.org/en/latest/phases-of-computation.html#graph-serialization

**Comment by quasiben** [comment]
I think what is happening in the the large space in the plot is the concatenation of 500 partitions:

> res = ddf.map_partitions(noop).compute()

The above line will bring all the partitions to the client and concatenate them all.  Naively, this takes roughly 18s:

```python
n = len(cdf)//500
split_cdf = [cdf.iloc[i * n:(i + 1) * n] for i in range((len(cdf) + n - 1) // n )]  
%time cudf.concat(split_cdf).head()
```

In your workflow can you instead use persist like the following:

```python
res = ddf.map_partitions(noop).persist()
wait(res)
print(res.head())
```

**Comment by beckernick** [comment]
Thanks @quasiben . Looks like it is the compute call, rather than persist in this example (tested on my side). Using persist eliminates the huge delay (though there is a small one still).

So to me, it sounds like:
- This observed behavior in this issue's example is primarily about concatenation of cuDF objets during `compute`
- We don’t fully understand what’s happening with the serialization around the `map_partitions` calls that involve cuDF objects in the context of the workflow that motivated this issue
    - There is a call to compute earlier to generate the small cuDF object, but I'd be surprised if that was the cause. Maybe I can test replacing that with a cuDF series instead of calling compute

Is that a generally accurate summary of the current status in your mind?

**Comment by quasiben** [comment]
Correct with one update.  I think the graph serialization shouldn't be an issue as along as you/we refrain from passing in external cudf series as arguments.  This can be avoided with dask.delayed as mentioned previously

**Comment by rjzamora** [comment]
> Looks like it is the compute call, rather than persist in this example (tested on my side). Using persist eliminates the huge delay (though there is a small one still).

It is worth reiterating your point that `compute` is very expensive in a distributed environment, and it should be avoided if it is not actually necessary.  When you call compute, you need to serialize/communicate/deserialize/concatinate all data on a single process (in addition to executing the actual tasks).

> Correct with one update. I think the graph serialization shouldn't be an issue as along as you/we refrain from passing in external cudf series as arguments. This can be avoided with dask.delayed as mentioned previously

agreed

**Comment by beckernick** [comment]
Thanks guys. @quasiben , didn't we try using dask.delayed before the holidays and observed the same behavior? Maybe it's something we can revisit on the workflow end to investigate more, too

**Comment by quasiben** [comment]
@beckernick, we did but i think i was ignoring the `compute` call.   What do you think about closing this issue for now and reopening or opening another if delayed does not help out?
