### ISSUE TITLE
When --dashboard-prefix is used root location is always redirected to /status without adding the prefix

### ISSUE THREAD

**Issue by cnanakos** [dask/distributed#3405]
The problem arises when using --dashboard-prefix, using http://DASHBOARD[:PORT]/PREFIX/ redirects to http://DASHBOARD[:PORT]/status instead of http://DASHBOARD[:PORT]/PREFIX/status.

**Comment by jacobtomlinson** [comment]
It would be nice to have a [minimal reproducer](https://stackoverflow.com/help/minimal-reproducible-example) here. For this issue it would be something like:

**Steps**
- Start Dask scheduler with a dashboard prefix `dask-scheduler --dashboard-prefix prefix`
- Visit the status page directly and confirm it loads http://127.0.0.1:8787/prefix/status
- Visit the bare prefix url http://127.0.0.1:8787/prefix/

**Experienced behaviour**
- I am redirected to http://127.0.0.1:8787/status

**Expected behaviour**
- I should be redirected to http://127.0.0.1:8787/prefix/status

**Comment by jacobtomlinson** [comment]
@mrocklin could you quickly weigh in as to whether this is the expected behaviour?

**Comment by mrocklin** [comment]
Yes, that behavior seems reasonable to me (although to be clear I would trust your judgement here as much or more than my own)

**Comment by jacobtomlinson** [comment]
Thanks! I guess I was more checking that this wasn't intentional behaviour for some historic reason.
