### ISSUE TITLE
Install WorkerPlugin on specific worker

### ISSUE THREAD

**Issue by H4dr1en** [dask/distributed#3502]
Hi,

I would be very interested in having the possibility to register a worker plugin to only one worker (using the name of the worker). Currently client.register_worker_plugin only broadcast the plugin to all workers.

Something that I would love to see is:
```
client.register_worker_plugin(plugin=None, name=None, workers=None)
```
Just as `client.map()` and `client.submit()` do.

Or is there already a way to do that?

**Comment by quasiben** [comment]
@H4dr1en I don't think something like this exists at the moment, but you could potentially do this with conditional checks in the plugin:

```python
class MyPlugin(WorkerPlugin):
    def __init__(self, *args, **kwargs):
        if self.name == '...':
            # do something
        else:
            pass
```

That's not very robust and requires hardcoding the name but could potentially unblock you

**Comment by H4dr1en** [comment]
Thanks for your answer, that's what I had in mind after a couple of minutes of thinking.
That hack would indeed solve my problem as a first iteration. 

Nevertheless , I see value in extending the api of register_worker_plugin, because over time the number of workers I will be using will increase at the point where it won't be maintainable to hardcode all the values in the plugin.

**Comment by mrocklin** [comment]
So adding a `workers=` keyword would be easy to do.  We can pass it through from the client method to the scheduler method and into the broadcast call, which currently supports it.  However, it would get more complicated when we start thinking about what happens when we add new workers.  We would have to keep the workers metadata around and check it every time.

More broadly people might have other requests, like only using certain hostnames, only using workers with GPUs, and so on.  Adding all of these is probably too much scope creep to be a good idea, and the right solution in these cases is probably exactly what you've decided, to run this check on the worker side in the plugin's constructor.  

> because over time the number of workers I will be using will increase at the point where it won't be maintainable to hardcode all the values in the plugin.

But you can include these values in the plugin's constructor

```python
class MyPlugin(WorkerPlugin):
    def __init__(self, desired_address):
        self.desired_address = desired_address

    def setup(self, worker):
        if worker.address != self.desired_address:
            return


client.register_worker_plugin(MyPlugin("alice:1234"))
```

Or maybe we could add a convention where if the `setup` method returns `False` then we don't include the plugin in the worker's list of plugins.

**Comment by H4dr1en** [comment]
> More broadly people might have other requests, like only using certain hostnames, only using workers with GPUs, and so on.

This is exactly my use case. I would like to attach an object interacting with the GPU to the worker, so that it can be accessed using `get_worker()` afterwards.

As you mentionned, 

> Or maybe we could add a convention where if the setup method returns False then we don't include the plugin in the worker's list of plugins.

If I register 50 `MyPlugin` in your example in 50 different workers, then each worker will have 49 useless plugins and only one actually of interest. Your solution would solve that.

Otherwise, maybe in that context `register_worker_callbacks` would make more sense? Something like:

```
def setup_engine(dask_worker, desired_address, **params):
    if dask_worker.address != desired_address:
            return
    from myPackage import myGPUEngine
    dask_worker.engine = myGPUEngine(**params)

client.register_worker_callbacks(setup_engine)
...
def job():
    get_worker().engine.work()

client.submit(job)
```

**Comment by H4dr1en** [comment]
Closing here since suggested workaround is reasonable for the use-case and ratio implementation effort/benefit is to low.
