### ISSUE TITLE
Class rpc overlaps with attributes of the same name

### ISSUE THREAD

**Issue by jakirkham** [dask/distributed#3589]
It appears we have a [class `rpc`]( https://github.com/dask/distributed/blob/511427b81f599105dc1eb4d2f35fd33aa249b4b8/distributed/core.py#L572 ) in lower case, which is atypical. This causes some confusion as it overlaps with [`Node.rpc`]( https://github.com/dask/distributed/blob/511427b81f599105dc1eb4d2f35fd33aa249b4b8/distributed/node.py#L31-L39 ), which shows up in [`ServerNode`]( https://github.com/dask/distributed/blob/511427b81f599105dc1eb4d2f35fd33aa249b4b8/distributed/node.py#L42 ) and [`Worker`]( https://github.com/dask/distributed/blob/511427b81f599105dc1eb4d2f35fd33aa249b4b8/distributed/worker.py#L90 ) as a result. It would be good to disambiguate these somehow (perhaps by capitalizing the class name?).

**Comment by mrocklin** [comment]
This was originally intentional.  It is common to call things like the following:

```python
await rpc(address="...").some_function(...)
```

With connection pools we wanted the same convention, but now with some state behind it to bundle connections.


```python
await my_thing.rpc(address="...").some_function(...)
```

We could change things if it's really important, but at this point in history it seems somewhat disruptive.
