### ISSUE TITLE
Start user-defined type of cluster by default with `Client()`

### ISSUE THREAD

**Issue by jsignell** [dask/distributed#3722]
It is often convenient to start a cluster implicitly using:

```python
from distributed import Client

client = Client()
client
```

In distributed (AFAICT) this always starts a `LocalCluster`. I was wondering if it would be reasonable to make this configurable, so that the user could set up their distributed.yaml to use KubeCluster by default. There is already a pattern for this in dask-labextension, so we could just follow that (dask-labextension could then be refactored to depend on the distributed config).

**Comment by jrbourbeau** [comment]
Thanks for raising this point @jsignell. I'm slightly hesitant to make implicit cluster creation configurable. The main reason being to avoid making things seem too magical for users. This may be a case where having a couple of lines of code to explicitly specify the cluster type could be beneficial for debugging purposes (both for users and maintainers). 

This is just my subjective opinion, I'm be curious to hear what others think

**Comment by jcrist** [comment]
Personally I like having a clear indication of how and where the cluster is deployed in the code. If I see `client = Client()` I know this code is using a local cluster. If I see `cluster = KubeCluster(...)`, I know the code is creating a cluster on k8s. Implicitly creating a cluster behind-the-scenes when calling `Client()` may be nice, but I'd argue that anything potentially expensive (both in time and in $$) should be explicit in the code so that users don't accidentally call it multiple times.

It can also be convenient to alternate between cloud and local resources, which would be trickier if `Client` is configured to start a clust er in the cloud.

**Comment by jsignell** [comment]
Ok, thanks for taking the time to explain your reasonings. That all makes sense. The lab-extension does seem like a better place for magic to live.
