### ISSUE TITLE
Display informative message if attempting to use the dashboard and bokeh isn't installed

### ISSUE THREAD

**Issue by jrbourbeau** [dask/distributed#3836]
From https://github.com/dask/distributed/issues/3741#issuecomment-635396442:

> Perhaps we should include a vanilla route under `/status` (the common
entry point for Bokeh users) that says "please install bokeh" with some
conda/pip install lines if Bokeh isn't installed.  The relevant code is
probably in distributed/http/scheduler/info.py .  I suspect that someone
even very mildly familiar with web programming could accomplish this by
copying examples that are already there.

**Comment by joshreback** [comment]
I would like to work on this, but I'm unsure of how to implement the suggested approach. Perhaps I'm missing something obvious, but if we add a route under `/status` to the Tornado server in `distributed/http/scheduler/info.py`, won't that conflict with the `/status` route on the Bokeh app? e.g, if Bokeh is installed, and the user navigates to `/status`, won't they be served by the vanilla route rather than the current status endpoint?

**Comment by mrocklin** [comment]
Good thought.  So we would probably only want to install that route if
bokeh wasn't installed.  We might accomplish this with a try-except
ImportError block.
