### ISSUE TITLE
Missing worker table and task table.

### ISSUE THREAD

**Issue by amosonn** [dask/distributed#385]
Somewhere between 1.10 and 1.11, the two tables were removed from the Bokeh UI. Perhaps they shouldn't be there by default, but there should be an option (configuration?) to enable them, they are very useful for monitoring unusually large jobs / struggling workers.

**Comment by mrocklin** [comment]
Yes, they were removed when we updated style and to a newer version of Bokeh.  They can be added back again in time.  I agree that they were useful for finding troublesome workers.

I think it might be nice to have them as a separate tab, perhaps with a callback that dives into a worker if you click on it.  

If you have interest in diving into the Bokeh code that would be really welcome.  This isn't done only because I'm time constrained.

**Comment by amosonn** [comment]
So you suggest adding a new URL (alongside /status and /tasks) for these tables? Or adding them to /status?
Adding them back in table form is pretty straight-forward, and we can undertake it. Something more fancy is probably more than we can commit to.

**Comment by mrocklin** [comment]
Bokeh now has a concept of different tabs within a single plot.  Probably all of the pages should be merged into one.

Pinging @birdsarah, can you point us to an example of having multiple tabs within the same page?

**Comment by mrocklin** [comment]
There is a `workers/` route now.  Closing.
