### ISSUE TITLE
Use cProfile across many tasks

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#392]
It would be nice to get cProfile-style profile statistics on a large distributed computation.  We can break this into three subproblems
1.  How do we run tasks within a cProfile context
2.  How do we move around pstats objects and present them back to the user
3.  How do we meaningfully aggregate pstats objects?

Pinging @minrk .  Does IPyParallel do this?  Or does this just come for free given your ability to control computational context?

**Comment by minrk** [comment]
IPython doesn't do anything like this. The closest we have is:

```python
%%px
%%prun
some_code()
```

which will profile everywhere, but doesn't do aggregation.

Since cProfile saves stats to a file when you do `python -m cProfile`, it shouldn't be difficult to serialize and move around profile objects. After profiling, `p.create_stats()` creates `p.stats` as a dict of simple (JSONable) types, so it should be feasible to merge those in a sensible way:

```python
In [26]: p = cProfile.Profile()
In [27]: p.run('time.sleep(1)')
Out[27]: <cProfile.Profile at 0x10b300db0>
In [28]: p.create_stats()
In [29]: p.stats
Out[29]:
{('<string>', 1, '<module>'): (1,
  1,
  6e-06,
  1.001421,
  {('~', 0, '<built-in method builtins.exec>'): (1, 1, 6e-06, 1.001421)}),
 ('~', 0, '<built-in method builtins.exec>'): (1,
  1,
  2.4999999999999998e-05,
  1.001446,
  {}),
 ('~', 0, '<built-in method time.sleep>'): (1,
  1,
  1.001415,
  1.001415,
  {('<string>', 1, '<module>'): (1, 1, 1.001415, 1.001415)}),
 ('~', 0, "<method 'disable' of '_lsprof.Profiler' objects>"): (1,
  1,
  1e-06,
  1e-06,
  {})}
```

**Comment by jcrist** [comment]
With the statistical profiler added in #1387 and #1403, I believe this can be closed.
