### ISSUE TITLE
Executor: async equivalent methods not listed in docs

### ISSUE THREAD

**Issue by stefanv** [dask/distributed#399]
For example, `_start`, `_result`, etc. are missing.

**Comment by mrocklin** [comment]
I'd like to keep these out of the main docs so that "normal" (non-tornado) users don't get confused by them.  We've also made a point of putting all of the docstrings into the "normal" functions, so API documentation is not likely to be particularly illuminating.  

What do you think is the best approach here?  Maybe a page with a general explanation of what's going on with the `_foo` functions and somewhat barebones API docs?

**Comment by stefanv** [comment]
A note at the bottom of the API table should be sufficient, if that'd work?
