### ISSUE TITLE
Dask workers do not properly wait for preload to finish when passing options

### ISSUE THREAD

**Issue by EmperorArthur** [dask/distributed#4169]
**What happened**:
Pre-loading with click options are not awaited.
This means any plugin which has an async setup function will not be fully loaded when the worker is "started".

> distributed.utils - INFO - Reload module test from .py file
distributed.preloading - INFO - Import preload module: test.py
/home/arthur/.virtualenvs/arhlibrary/lib/python3.8/site-packages/distributed/preloading.py:175: RuntimeWarning: coroutine 'dask_setup' was never awaited
  dask_setup.callback(self.dask_server, *context.args, **context.params)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**What you expected to happen**:
The preload should wait for `dask_setup` to finish regardless of if options are passed or not.

**Minimal Complete Verifiable Example**:

```python
import click
from distributed import Worker

@click.command()
@click.option("--some-property", type=str, required=False)
async def dask_setup(worker: Worker, some_property: str = "test"):
    await worker.client.set_metadata(some_property, "good")
    print(await worker.client.get_metadata(some_property))
```
```bash
dask-worker --preload test.py --nprocs 1 tcp://127.0.0.1:8786
```

**Anything else we need to know?**:

If the @click options are removed, then this works as expected.

The problem is in distributed.preloading.Preload.start.  It seems that click functions are explicitly not awaited!

**Environment**:

- Dask version: 2..30.0
- Python version: Python 3.8.5
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): pip

**Comment by jrbourbeau** [comment]
Thanks for raising an issue and providing an nice code example @EmperorArthur! I'm able to reproduce the `RuntimeWarning: coroutine 'dask_setup' was never awaited` when using your `dask_setup` click command (though I get this warning regardless of if there are click options or not). 

My understanding is that click commands themselves don't support coroutines (xref https://github.com/pallets/click/issues/85) so perhaps that's why we don't `await` them. That said, since we're manually retrieving the underlying function and calling it

https://github.com/dask/distributed/blob/dcb46d07318282d8a8976aadb0e4003144a42ae7/distributed/preloading.py#L172-L175

we should also be able to see if a coroutine is returned and `await` it accordingly. Is this something you're interested in working on? (no obligation though)

**Comment by EmperorArthur** [comment]
I am interested, though my time is limited, and I need to find and read any contributor guidelines for the project.

I should have been more clear, commenting out both:
````python
# @click.command()
# @click.option("--some-property", type=str, required=False)
````
Triggers the else statement:
https://github.com/dask/distributed/blob/dcb46d07318282d8a8976aadb0e4003144a42ae7/distributed/preloading.py#L176-L180

Unfortunately, that meant I had to choose between allowing arguments, or letting the function be async.  Which really sucks when the whole point is to pre-load a plugin or to talk to the scheduler.

**Comment by jrbourbeau** [comment]
No worries @EmperorArthur, I opened up a PR over at https://github.com/dask/distributed/pull/4170 to support click commands wrapping async functions. Also, for future reference, developer docs for `distributed` are available at https://distributed.dask.org/en/latest/develop.html
