### ISSUE TITLE
Remove graph expansions from graph_to_futures

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#4187]
I'm looking through `Client._graph_to_futures` now after the work from @madsbk was merged in.  It looks like we've moved the graph expansion down to calling `dask.order.order` here:

https://github.com/dask/distributed/blob/23ceba98b4830af006a21036f11891f09090eff2/distributed/client.py#L2638-L2654

I *think* that this is the last major reason to compute `dsk` and `dependencies` explicitly on the client side (other than in optimizations for low level task fusion or array slice fusion).  Is this your understanding as well @madsbk ?  If so, a good next step might be to try moving `order` up to the scheduler.

**Comment by madsbk** [comment]
Ordering is already done by the scheduler, if `priority` is None: https://github.com/dask/distributed/blob/master/distributed/scheduler.py#L1944

However, I realized that another reason to calculate `dependencies` on the client is `dumps_task()`. Since the scheduler doesn't deserialize tasks, it cannot compute the dependencies of the serialized tasks. 

Working on this Friday and today, I finally think I have a good solution. The client unpack remote data, stringify, and calculate missing key dependencies (the already calculate dependencies in the HLG are not re-calculated). For non-materialized Layers such as `Blockwise` and `ShuffleLayer`, the client implement a Layer-specific serialization/deserialization that delays the stringification and dependency calculation to the scheduler.
This way, we keep the already calculated information of the materialized Layers without forcing a materialization of all Layers on the client.
The downside is that Distributed need to implement Layer-specific serialization/deserialization for each know Layer.

**Comment by mrocklin** [comment]
> Since the scheduler doesn't deserialize tasks, it cannot compute the dependencies of the serialized tasks.

I would expect the Layer subclasses to be able to generate their own dependencies.  Is this not already the case?

> For non-materialized Layers such as Blockwise and ShuffleLayer, the client implement a Layer-specific serialization/deserialization that delays the stringification and dependency calculation to the scheduler.

Right.  To make sure I understand what you're saying here, this is the serialization that you were doing with `__reduce__` so that you can pass things up through msgpack and then have re-materialized Layers on the scheduler (although with some differences, because probably the actual function will still be serialized in the layer when it is deserialized).  

> The downside is that Distributed need to implement Layer-specific serialization/deserialization for each know Layer.

I'm not sure I understand this point

**Comment by mrocklin** [comment]
To be clear, what I think *should* happen is that 

1.  We never expand the full graph locally on the client side
2.  Ideally we also never expand dependencies, unless maybe we need to do a low level task optimization sometimes
3.  We serialize the layer using a method defined on that layer 
4.  We deserialize the layer using a method defined on that layer, except that the deserialized form probably doesn't deserialize any pickle-serialized components, like the subgraph-callable in a Blockwise
5.  The scheduler generates the full graph, using the pickle-serialized attribute stored on the deserialized form

**Comment by madsbk** [comment]
I mostly agree but there are many subtle details that are difficult to handle. I have added some thoughts in the PR: https://github.com/dask/distributed/pull/4140#issuecomment-717221583

**Comment by madsbk** [comment]
I think this has all been implemented by https://github.com/dask/distributed/pull/4140
