### ISSUE TITLE
CI failing test_auto_normalize_collection 

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/distributed#4404]
The CI on master is currently failing. The bad test is `distributed/tests/test_client.py::test_auto_normalize_collection`.

The problem appears to be in `dask/dask`. Running a `git bisect` shows that this has been failing since dask/dask#7016.

With dask and distributed `2020.12.0` the test passes. But with `dask@master` all distributed versions that I've tested fail.

**Comment by jacobtomlinson** [comment]
cc @mrocklin as the author of that PR

**Comment by mrocklin** [comment]
Hrm, interesting.  It looks like we were actually depending on normal
optimizations to not occur.  This test checks that we correctly insert
existing futures into the graph prior to sending things up to the
scheduler.  This no longer works because we fuse the task that would have
become a future into some other unrecognizable task.  What's odd is that I
wouldn't have expected this to require explicit intervention.  Maybe we
chose not to include this optimization because it took a while?

The other option here would be to include user optimizations before fusion,
or other standard optimizations that mangle the graph to the point where we
lose recognition of tasks.  We might also drop fusion altogether in the
future, which would make this moot.

**Comment by jacobtomlinson** [comment]
If we intend to `xfail` these tests as suggested in dask/dask#7035 we also need to include `distributed/tests/test_client.py::test_auto_normalize_collection_sync`.

**Comment by jakirkham** [comment]
Oops missed this issue. Had opened PR ( https://github.com/dask/distributed/pull/4405 ) to bump the timeout. Though it sounds like that may not be the right solution based on the discussion here. If so, happy to close that PR instead.
