### ISSUE TITLE
Worker and scheduler disagree about key/dep's status

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#4550]
The following was reported to me by a colleague.  It seems slightly familiar to work that @gforsyth and @fjetter have been playing with recently

Situation: S thinks W is processing K, but I suspect W's story suggests otherwise.

The key `K` appears in `client.processing()[W]`.  And the story from W:

```
k = "('nonan-d6dda2c8a4eb8ab1b66bab78b66cc0ff', 0, 28, 0)"
w = "tcp://worker-1"
client.run(lambda dask_worker: dask_worker.story(k), workers=[w])
```
gives:
```
[("('nonan-d6dda2c8a4eb8ab1b66bab78b66cc0ff', 0, 28, 0)", 'new-dep', 'waiting'),
 ("('nonan-d6dda2c8a4eb8ab1b66bab78b66cc0ff', 0, 28, 0)", 'release-key'),
 ("('nonan-d6dda2c8a4eb8ab1b66bab78b66cc0ff', 0, 28, 0)", 'new'),
 ('gather-dependencies', "('nonan-d6dda2c8a4eb8ab1b66bab78b66cc0ff', 0, 28, 0)", []),
 ("('nonan-d6dda2c8a4eb8ab1b66bab78b66cc0ff', 0, 28, 0)", 'waiting', 'flight'),
 ('request-dep',
  "('rechunk-merge-9a91cf92d9ecd81fb909b9660873466b', 28, 0)",
  'tcp://worker-2',
  ["('rechunk-merge-9a91cf92d9ecd81fb909b9660873466b', 28, 0)", "('nonan-d6dda2c8a4eb8ab1b66bab78b66cc0ff', 0, 28, 0)"]),
 ("('nonan-d6dda2c8a4eb8ab1b66bab78b66cc0ff', 0, 28, 0)", 'release-key'),
 ("('nonan-d6dda2c8a4eb8ab1b66bab78b66cc0ff', 0, 28, 0)", 'flight', 'waiting')]
```

Thoughts?  Both of K's depenendencies are in memory on W.

**Comment by gforsyth** [comment]
I strongly suspect this is related to the ambiguity of "waiting" to cover both tasks waiting for dependencies to compute vs. waiting for a computed result to arrive from another worker.
If this shows up with any regularity for a given workflow, I would be very curious to see if the mismatch occurs (and what the corresponding story is) if it's run on top of #4470 (there are still some kinks to iron out in that but it does remove the ambiguity that I think is driving this problem)

**Comment by fjetter** [comment]
I think there are a few steps to fix this problem cleanly
* Address the ambiguity of waiting in #4470 
* Figuring out how the release-key transition is actually supposed to work and whether we need something like `forgotten` on worker side (#4413)
* Wrap these two up by implementing a recommendation based transition system, similar to the scheduler (I hope we can reuse something here)

Lastly, all of this led me to the question of whether or not the system should be able to detect these drifts in state and trigger an auto correct. Currently, we're doing already parts of this, namely whenever a worker connects, it submits it's current in-memory keys to the scheduler. Something like this (as part of the hearbeat or more rarely?) would be sufficient to detect major inconsistencies. correcting it should also be trivial(ish) since the scheduler has ultimate authority.

Whether we need such a mechanism depends on how we actually can end up in this situation. If it is just because our transition code is buggy, we should fix it and not make things more complicated. However, if there are situations where this drift may occur naturally (e.g. if messages are dropped due to a disconnect) we should be able to detect it.


xref https://github.com/dask/distributed/issues/4439 (deadlocks are a different issue but I believe this is all connected to the worker state machine)

**Comment by fjetter** [comment]
Closed by https://github.com/dask/distributed/pull/4784
