### ISSUE TITLE
dask_serialize.register not working as described in the tutorial

### ISSUE THREAD

**Issue by cruyffturn** [dask/distributed#4562]
Bug reports that follow these guidelines are easier to diagnose, and so are often handled much more quickly.
-->

**What happened**:
I'm following guide in the [Dask website](https://distributed.dask.org/en/latest/serialization.html) for registering a serialization but I have received the following error:

> Exception: No dispatch for <class '__main__.Human'>

**What you expected to happen**:
I expected it to serialize the Human object.

**Minimal Complete Verifiable Example**:

```python
from dask.distributed import Client
from distributed.protocol import dask_serialize, dask_deserialize

class Human:
    def __init__(self, name):
        self.name = name

@dask_serialize.register(Human)
def serialize(human):
    header = {}
    frames = [human.name.encode()]
    return header, frames

@dask_deserialize.register(Human)
def deserialize(header, frames):
    return Human(frames[0].decode())

if __name__ == '__main__':
    
    client = Client('localhost:8786')    
    futures = client.scatter([Human('Only')])

```

**Anything else we need to know?**:

**Environment**:

- Dask version:'2021.02.0'
- Python version:3.6.12
- Operating System:Mac OS 10.14
- Install method (conda, pip, source): conda

**Comment by quasiben** [comment]
I think this is probably because of some namespacing issues and if you place the serialization bits in a separate file you should be ok.  Hmm, I think you may also run into an issue with `decode` as we are now encoding things as memoryviews.  This means using `tobytes` instead of `decode`.  cc @jakirkham in case I said something incorrect or misleading

```python
# human.py
from distributed.protocol import dask_serialize, dask_deserialize

class Human:
    def __init__(self, name):
        self.name = name

@dask_serialize.register(Human)
def serialize(human):
    header = {}
    frames = [human.name.encode()]
    return header, frames

@dask_deserialize.register(Human)
def deserialize(header, frames):
    return Human(frames[0].decode())
```

```python
# main.py
from dask.distributed import Client
from human import Human, MyObj

if __name__ == '__main__':
    client = Client()
    futures = client.scatter([Human('Only')])
```

**Comment by jakirkham** [comment]
Would also add you may need to do something like `client.run(importlib.import_module, "human")` and possibly the same things with `client.run_on_scheduler` to make sure this is imported everywhere. Dask does this for some covered types, but there is no hook for doing this for 3rd party libraries ( https://github.com/dask/distributed/issues/3831 ). So we need to do that sort of thing manually

**Comment by cruyffturn** [comment]
I really appreciate the help. It turns out that I don't have to customize serialization but I guess an update tutorial can be helpful for everyone.

**Comment by jakirkham** [comment]
Yeah we fallback to pickling if we don't otherwise know what to do. Given we support things like pickle protocol 5 (and the `pickle5` backport package on old Python versions) to avoid needless copying, this is actually a good default option. Things can be improved by custom serialization, but the bar is a lot higher after those changes went in.

**Comment by quasiben** [comment]
Thanks @cruyffturn . In #4579, while closed,  there is a [self-contained example](https://github.com/dask/distributed/pull/4579#issuecomment-797757950) which demonstrates how to use serialization in a single file.  Additionally, I am no longer able to reproduce the encoding issue.  I'm going close for now since I think the example has been validated.  If you think the language could be cleaner in the docs I would encourage to open a PR and we can work through your suggestions.
