### ISSUE TITLE
Gather feedback about distributed documentation

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#46]
I've been rolling through the documentation again.  It would be good to gather impressions from people.  Both in-depth-analysis and quick glance-overs are welcome and provide valuable feedback.

**Comment by electronwill** [comment]
I took a quick look at the quickstart and it looks great! Everything through "Gather" is very clear.

"Get" is still pretty good but makes me wonder when to use get instead of gather. Does it use the structure of a dask collection to coordinate the cluster instead of using map and submit?

"Shutdown" clearly applies to the executor and not to the cluster workers. You might add another brief section at the end explaining what command is used to reverse dcenter and dworker and shut down the cluster workers and the cluster, so the reader can reset their machine to the state it was in at the start of the quickstart.

**Comment by mrocklin** [comment]
Thanks for the feedback @electronwill !  I've removed the get section from the quickstart (it's not as critical) but refactored the same section in the longer `Executor` document linked to at the end. 

I've removed the shutdown section (again, not critical) but added a short section on `restart` which does reset the cluster state.

**Comment by mrocklin** [comment]
@koverholt may also have some feedback to provide here.  Kris if there is a bulk set of changes to suggest this might be a good place to record them.

**Comment by koverholt** [comment]
Right now, I have more concrete feedback for the Dask documentation. I'll definitely have more targeted feedback for Distributed as I work on some examples/tutorials and dive in deeper.

These are my initial impressions after reading through the Distributed docs. They are mostly related to the separation of user docs and developer-oriented/API docs.

* Consider moving all developer-facing docs into a different section.
* Better separation of user-facing calculations with Distributed vs. backend-API for Dask.
* A more explicit user section would helpful, with sections that expand on the quickstart stubs.
* distributed-by-example is pretty good. I'm planning on working on some tutorials this week that are smaller, encapsulated examples with Distributed. Mostly for my own learning, but hopefully these will serve as good tutorials here.

**Comment by mrocklin** [comment]
Oh, whoops.  Totally confused the two projects.  Sorry!

**Comment by mrocklin** [comment]
Stale, non-critical, closing.
