### ISSUE TITLE
Add Computation model to Scheduler

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#4613]
Currently the Scheduler state is aware of a hierarchy of computation elements

-  TaskState
-  TaskGroup (often equivalent to a layer in a client-side graph)
-  TaskPrefix (a collection of layers that we think have similar computational characteristics

All of these elements are useful in scheduling heuristics and visual diagnostics.

We might consider adding a fourth class to this system, the `Computation`.  This would be the result of a single `compute/persist/map` call, and would include a collection of the groups involved, as well as the context of the call (perhaps using the same frame-grabbing tricks that we use in the performance reports to show the code in the first tab).  

This would give us additional context that we could use in constructing diagnostics to give back to the user.  For example, we might be able to generate a performance_report on the fly for every compute/persist call that they've run during their session.

**Comment by fjetter** [comment]
First question coming up for me is "What kind of data do we want to store" and what do we want to do with it. I would suggest not to introduce any instrumentation without an application (if it shows up on a dashboard that's enough). I see two types of data we may collect and the reality might be a subset of this.

### Static runtime information

Static runtime information would include 
* What kind of prefixes, groups, etc. where involved
* What was the total runtime
* What was the runtime doing {compute, disk, network, etc.}
* What was peak hardware (memory per worker, num workers, etc.) usage
* Averages and sums of various dynamic quantities (task duration, bytes over network, etc.)
* IPs involved (client, workers, etc.)

### Dynamic runtime information

All of the above plus timeseries data about
* tasks per time unit
* Hardware usage per time unit
* Various histograms using crick?
* Task state evolution / How many tasks where in state X at the time
* Profiling information
* Entire performance reports
* Work stealing / transition logs??


Regardless of the kind of information we track, a few common considerations

* I think both approaches are feasible. The dynamic tracking of metadata will be a bit tougher but in general I consider storing aggregated data on this level as cheap and hopefully negligible in terms of memory and compute cost
* I see some problems upcoming in terms of memory cost if we store the entire graph indefinitely, i.e. all `TaskPrefix`, `TaskGroup` and `TaskState` objects which are referenced by the `Computation` might end up to significant memory cost (tasks include serialized code) but I would propose to just not do that :)
* Introducing a `Computation` object would also allow us to show the user a history of computations. Especially for long running clusters and/or batch oriented workflows this would add a great piece of observability where one can observe recent runtimes, etc. Enriched with aggregated performance metrics like "time spent doing {network, disk, compute, etc.}" this would add up to a very nice dashboard.
* Especially for the historization we should then include a unique ID (e.g. a true UUID generated on client side) and/or a timestamp (clock of scheduler?)
* I would probably go for a serializable (and stable-ish) object definition from the start. this kind of information feels very valuable and as a user I would probably want to persist this for my own bookkeeping. I could see this easily be implemented as a scheduler plugin which stores this stuff in a DB, blob store, etc. or it could be exposed via our HTTP server. If I implemented this from scratch, I'd go for smth like pydantic dataclasses / models (https://pydantic-docs.helpmanual.io/) but we haven't used anything like this, yet, and I don't know how easily this stuff is cythonable.


I think this idea is very powerful but I would introduce it gently, especially with our recent concerns of scheduler performance. If we intend to eventually evolve into this "remember everything" approach we need a feasible approach of lifecycle management, either by persisting this stuff to a DB (could be local disk of scheduler) or by introducing retention policies and forget stuff rather quickly again.

### Computation context

You mentioned the frame grab thingy. I have to admit that I never fully bought into this feature. In my experience this doesn't capture enough information about what's going on since the `dask.compute` and the compute logic is not necessarily at the same place. If it doesn't hurt you can fetch this of course. What's probably missing for me is the snapshot of or a reference to the entire environment, e.g. a `conda list` or `pip freeze` attached to this. At the very least for non-ad-hoc computations this should give enough information to reproduce the run.

## first steps?

boiling this down to something actionable, I would propose to start simple by generating a UUID on client side which is attached to the graph. this is translated to a computation object on scheduler side and at first we track mostly static information, e.g. once computations complete. Without browsing too much code, the computation update would probably be at a similar position as the "notify client" events. My first application would probably be a dashboard page showing a simple history view, e.g. a simple table with past runs, their UUIDs, timestamps, runtimes, etc.. From this we get some experience and can iterate.

**Comment by mrocklin** [comment]
Yeah, I think that the application that I have in mind is to store enough information to generate performance reports (or some lighter weight version of them) without the user explicitly asking us to do so  ahead of time.  

I agree that storing all TaskStates isn't feasible, but I'm hopeful that TaskGroups can provide enough summary information, especially if we enhance them (see #4671 for one example).  There is another PR in dask/dask that adds collection metadata to layers which is another good example.

I *do* find that the frame grabbing feature is useful.  As someone who looks at freqently performance reports generated by other people I find it very valuable to see what code they're running.  Looking at the profile information you might say "hrm, we're spending a lot of time reading from parquet" while if you look at the profile information and the code you might say "oh of course, you should specify the subset of columns that you actually want to read".  

> My first application would probably be a dashboard page showing a simple history view, e.g. a simple table with past runs, their UUIDs, timestamps, runtimes, etc.. From this we get some experience and can iterate

+1

**Comment by mrocklin** [comment]
Also, in the future when we reliably send layers up to the scheduler it would be useful to translate those direclty into TaskGroups.  Currently we back this information out with keynames.  Hopefully once we have layers we can store lots of more ~fun~ useful information.

**Comment by dhirschfeld** [comment]
I'm quite interested here as it sounds like this may enable my use-case for tracking different ETL jobs. I had thought annotations might be useful for that but haven't gotten around to trying them out:

> *Our dask cluster is long-lived so there is no latency for processing jobs as they come in. Each job comprises multiple underlying tasks but currently at the dask level there is no concept that any individual task is associated with a particular job - information which would be very valuable to have and which I'm hopeful we could get using task annotations. As it is currently we can see from the dashboard that there are several jobs running on the cluster but not which jobs they are.*

https://github.com/dask/distributed/pull/2180#issuecomment-562902173

**Comment by mrocklin** [comment]
This is added in #4972
