### ISSUE TITLE
Exposing workers' SystemMonitors to scheduler

### ISSUE THREAD

**Issue by charlesbluca** [dask/distributed#4630]
I am working on [GPU] worker resource tracking, as discussed in #4494 - some suggestions that came up were:

- Showing the user the average/peak usage of a worker
- Plotting a time series of the worker(s) metrics, similar to the dashboard's System tab

In working on these suggestions in #4614 and #4627, I've noticed some limitations centered around the fact that the scheduler can only access worker resource metrics through a `WorkerState` object; this means that it only has access to *present* worker metrics, as past metrics are thrown out.

It is still possible to make a dashboard component with time series / aggregated charts of worker resources, but this requires the metrics from the `WorkerState` to be collected within the component itself, which has some issues:

- Reloading the component causes all this data to be thrown out, meaning all plots and charts will be reset.
- Because the performance report loads components *after* an operation is finished, these components will only be populated with worker data from after the profiling period.

The workers have their own `SystemMonitors` similar to the scheduler, which should be logging most of the metrics we're interested in,  though I don't think there is any way to access them from the scheduler object - can we make it so they are accessible?

```
>>> scheduler.worker_monitors
SortedDict({
    'tcp://127.0.0.1:34215': <SystemMonitor: cpu: 6 memory: 565 MB fds: 209>,
    'tcp://127.0.0.1:37983': <SystemMonitor: cpu: 6 memory: 565 MB fds: 209>, 
    'tcp://127.0.0.1:38587': <SystemMonitor: cpu: 6 memory: 565 MB fds: 209>, 
    'tcp://127.0.0.1:39987': <SystemMonitor: cpu: 6 memory: 565 MB fds: 209>, 
    'tcp://127.0.0.1:41055': <SystemMonitor: cpu: 6 memory: 565 MB fds: 209>, 
    'tcp://127.0.0.1:41683': <SystemMonitor: cpu: 6 memory: 565 MB fds: 209>, 
    'tcp://127.0.0.1:44779': <SystemMonitor: cpu: 6 memory: 565 MB fds: 209>, 
    'tcp://127.0.0.1:45823': <SystemMonitor: cpu: 6 memory: 565 MB fds: 209>
    })
```

This could allow for more advanced charting / plotting of worker resources.

**Comment by quasiben** [comment]
Thanks for the detailed write-up @charlesbluca!  I'm not sure what is best here.  Some of my thoughts/concerns:

1) The nanny is not always around -- some users will run the dask worker with the `no-nanny` option.  But maybe that's ok, they won't be able to get this info unless the nanny is actively monitoring resource consumption
2) Reloading the component in the live dashboard is ok.  I believe this happens for the dashboard components as well like `/individual-memory-by-key`.   However, for the performance report we could, query all the nannies when the time comes to pull all the data -- there's probably a better way but simply `client.run(lambda dask_worker: dask_worker.monitor.gpu/cpu/memory`
3) Instead of the nannies, we can store metrics from the worker state in a configurable object like https://github.com/dask/distributed/blob/3b8b97e31ed10598531fb458b53db16683c92c47/distributed/scheduler.py#L3275-L3276

this would be stored during the [heartbeat_worker](https://github.com/dask/distributed/blob/3b8b97e31ed10598531fb458b53db16683c92c47/distributed/scheduler.py#L3604) call

@jacobtomlinson do you have any additional thoughts ?

**Comment by charlesbluca** [comment]
> they won't be able to get this info unless the nanny is actively monitoring resource consumption

I was under the impression that workers and nannies, both being subclasses of `ServerNode` and `Server`, should each have their own independent monitors - is it the nanny's monitor we're interested for keeping track of worker resource consumption?

> However, for the performance report we could, query all the nannies when the time comes to pull all the data

This sounds like a good solution that I'll try out. I guess the idea of making the worker monitors accessible to the scheduler is that it would make the process of generating these plots on the performance report / dashboard essentially congruous to how it's being done in #4561, but that's not really a big deal.

> we can store metrics from the worker state in a configurable object

I guess my concern is if this is redundant; if the `WorkerState` is already getting its metrics from some existing monitor, wouldn't storing this data in a configurable object within the scheduler be essentially recreating that original monitor?

**Comment by jacobtomlinson** [comment]
> query all the nannies when the time comes to pull all the data

I wonder if we should make this an RPC call to retrieve metrics?

**Comment by charlesbluca** [comment]
> I wonder if we should make this an RPC call to retrieve metrics?

That sounds like a good idea - a worker handler function could return the output of `worker.monitor.quantities` or optionally `worker.monitor.range_query(...)`, which could then maybe be gathered by something like `scheduler.worker_monitors(count=None)` - does that sound doable?
