### ISSUE TITLE
Repeatedly use the same worker on first task

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#4637]
Apparently in a quiet cluster we end up sending new tasks to the same worker repeatedly.  So probably the following test would fail:

```python
@gen_cluster(client=True)
def test_round_robin(c, s, a, b):
    await c.submit(inc, 1)
    await c.submit(inc, 2)
    await c.submit(inc, 3)
    assert a.transition_log and b.transition_log
```

This outcome is determined here:

https://github.com/dask/distributed/blob/bf9ddab3fd67c33b0d87da4f18bcdc7e47262393/distributed/scheduler.py#L2122-L2136

It looks like when there are no dependencies and we have only a few workers we currently choose the worker with minimum occupancy.  In a quiet cluster all workers have zero occupancy, so probably we're getting whatever Python uses to break a tie in this setting.

In the case where the occupancy is zero we might do something like a round-robin (this is done just below in the case where we have greater than 20 workers) among the worker pool for as long as that worker has zero occupancy.

Reported in conversation by @crusaderky

**Comment by douglasdavis** [comment]
Tinkering with this. The test indeed fails ;) but perhaps the reason is not what you were trying to trigger? I'm seeing `transition_log` is not an attribute of `distributed.worker.Worker`. Searching through the repo I only see instances of `s.transition_log` scattered in a bunch of tests.

Is your `assert` trying to test that both workers `a` and `b` have some evidence of usage? I might be barking up the wrong tree.

**Comment by mrocklin** [comment]
> Is your assert trying to test that both workers a and b have some evidence of usage?

Yes, this was exactly my intent.  The issue was authored in haste, my apologies for the messiness here.  Looking again at worker.py it looks like we might look at `Worker.log` instead.

**Comment by douglasdavis** [comment]
Thanks for the clarification!
