### ISSUE TITLE
performance report - Number of tasks limited to 100k ?

### ISSUE THREAD

**Issue by maawoo** [dask/distributed#4773]
**What happened**:
On the first page of the performance report it lists the `number of tasks`.
I've run two separate computations recently and used the report (which is great btw, thanks!) but both times it listed exactly 100000 tasks instead of ~174000 tasks. Is it capped for some reason or really a bug? Couldn't find anything else about this via a quick check of existing issues.

**Environment**:

- Dask version:  2021.4.0
- Python version: 3.7.10
- Operating System: Linux / Pop!_OS 20.10 x86_64
- Install method (conda, pip, source): conda

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @maawoo, glad to hear you're finding performance reports useful! You're indeed correct that the total number of tasks is capped at 100k. I think this is to limit the total amount of memory taken up on the scheduler by the data that goes into the task stream. (otherwise it would grow indefinitely). 

There is a `distributed.scheduler.dashboard.tasks.task-stream-length` configuration value

https://github.com/dask/distributed/blob/42e3f22ef1d9d3dcb494bd4e546f9ca6f2d54891/distributed/distributed.yaml#L37

which allows you to increase that 100k limit

**Comment by maawoo** [comment]
Thanks for your quick reply! 
That makes sense but good to have the option to configure it manually 👍🏻
