### ISSUE TITLE
Scheduler Experiments

### ISSUE THREAD

**Issue by quasiben** [dask/distributed#4881]
1. Is tornado usage causing significant performance degradations ? 
a. Should we replace tornado with asyncio/custom library (uvloop friendly)
b. Test UCX (TCP only) this will not use tornado for comms and give us some idea of the performance benefits if we replaced tornado

2. Are we sending messages too frequently ?
 a. We can batch writes from worker -> scheduler by increasing worker batch sizes (2ms -> 20ms)

cc @gjoseph92

**Comment by fjetter** [comment]
> Are we sending messages too frequently ?

I'd be interested in some statistics for this, e.g. how large are our batches we send on average (# msgs not necessarily byte size)

**Comment by mrocklin** [comment]
It would be easy to add some basic running statistics on the BatchedSend
object to start.  That's something that I could imagine putting into main.

**Comment by quasiben** [comment]
UCX Experiment (Linux Only):

Build UCX/UCX-Py from latest:

```
conda create -n ucx -c conda-forge    automake make libtool pkg-config cython setuptools libhwloc psutil dask distributed
git clone https://github.com/openucx/ucx
conda activate ucx
cd ucx
./autogen
mkdir build
../contrib/configure-release --prefix=$CONDA_PREFIX --enable-debug --enable-mt --disable-cma --disable-numa
make -j install

cd -
git clone git@github.com:rapidsai/ucx-py
cd ucx-py
python -m pip install .
```

Configure scheduler:

> UCX_TCP_TX_SEG_SIZE=8M UCX_TCP_RX_SEG_SIZE=8M dask-scheduler --protocol ucx

Worker:

> UCX_TCP_TX_SEG_SIZE=8M UCX_TCP_RX_SEG_SIZE=8M dask-worker ucx://192.168.1.43:8786 --protocol ucx

Client
> UCX_TCP_TX_SEG_SIZE=8M UCX_TCP_RX_SEG_SIZE=8M python foo.py

The [UCX_TCP_TX/RX_SEG_SIZE](https://ucx-py.readthedocs.io/en/latest/configuration.html#ucx-tcp-rx-seg-size) env var is something which can be tuned.  We've found `8M` to be a good size for setting the send/receive buffer size but have not investigated deeply here


cc @gjoseph92

**Comment by mrocklin** [comment]
Gabe had decent results with batching messages, which shows that there are
certainly some benefits to be gained.  I do think it would be useful to do
the UCX experiment as well to see if it's more about Tornado IOStreams or
more about the concurrency system, but in general we have good signal that
there is room for optimization here.

**Comment by gjoseph92** [comment]
Here are some initial batched send results.

I made the worker batched send interval configurable in my [distributed fork](https://github.com/dask/distributed/compare/main...gjoseph92:worker/config-batched-send-interval?expand=1). Here are profile results:

_Note that when looking at speedscope profiles, make sure `MainThread` is selected via the thread selector at the top or the `n` key_

#### GC active (normal)
* Performance reports: [2ms batched send (`main`)](https://rawcdn.githack.com/gjoseph92/dask-profiling-coiled/370ae24b7ae81636c310d68bf9f876a63decea08/results/cython-shuffle-gc.html?raw=true) -> [20ms batched send](https://rawcdn.githack.com/gjoseph92/dask-profiling-coiled/5ea8e50f45752ad444796de26d25abb02a018fbd/results/cython-shuffle-gc-20ms-batched-send.html?raw=true)

#### GC disabled (better for comparing speedscope profiles, so GC pauses don't skew runtimes)
* Performance reports: [2ms batched send (`main`)](https://rawcdn.githack.com/gjoseph92/dask-profiling-coiled/5f84365d81cfde61aabd5e5fcec73b309fde8e2a/results/cython-shuffle-nogc.html?raw=true) -> [20ms batched send](https://rawcdn.githack.com/gjoseph92/dask-profiling-coiled/451d3fd4abb4dd55ac39f3cecd3752cf67f34c5a/results/cython-shuffle-nogc-20ms-batched-send.html?raw=true)
* Speedscope profiles: [2ms batched send (`main`)](https://www.speedscope.app/#profileURL=https%3A%2F%2Frawcdn.githack.com%2Fgjoseph92%2Fdask-profiling-coiled%2F5f84365d81cfde61aabd5e5fcec73b309fde8e2a%2Fresults%2Fcython-shuffle-nogc.json%3Fraw%3Dtrue) -> [20ms batched send](https://www.speedscope.app/#profileURL=https%3A%2F%2Frawcdn.githack.com%2Fgjoseph92%2Fdask-profiling-coiled%2F451d3fd4abb4dd55ac39f3cecd3752cf67f34c5a%2Fresults%2Fcython-shuffle-nogc-20ms-batched-send.json%3Fraw%3Dtrue)

Notable observations:
* There may be a minor speedup (~8%, 10sec) from the longer batched-send interval under normal GC. However, these profiles are only run once; we'd need to run many times and look at distributions to determine if any change in runtime is real. Though having run a lot of these, ~100sec is round what I'd expect for `main` right now, and the speedup reproduced a couple times, so I think it's real. I can't say the exact magnitude though.
* Very negligible speedup (~4%, 3sec) when GC is disabled. Not sure if this is because:
  1. Having GC off makes `read`s more efficient, so doing fewer of them matters less.
  1. They're totally orthogonal, but everything is 2x faster with GC disabled, including this speedup
* A longer batched-send means fewer `read`s on the scheduler. This is what was supposed to happen, but nice to confirm that it actually did. Making batched-send 10x longer led to about 2x fewer `read` calls, and brought the amount of time spend in `handle_stream ` (read, deserialize, etc.) from 18% to 10%:
  ![Screen Shot 2021-06-10 at 7 41 07 PM](https://user-images.githubusercontent.com/3309802/121618613-4d554780-ca24-11eb-9d91-1b8790005ab9.png)

So I'm not seeing a strong conclusion in this yet. We know `read` is slow / has high overhead, and here we managed to call it a lot less—great! And it made things a bit better, though not a ton better. Perhaps it made them better by around how much we thought it would? I think having BatchedSend statistics and trying out more intervals would help here.

I also want to note again: turning off GC is still giving us a 30% reduction in runtime ([gc](https://rawcdn.githack.com/gjoseph92/dask-profiling-coiled/370ae24b7ae81636c310d68bf9f876a63decea08/results/cython-shuffle-gc.html?raw=true) -> [no gc](https://rawcdn.githack.com/gjoseph92/dask-profiling-coiled/5f84365d81cfde61aabd5e5fcec73b309fde8e2a/results/cython-shuffle-nogc.html?raw=true))! Also, in the system tab, the scheduler memory usage is roughly similar (would need to test on much longer-running clusters to be sure about that though). I still think this is worth more investigation.

**Comment by mrocklin** [comment]
This is exciting.  I see two possible actions:

1. Improve our comm infrastructure to use some lower-level asyncio protocol rather than Tornado
2. Have the scheduler identify that it is under strain and ask workers to slow down on their batch rates.  We do something similar in two ways today
     1. Heartbeat frequencies are sent from scheduler to workers on every heartbeat response.   Based on the number of current workers the scheduler tells the worker to check back in in longer and longer intervals.  This shows a mechanism by which we can convey information about desired timings to the worker
     2. The reevaluate_occupancy periodic callback regulates itself by tracking CPU usage.

    I suggest that we track CPU usage on the scheduler (we already do this with the SystemMonitor) and if that usage gets above a certain amount, and if we have received many messages, then we start asking workers to slow down.  How do we check to see if we've received many messages?  Maybe we keep an exponentially weighted moving average of the time between the last hundred messages.   We can do this by keeping a bit of state on the scheduler and adding an `every_cycle` method that does an EMWA on every received message.


We should consider both.  The second option is easier.  The first option is more general.

**Comment by fjetter** [comment]
I am currently a bit surprised about the `2ms` default interval. that's incredibly small (I cannot even ping my own router in that time but that's probably my crappy home network 😁 ). I would argue this should be at the very least a bit larger than our network latencies, especially considering that we're performing serialization and stuff as well. While our latency measurements are a bit crude, that could also be used for a minimal bound. otoh, I'm not a network expert and this comment may be nonsense 🤷

**Comment by mrocklin** [comment]
I remember originally tuning this number by running something like a rapid ping-pong computation and bringing this number down until it no longer had an effect.  I agree that we could probably bump it up to something like 5ms by default and probably be fine.  We could also make it configurable.  

I like the idea of it being auto-tunable though.  I think that this is probably pretty doable.  It worked well for heartbeats.  No one has complained about those being too frequent or too costly since we set up the auto-tuning behavior.

**Comment by fjetter** [comment]
> We could also make it configurable.

> I like the idea of it being auto-tunable though.

I agree with you and I would prefer the auto tune over introducing another expert level parameter no actual user can reason about. That also feels like the only sensible way to handle scaling well, even if it is as simple as the heartbeat scaling.

**Comment by jakirkham** [comment]
Gabe, have we been able to trackdown what is being GC'd? Is it particular `*State` objects, `Task*` objects, builtin Python objects, or something else? Also does it show up at a particular time like serialization, task submission, task completion, etc.?

**Comment by gjoseph92** [comment]
@jakirkham I haven't looked into GC further. And I haven't noticed much pattern around when it shows up, though you can see [on the profile](https://www.speedscope.app/#profileURL=https%3A%2F%2Frawcdn.githack.com%2Fgjoseph92%2Fdask-profiling-coiled%2F370ae24b7ae81636c310d68bf9f876a63decea08%2Fresults%2Fcython-shuffle-gc.json%3Fraw%3Dtrue) it seems to be at a relatively regular interval.

**Comment by gjoseph92** [comment]
Update: I've also tried a 60ms, 120ms, 500ms interval (just to push to the extreme). The amount of time spent in reads does decrease with each of these, but interestingly the overall runtime doesn't seem to change much. 

### GC active
* Performance report: [cython-shuffle-gc-20ms-batched-send.html](https://rawcdn.githack.com/gjoseph92/dask-profiling-coiled/5ea8e50f45752ad444796de26d25abb02a018fbd/results/cython-shuffle-gc-20ms-batched-send.html?raw=true)
* Performance report: [cython-shuffle-gc-60ms-batched-send.html](https://rawcdn.githack.com/gjoseph92/dask-profiling-coiled/6e382e68724b58209e8b091b8a1fa3af392534ac/results/cython-shuffle-gc-60ms-batched-send.html?raw=true)
* Performance report: [cython-shuffle-gc-120ms-batched-send.html](https://rawcdn.githack.com/gjoseph92/dask-profiling-coiled/ffe6475f6d77ea99d2578c0e0e8eaf8a77875674/results/cython-shuffle-gc-120ms-batched-send.html?raw=true)
* Performance report: [cython-shuffle-gc-500ms-batched-send.html](https://rawcdn.githack.com/gjoseph92/dask-profiling-coiled/6de1bef4624859f13f0dcb830054b81c95ed89b2/results/cython-shuffle-gc-500ms-batched-send.html?raw=true)


### GC off
##### Performance reports
* Performance report: [cython-shuffle-nogc-20ms-batched-send.html](https://rawcdn.githack.com/gjoseph92/dask-profiling-coiled/451d3fd4abb4dd55ac39f3cecd3752cf67f34c5a/results/cython-shuffle-nogc-20ms-batched-send.html?raw=true)
* Performance report: [cython-shuffle-nogc-60ms-batched-send.html](https://rawcdn.githack.com/gjoseph92/dask-profiling-coiled/1882a52734c30dbea1c84afe8760e056f40aa981/results/cython-shuffle-nogc-60ms-batched-send.html?raw=true)
* Performance report: [cython-shuffle-nogc-120ms-batched-send.html](https://rawcdn.githack.com/gjoseph92/dask-profiling-coiled/2f50a406ebb054e12e9de2baf35848bcedaa287f/results/cython-shuffle-nogc-120ms-batched-send.html?raw=true)
* Performance report: [cython-shuffle-nogc-500ms-batched-send.html](https://rawcdn.githack.com/gjoseph92/dask-profiling-coiled/a324d45034dc145edc85c3d0d2f20acce2d1e48a/results/cython-shuffle-nogc-500ms-batched-send.html?raw=true)

##### Profiles

* Speedscope profile: [cython-shuffle-nogc-20ms-batched-send.json](https://www.speedscope.app/#profileURL=https%3A%2F%2Frawcdn.githack.com%2Fgjoseph92%2Fdask-profiling-coiled%2F451d3fd4abb4dd55ac39f3cecd3752cf67f34c5a%2Fresults%2Fcython-shuffle-nogc-20ms-batched-send.json%3Fraw%3Dtrue)
* Speedscope profile: [cython-shuffle-nogc-60ms-batched-send.json](https://www.speedscope.app/#profileURL=https%3A%2F%2Frawcdn.githack.com%2Fgjoseph92%2Fdask-profiling-coiled%2F1882a52734c30dbea1c84afe8760e056f40aa981%2Fresults%2Fcython-shuffle-nogc-60ms-batched-send.json%3Fraw%3Dtrue)
* Speedscope profile: [cython-shuffle-nogc-120ms-batched-send.json](https://www.speedscope.app/#profileURL=https%3A%2F%2Frawcdn.githack.com%2Fgjoseph92%2Fdask-profiling-coiled%2F2f50a406ebb054e12e9de2baf35848bcedaa287f%2Fresults%2Fcython-shuffle-nogc-120ms-batched-send.json%3Fraw%3Dtrue)
* Speedscope profile: [cython-shuffle-nogc-500ms-batched-send.json](https://www.speedscope.app/#profileURL=https%3A%2F%2Frawcdn.githack.com%2Fgjoseph92%2Fdask-profiling-coiled%2Fa324d45034dc145edc85c3d0d2f20acce2d1e48a%2Fresults%2Fcython-shuffle-nogc-500ms-batched-send.json%3Fraw%3Dtrue)

Notice how as the batched send interval increases, `read` becomes dominated by msgpack deserialization (`unpackb`) because Tornado/SSL IO gets smaller: 

![2ms (main)](https://user-images.githubusercontent.com/3309802/121738996-41b36080-cab8-11eb-9f8e-876dfa433ec5.png)
![20ms](https://user-images.githubusercontent.com/3309802/121739004-42e48d80-cab8-11eb-8686-91a771cc5d51.png)
![60ms](https://user-images.githubusercontent.com/3309802/121739007-437d2400-cab8-11eb-8ef7-f86d995b1b6e.png)
![120ms](https://user-images.githubusercontent.com/3309802/121739009-4415ba80-cab8-11eb-9090-fb136e16a852.png)
![500ms](https://user-images.githubusercontent.com/3309802/121739014-44ae5100-cab8-11eb-9c8c-3ad79266c688.png)

**Comment by mrocklin** [comment]
Cool.  As you warned, variation in total runtime is high.  If the next coding step here is to choose a new interval (or interval range, if we're being adaptive) then we're going to want to know what min/max/default values of that range should be, which means that we might want to get more precise measurements.

FWIW, I expect us to focus more in the 2ms-20ms range than out in the 100ms range.  I could be wrong though.
