### ISSUE TITLE
Support for automatic start/stop and integration with system init scripts.

### ISSUE THREAD

**Issue by wl2776** [dask/distributed#496]
It would be useful to have a support for automatic starting/stopping/restarting of the scheduler and workers.

Particularly, modern Linux distributions use systemd, and it wants [unit files](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/sect-Managing_Services_with_systemd-Unit_Files.html). 

Such a file must contain `ExecStop` command, that stops the started process. This can be implemented with 2 methods: (1) new command line switch that would search for running process and send it interrupt signal,  or (2) obtain PID of current process on start and store it somewhere in a file, then use standard Linux `kill` command.

**Comment by mrocklin** [comment]
Ping @danielfrg @quasiben for input

**Comment by danielfrg** [comment]
Personally I not sure if distributed as a python library should support this. I don't recall having seen a python library that I can `pip install ...` and that creates unit files.

I think the reason for that is that they are sometimes system/distro dependent, redhat different than debian for example. So what end ups happening is that the pkgs (`yum install ...` or `apt-get install ...`) for those distribution do create the unit files since they are tested only for that purpose.

So I would say if the dask team is willing to maintain the pkgs on and apt for example then that would be a nice feature.

For `dask-ec2` I ended using supervisor to start the processes.

**Comment by wl2776** [comment]
I see. Then, the most universal option would be a new command line switch with the path to the PID file. The script writes its process id to that file, if the switch was specified, or behaves as usual otherwise.

**Comment by mrocklin** [comment]
Adding a `--pid-file=/path/to/pid/file` option is trivial if that is what is decided is needed.

**Comment by wl2776** [comment]
Yes, then I can write ` ExecStop=/bin/kill `/bin/cat /path/to/pid` `

**Comment by mrocklin** [comment]
Potentially fixed in https://github.com/dask/distributed/pull/497

@wl2776 does this resolve things?

@danielfrg is this a good idea?

**Comment by danielfrg** [comment]
+1 for the `--pid-file` option.

**Comment by wl2776** [comment]
yes, thanks

**Comment by mrocklin** [comment]
This has been merged.  @wl2776 please let me know how this works out for you.  If you have recommendations on doc pages that should be built around your use case (and have an interest in authoring them) then please let me know.

**Comment by wl2776** [comment]
Thanks. I'm using Anaconda and their packages, therefore, would like to wait till package update.

**Comment by mrocklin** [comment]
OK.  There will probably be a release on the conda-forge channel within a week or so.  I can't speak to when the default anaconda channel will update.

**Comment by wl2776** [comment]
Works pretty well. PID files are created. As for additions to dask/distributed doc pages, I need some more time to study systemd documentation to figure out the most right way of integration.
