### ISSUE TITLE
`client.run` can timeout while connecting to workers on large clusters

### ISSUE THREAD

**Issue by gjoseph92** [dask/distributed#5095]
During some experiments, I noticed that `client.run` on a 100-worker cluster was routinely failing with `OSError: Timed out trying to connect to tls://34.219.107.163:8786 after 10 s` from https://github.com/dask/distributed/blob/30ad02b85d0cd5ab58d8bfa2649515c668298c3c/distributed/scheduler.py#L5579

On smaller clusters (10-50 workers) with the scheduler running fewer tasks, it worked fine. Setting `DASK_DISTRIBUTED__COMM__TIMEOUTS__CONNECT=60s` (up from the default of `10s`) eliminated most (but not all) of these failures.

1. Why does `Scheduler.broadcast` use `self.rpc.connect` (potentially creating a new connection to workers) instead of using `Schduler.stream_comms`, where there should already be an open connection? Is it to avoid any latency from the `BatchedSend`?
2. Should the connection timeout scale with the number of workers in some way?

**Comment by mrocklin** [comment]
`Schduler.stream_comms` is used for the fire-and-forget BatchedSend comms, typically short messages that don't need a response like "here is a task for you to run".  `self.rpc.connect` uses a connection pool, and provides a request/reply pattern.  In the common case we'll already have an open connection and won't need to open anything.  Even if we do need to open a connection it should only take a few milliseconds.  If we did try to use the stream_comms comm we would fail because the other end already has a read open and is looking for a list of small messages to handle.

10s timeouts seem wierd to me.  At some point we should see what's going on.  My hope though is that as we clean up various other performance issues that sticky points like this start to flow more naturally.

Short term we should probably consider increasing the default timeout.  We could also consider putting the connect call in a retry_operation call.

Also, it's a bit odd that we have a separate function there and that we don't just use `self.rpc(worker).foo`.  I'm sure there is a good reason for it, but it's curious.

**Comment by fjetter** [comment]
>  Also, it's a bit odd that we have a separate function there and that we don't just use self.rpc(worker).foo. I'm sure there is a good reason for it, but it's curious.

I see two things happening:
1. The comms get a nice name
2. They are actually closed afterwards

No idea why 2) would be necessary

---

BTW I have a suspicion that the retries we have for the connect are somehow responsible for some of the problems you are observing, see https://github.com/dask/distributed/pull/5096

**Comment by mrocklin** [comment]
(1) seems like something that I or others might have done while testing/debugging something and then never cleaned up

**Comment by gjoseph92** [comment]
Turns out this wasn't a dask problem, but an issue between Coiled and how I'd set up my script.

I was waiting for clusters to fully scale up with `client.wait_for_workers(...)`. When an internal Coiled error silently prevented the cluster from scaling further, it would sit idle, since my script was waiting for these workers that would never arrive before submitting tasks. Eventually the `idle_timeout="1 hour"` set on the scheduler would kick in, shutting down the cluster. `wait_for_workers` was still waiting, so the connection closed and it tried to reconnect, which of course didn't work.
