### ISSUE TITLE
use environment-3.9.yaml for install in docs

### ISSUE THREAD

**Issue by raybellwaves** [dask/distributed#5352]
https://distributed.readthedocs.io/en/latest/develop.html#install currently points to environment-3.8.yaml should it now point to environment-3.9.yaml?

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @raybellwaves! 

> should it now point to environment-3.9.yaml?

I think we mostly care about pointing to a valid conda environment file. Since both `environment-3.8.yaml` and `environment-3.9.yaml` exist, either should be fine. We don't have a hard policy here.

Closing as the current docs are still correct, but if you want to submit a PR to bump the version, I don't think others would object
