### ISSUE TITLE
Canonical Docker Image?

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#540]
Many people create Docker images for their dask.distributed schedulers/workers when deploying with systems like Kubernetes or Mesos.  Should we publish canonical images that can be used as a reference?  

I don't know if average users appreciate this or not.  Do people who use docker generally roll their own or do they copy-paste-edit?

cc @quasiben @ogrisel @timodonnell @hussainsultan

**Comment by timodonnell** [comment]
Since installing dask distributed is pretty painless, I'm not sure it's a big win, except for maybe people learning, who could then avoid having to learn about docker for bit while they get into dask.

For production use cases I think most people will still have to make their own images since they will need their code in their image. If you publish a dask.distributed image then people would be able to build from that though.

Does dask.distributed ship with anaconda? If it does, using those [images](https://hub.docker.com/r/continuumio/) could also be an alternative then.

FWIW, in our use case we wouldn't be able to use a dask.distributed image as we need to build from the nvidia CUDA image (see our [Dockerfile](https://github.com/hammerlab/mhcflurry/blob/master/Dockerfile)). I'm not sure how many people are in similar situations.

**Comment by mrocklin** [comment]
Alright.  Closing.  Thanks for the feedback all.
