### ISSUE TITLE
KeyError in `Worker.handle_compute_task` (causes deadlock)

### ISSUE THREAD

**Issue by gjoseph92** [dask/distributed#5482]
```
Traceback (most recent call last):
  File "/opt/conda/envs/coiled/lib/python3.9/site-packages/distributed/worker.py", line 1237, in handle_scheduler
    await self.handle_stream(
  File "/opt/conda/envs/coiled/lib/python3.9/site-packages/distributed/core.py", line 564, in handle_stream
    handler(**merge(extra, msg))
  File "/opt/conda/envs/coiled/lib/python3.9/site-packages/distributed/worker.py", line 1937, in handle_compute_task
    self.tasks[key].nbytes = value
KeyError: "('slices-40d6794b777d639e9440f8f518224cfd', 2, 1)"
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
```

I may be able to reproduce this if necessary. I was running a stackstac example notebook [on binder](https://mybinder.org/v2/gh/gjoseph92/stackstac/use-binder?urlpath=lab/tree/examples/cluster.ipynb) against a Coiled cluster over `wss`, where the particular versions of things were causing a lot of errors (unrelated to dask). So I was frequently rerunning the same tasks, cancelling them, restarting the client, rerunning, etc. Perhaps this cancelling, restarting, rerunning is related?

@fjetter  says
> The only reason this keyerror can appear is if the compute instruction transitions its own dependency into a _forgotten_ state which is very, very wrong.

Relevant code, ending at the line where the error occurs: https://github.com/dask/distributed/blob/11c41b525267cc144caa8d077b84a0939fecae97/distributed/worker.py#L1852-L1937

Scheduler code producing the message which causes this error:
https://github.com/dask/distributed/blob/11c41b525267cc144caa8d077b84a0939fecae97/distributed/scheduler.py#L7953-L7994

**Comment by fjetter** [comment]
> So I was frequently rerunning the same tasks, cancelling them, restarting the client, rerunning, etc. Perhaps this cancelling, restarting, rerunning is related?

Probably. What you're describing is basically what motivated https://github.com/dask/distributed/pull/5046, see specifically https://github.com/dask/distributed/pull/5046#issuecomment-895305582 and to some extend https://github.com/dask/distributed/issues/4413#issuecomment-817820890 although the latter is a bit outdated. I'll need to update both (xref https://github.com/dask/distributed/issues/5413)

The code should be much more robust to this situation but I guess I missed an edge case. Therefore, a transition log of the deadlocked worker would be very valuable.

**Comment by fjetter** [comment]
> @fjetter says
> 
> > The only reason this keyerror can appear is if the compute instruction transitions its own dependency into a forgotten state which is very, very wrong.

Explanation below

1. Schedule ensures that `msg["who_has"].keys() == msg["nbytes"].keys()`

https://github.com/dask/distributed/blob/11c41b525267cc144caa8d077b84a0939fecae97/distributed/scheduler.py#L7977-L7980

2. Worker ensures there exists a `TaskState` in `Worker.tasks` for every key in `who_has`

https://github.com/dask/distributed/blob/76495965cf8d3fb5f54bb4b8d20279ae402e0957/distributed/worker.py#L1907-L1916

3. We perform a bunch of transitions. This is the only place where can actually drop another task again.

https://github.com/dask/distributed/blob/76495965cf8d3fb5f54bb4b8d20279ae402e0957/distributed/worker.py#L1937

4. This is where the KeyError is raised.

https://github.com/dask/distributed/blob/76495965cf8d3fb5f54bb4b8d20279ae402e0957/distributed/worker.py#L1943-L1944


Since 1.) ensures `nbytes.keys() == who_has.keys()` and 2.) ensure there exists a task for all keys in who_has, therefore it ensures there is a task for every key in nbytes, 3. is the only way we could drop/forget a key since 4. is still in the same synchronous block.

The transition logic for that broken key could be either of

A) released -> waiting -> ready -> executing -> cancelled(executing)
B) released -> fetch -> flight -> cancelled(flight)

Above 2.) should then be a no-op 3.) should then trigger a 

A) `cancelled->fetch` transitions to `flight`
B) `cancelled->fetch` transitions to `resumed(flight)`. This one triggers a `release_key` and is as far as I can see the only source which could generate a `forgotten` recommendation.

I _think_ this is some not well covered edge case in https://github.com/dask/distributed/blame/76495965cf8d3fb5f54bb4b8d20279ae402e0957/distributed/worker.py#L2965-L2966

**Comment by bennnym** [comment]
At the request of @gjoseph92  I am posting my transition logs as a result of a deadlock:

[log.txt](https://github.com/dask/distributed/files/7470870/log.txt)

**Comment by gjoseph92** [comment]
^ For background @bennnym ran into this same `KeyError`:
```
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO - Run out-of-band function 'lambda'
distributed.worker - ERROR - "('split-shuffle-1-80cde6aa3e7938b28ad0dfe2387b063e', 5, (2, 3))"
Traceback (most recent call last):
  File "/opt/conda/envs/coiled/lib/python3.8/site-packages/distributed/worker.py", line 1237, in handle_scheduler
    await self.handle_stream(
  File "/opt/conda/envs/coiled/lib/python3.8/site-packages/distributed/core.py", line 564, in handle_stream
    handler(**merge(extra, msg))
  File "/opt/conda/envs/coiled/lib/python3.8/site-packages/distributed/worker.py", line 1937, in handle_compute_task
    self.tasks[key].nbytes = value
KeyError: "('split-shuffle-1-80cde6aa3e7938b28ad0dfe2387b063e', 5, (2, 3))"
distributed.worker - INFO - Connection to scheduler broken.  Reconnecting...
```
This error then caused a deadlock (https://github.com/dask/distributed/issues/5480). We confirmed it was also due to https://github.com/dask/distributed/issues/5481 by checking for queued messages in the worker's `batched_stream`:
```
>>> client.run(
...     lambda dask_worker: (
...         len(dask_worker.batched_stream.buffer),
...         dask_worker.batched_stream.please_stop
...     )
... )
{'tls://10.12.16.108:35519': (0, False),
 'tls://10.12.16.88:42647': (0, False),
 'tls://10.12.18.155:41501': (0, False),
 'tls://10.12.19.84:40143': (0, False),
 'tls://10.12.20.221:40545': (0, False),
 'tls://10.12.21.210:45285': (0, False),
 'tls://10.12.21.217:35583': (0, False),
 'tls://10.12.21.39:43355': (0, False),
 'tls://10.12.23.137:44833': (0, False),
 'tls://10.12.23.225:36857': (0, False),
 'tls://10.12.23.48:36147': (620, True),  <-- this one has enqueued messages and a stopped `_background_send` coroutine
 'tls://10.12.24.247:42369': (0, False),
 'tls://10.12.26.157:42411': (0, False),
 'tls://10.12.27.196:44821': (0, False),
 'tls://10.12.27.70:40899': (0, False),
 'tls://10.12.28.196:32955': (0, False),
 'tls://10.12.29.12:40313': (0, False),
 'tls://10.12.30.116:45129': (0, False),
 'tls://10.12.30.157:34201': (0, False),
 'tls://10.12.31.58:36025': (0, False)}
```

So we then got transition logs for the key in question, which Ben has attached above.

@bennnym I forgot, could you also post the output of `client.get_versions`?

**Comment by bennnym** [comment]
@gjoseph92  my code was running in a notebook and my kernell died, sorry. That is all I have

**Comment by gjoseph92** [comment]
Do you know offhand what versions of dask and distributed you were running? It may show in your Coiled software environment.

**Comment by bennnym** [comment]
I was just installing `dask[distributed]` so I assume the latest version
