### ISSUE TITLE
`Worker.log_event` is not threadsafe / `BatchedSend.send` not threadsafe

### ISSUE THREAD

**Issue by gjoseph92** [dask/distributed#5552]
**What happened**:

Calling `get_worker().log_event(...)` from multiple worker threads can fail (or probably corrupt the BatchedSend), since `BatchedSend.send` is not thread-safe.

I saw a traceback like
```python-tracebak
/opt/conda/envs/coiled/lib/python3.8/site-packages/distributed/worker.py in log_event()

/opt/conda/envs/coiled/lib/python3.8/site-packages/distributed/batched.py in send()

/opt/conda/envs/coiled/lib/python3.8/site-packages/tornado/locks.py in set()

RuntimeError: Set changed size during iteration
```

This is probably coming from the `_background_send` coroutine calling `wait` on the tornado Event (adding to its `_waiters` set) while the `send` call in a worker thread calls `set` (iterating over the `_waiters` set).

**What you expected to happen**:

Users don't have to manage thread-safety of this API; it locks automatically.

**Anything else we need to know?**:

This is certainly a rarely-used API, but it is advertised in the docs: http://distributed.dask.org/en/stable/logging.html#structured-logs.

Easy to fix (`sync`?), though not a high priority, just wanted to note it for posterity.

**Environment**:

- Dask version: 2021.11.2
- Python version: 3.8.7
- Operating System: linux
- Install method (conda, pip, source): pip

**Comment by fjetter** [comment]
I'm wondering what the worst case of a non-thread safe interaction would be. As the post points out, this can raise a RuntimeError whenever a send is called. That typically happens after a message has been queued up in the buffer so the worst case for a *single message* submit would be that a message submission is delayed until the next wake. No big deal

However, all patterns that send many messages subsequently would be at risk of dropping a message

```python
for msg in msgs:
    batched.send(msg)
```

I'm further wondering if this race condition could not corrupt the `tornado.Event` itself, such that the `BatchedSend._background_send` might deadlock since actions on futures (under the hood) are also not thread safe and might leave the critical future in a corrupt state

---

Today, we investigated this topic briefly around a spurious connection failure but I don't think any of this could actually corrupt the connection itself.
