### ISSUE TITLE
dask security: The TLS protocol version can be selected.

### ISSUE THREAD

**Issue by leo038** [dask/distributed#5553]
TLS 1.0 and TLS 1.1 have proven to be insecure and are gradually being discarded. When users have higher security requirements, TLS1.2 and later versions are preferred. However, the TLS version cannot be specified currently. As a result, earlier versions are supported, causing security risks.
According to my practice, you only need to modify the following code to specify the version:
change the file   of `security.py`:
change 
```python
 ctx = ssl.create_default_context(purpose=purpose, cafile=ca)
```
to 
```python
ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
ctx.verify_mode = ssl.CERT_REQUIRED
ctx.load_verify_locations(ca)
```
`ssl.PROTOCOL_TLSv1_2` can be an input parameter， so the user can select another version.  Since `dask-scheduler` and `dask -worker` already have the `--protocol` parameter, I think it's convenient to extend this parameter directly.

However, we cannot directly modify the dask source code, so we hope dask provides official support.

**Comment by jcrist** [comment]
Thanks for raising this issue, should be fixed by #5594. Note that the syntax you've used above is deprecated in Python, you should rely on setting `minimum_version`/`maximum_version` on the ssl context.

In #5594 we also move to requiring TLS 1.2+, so for your specific issue no further config should be necessary once that's merged in.
