### ISSUE TITLE
progress doesn't work in ipython qtconsole

### ISSUE THREAD

**Issue by dhirschfeld** [dask/distributed#558]
It appears the progress function thinks it's in the ipython notebook:
```python
In [24]: from distributed import progress

In [25]: futures = executor.compute(list(map(etl, periods)))

In [26]: futures[-2:]
Out[26]: 
[<Future: status: pending, key: finalize-18c25ce7508afc33e4fdafa4436597c3>,
 <Future: status: pending, key: finalize-f297a3a15f4e0d0e790b9a485ff2f8b2>]

In [27]: progress(*futures)
Widget Javascript not detected.  It may not be installed properly. Did you enable the widgetsnbextension? If not, then run "jupyter nbextension enable --py --sys-prefix widgetsnbextension"
```
System info:
```
In [28]: import distributed

In [29]: distributed.__version__
Out[29]: '1.13.2'

In [30]: from IPython import sys_info

In [31]: print(sys_info())
{'commit_hash': '5c9c918',
 'commit_source': 'installation',
 'default_encoding': 'cp1252',
 'ipython_path': 'C:\\Python\\lib\\site-packages\\IPython',
 'ipython_version': '5.1.0',
 'os_name': 'nt',
 'platform': 'Windows-7-6.1.7601-SP1',
 'sys_executable': 'C:\\Python\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, '
                '11:41:13) [MSC v.1900 64 bit (AMD64)]'}
```

**Comment by dhirschfeld** [comment]
I originally ran it in spyder but have also tested in the plain qtconsole with the same result.

**Comment by dhirschfeld** [comment]
**Repro:**
```python
from distributed import Client, progress

def double(x):
    return 2*x

client = Client()
futures = client.map(double, np.arange(1e3))
```
```
In [9]: progress(*futures)
Widget Javascript not detected.  It may not be installed properly. Did you enable the widgetsnbextension? If not, then run "jupyter nbextension enable --py --sys-prefix widgetsnbextension"
```

**Comment by dhirschfeld** [comment]
Interestingly, it *does* work in the terminal ipython.

**Comment by danielballan** [comment]
It looks like `progress` infers whether it is running in a notebook by checking whether the Python process is a kernel [here](https://github.com/dask/distributed/blob/f777f4c0d0675c1a44931ac8ffeb59301eea5c6b/distributed/diagnostics/progressbar.py#L316). It works in terminal IPython because terminal IPython runs as a single process (no kernel). The console and notebook separate the computation into a separate process, the kernel.

By design, the kernel is not aware whether it is talking to a notebook or a console. (It might be talking to more than one.) To make the progress bar chose the desired behavior, it looks like the `notebook` arg supercedes the "assume-notebook-if-this-is-a-kernel" heuristic.

**Comment by dhirschfeld** [comment]
Right, says so right there in the docstring. Sorry for wasting everyone's time...
```python
In [22]: progress(*futs, notebook=False)
[########################################] | 100% Completed |  0.0s
```
Works fine.

**Comment by mrocklin** [comment]
I've actually been swamped with conference things this week and so didn't get a chance to review this until now.  Always happy to come to an issue and see "Closed" at the end :)

@danielballan do you see any way we can help QtConsol users avoid this speedbump in the future?

**Comment by danielballan** [comment]
I've encountered this problem before, and I don't see any way to do this without breaking the abstraction that kernels aren't supposed to know what front-end(s) they are talking to. Of course, the JupyterLab Console will work with the JS progress bar just fine, so that would be the way to get the console workflow and the nice progress bar.
