### ISSUE TITLE
Unclear user feedback in case Client-Scheduler connection breaks up

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#5666]
# Description

In case of a disconnect between Client and Scheduler, the logging messages are not very helpful for the typical user and do not help debugging the issue but rather cause more confusion. The feedback is sometimes delayed (only triggered after a timeout), causation is not transparent or log messages are missing or on a wrong level.

A) CancelledError confusing

The below code raises a `CancelledError` after a timeout of 30s. This is typically a cryptic exception most users cannot relate to. If a `persist` is in the chain of commands, the timeout is not even logged but only a `CancelledError` is raised such that the disconnect is entirely obfuscated.

Instead of a `CancelledError`, I would expect a more user friendly exception telling the user about the non-running status of the client which is likely caused by a disconnect with the scheduler.

<details>
<summary>CancelledError after timeout</summary>

```python
import dask.array as da
import distributed

with distributed.LocalCluster(n_workers=1) as cluster:
    client = distributed.Client(cluster)
x = da.ones(10, chunks=5)
x.compute()
```

Causes

```
distributed.client - ERROR - Failed to reconnect to scheduler after 30.00 seconds, closing client
_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=CancelledError()>
asyncio.exceptions.CancelledError
distributed.client - ERROR - Failed to reconnect to scheduler after 30.00 seconds, closing client
_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=CancelledError()>
asyncio.exceptions.CancelledError
```

</details>

<details>
<summary>CancelledError with persist</summary>

```python
import dask.array as da
import distributed

with distributed.LocalCluster(n_workers=1) as cluster:
    client = distributed.Client(cluster)
    x = x.persist()
y = x.sum()
y.compute()
```

</details>

B) Client reconnecting to (new) scheduler

In a case a reconnect finishes successfully, this can go entirely unnoticed

```python
import dask.array as da
import distributed

with distributed.LocalCluster(n_workers=1, scheduler_port=5678) as cluster:
    client = distributed.Client(cluster)
    x = da.ones(10, chunks=5).persist()

# New cluster, same address
cluster = distributed.LocalCluster(n_workers=1, scheduler_port=5678)
assert client.status == "running"

x.sum().compute()  # Boom
```

![image](https://user-images.githubusercontent.com/8629629/149959547-464a5c36-6eaf-47c3-9cd6-89f753f2f3be.png)

# Expected behaviour

* Clear logging mentioning that a scheduler<->Client disconnect happened with a sufficient log level that it is not dropped in common applications (e.g. jupyter lab / default config)
* Clear exception messages indicating what's wrong and where to look
* Both persist and compute calls provide a clear message

Note:
When only using persist, the log only appears after a timeout of 30s (after giving up on the reconnect)

**Comment by davidkell** [comment]
Hey @fjetter and @hayesgb, taking a look at this one. It’s something I’ve experienced first hand when running dask on GKE, eg when nodes are pre-empted or we force a re-deploy.

### Why it happens

When a client attempts to re-connect to the scheduler, all futures are cancelled and removed from the `client.futures` dict. 

If the client later attempts to work with these futures, as defined elsewhere, it cannot find them in `client.futures` and the default strategy in the codebase is to throw `CancelledError` without future information.

Interestingly, this can happen in different parts of the codebase. At least when running locally, for the two examples above, I saw an error in:
- cancelled after timeout: `distributed.client.Client._gather`
- cancelled after persist: `dash.highlevelgraph.Layer.__dask_distributed_pack__`

In both cases, the root cause is that the future does not exist in `client.futures`.

### Short term proposal

If a future is missing in `client.futures`, what can we infer? Reading through the code, I see typically three reasons:
1. It was created by another client. This is handled by a separate exception so we can ignore it.
2. It is no longer referenced (i.e. reference count is 0). If that's the case, by definition it shouldn't be possible for the client to be requested that future. (Well, unless you pathologically deleted a future, and reconstructed a new one with the same key and client.)
3. The client attempted to reconnect.

So in the majority of cases where we see this happen, it's a reasonable inference that client reconnecting is the reason.

As a solution, we can add logic to check for the presence of a future in `client.futures` when it is requested. If it's not there, we'd log to the user with an optional exception, explaining to them that, most likely, this happened because their client reconnected.

### Longer term solution?

Having said that, it feels like a band-aid fix, rather than tackling the root cause. `client.futures` is referenced in a wide number of places in both `distributed` and `dask`, and as noted above, where the error happens can vary.

I completely agree with @fjetter in #5667 that adding logic for reconnecting (without wiping `client.futures`) on short network disconnects would be a big win. Building on that insight, I would say that the long term goal is to only allow two possible states:
- the client is trying to reconnect, and the future exists
- the client is closed, and the future is deleted
This means we can always be sure that `client.futures` has the keys we expect (unless the user/another library starts messing around with it).

If we did that, my suggested fix wouldn't be required anymore. For example, taking the @fjetter "cancelled after timeout" example, the behaviour you'd get is:
- client hangs for 30 seconds trying to reconnect (perhaps with logging)
- client closes and fails

I think that would be pretty clear feedback for the user, and we get this "for free" without having to add checks all over the place.

Of course, #5667 is a much bigger piece of work - so perhaps the right strategy is the short term solution at a few key points (as a quick UX win), while working on the long term solution that eventually supersedes this. Thoughts?

**Comment by fjetter** [comment]
closed by https://github.com/dask/distributed/pull/8705

xref https://github.com/dask/distributed/issues/8690
