### ISSUE TITLE
More KilledWorkers since dask upgrade from 2.18.1 to latest

### ISSUE THREAD

**Issue by NickSchouten** [dask/distributed#5734]
Hi all, 

First of all thanks for taking the time to read this.

We recently upgraded our dask base image from dask Version: 2.18.1 to latest.
For most of our long running jobs this went fine, but for about 10% the upgrade causes the jobs to crash with `KilledWorker` exceptions. On the old image we would chuck this up to bad memory usage, but the same job is able to run to completion on the old dask version.

I cannot provide you with a reproducible snippet for this, but can show you a GIF of the dashboard following the memory usage. 

![Screen Recording 2022-01-28 at 11 47 04](https://user-images.githubusercontent.com/11192820/151765379-13840c7c-348e-40af-8dea-cadd2ee3ae27.gif)
_Notice the orange bars surging to full memory and then re-appearing as an empty worker_

What we find strange is how (recent) unmanaged memory spikes seem to be the cause of these tasks being killed. 
You can see this in the video, where all is running fine until suddenly one worker reserves (presumably) a lot of memory which leads to it being killed.
The same job on the old image would not have these surges, but also did not yet have the distinction between unmanaged and managed memory.

Lastly, we tried setting distributed.memory.target to 0.2 and spill to 0.3. This got some jobs to run to completion. The workers would all stay lower on memory. The surges still happened, but they could now fit in memory.

If anybody has any ideas as to why this is happening with regards to the version upgrade, that would be greatly appreciated.

Thanks in Advance,
Nick

**Comment by fjetter** [comment]
Hi @NickSchouten,

Thanks for your report. Memory issues are a very frequent problem and we're doing our best to get ahead of them and make it easier to debug. The spike in unmanaged memory is one of them and a hint one can investigate. However, this can still mean a bunch of things.

Your particular problems is hard to diagnose with the information you provided. Particularly, since you're upgrading from 2.18.1 which is almost two years old now.

One idea I have to triage this is to check if the graphs you are calculating are the same size. There are two easy ways to do this. The first one is the dashboard where it shows `total: XYZ` next to the progress bars and the other is by inspecting the dask dataframe *before* you hit compute, i.e. `len(ddf.dask)`. If these numbers diverge significantly, this may be a hint we can follow up on.

I would also recommend checking if any other libraries increased in your upgrade which might be relevant for this, e.g. numpy or pandas.

**Comment by NickSchouten** [comment]
Hi @fjetter,

Thanks for the reply:

len(ddf.dask) returns 521.
With a dashboard progress screenshot: 
![Screenshot 2022-02-01 at 11 10 28](https://user-images.githubusercontent.com/11192820/151949956-ac904162-d60e-4f68-88f7-7da943bfc5b2.png)
_I'm not quite sure with which number you want me to compare_

We did indeed also upgrade a lot of other libraries among which:
Numpy: 1.19.5 => 1.20.3
Pandas: 1.0.1 => 1.3.5
Dask-kubernetes: 0.10.0 => 2021.10.0
