### ISSUE TITLE
Drop setuptools runtime dependency?

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#5949]
- Follow-up from https://github.com/dask/distributed/pull/5923

Now that we no longer use pkg_resources, can we drop the run-time dependency from setuptools altogether?

I see it used:
- in setup.py (which is not runtime)
- in versioneer.py, with a fallback to distutils if it's not already loaded. Unsure about the implications of this.
- in a single test (``test_upload_file_egg``) which could have ``pytest.importorskip``

Notably, setuptools is already not in requirements.txt. However, I can see it in the conda recipe:
```yaml
run:
    [...]
    - setuptools <60.0.0
```
Not sure why? xref #5802 where it was added.

CC @graingert @charlesbluca

**Comment by jsignell** [comment]
setuptools was already in the conda-forge recipe I just set a ceiling for it in https://github.com/conda-forge/distributed-feedstock/pull/194 it would not surprise me if we don't in fact need it in the feedstock.

**Comment by jakirkham** [comment]
Right I think this was due to the `pkg_resources` as @crusaderky points out. If we no longer need `pkg_resources`, then yes we should be able to drop `setuptools` as a dependency.

As to the version constraint on `setuptools`, there were a bunch of changes in `60.0.0`, which broke various packages (`distributed` being one). So it was constrained. Again shouldn't be relevant if we are no longer using `pkg_resources`.

As to the egg case, I thought the optional [`PipInstall`]( https://github.com/dask/distributed/blob/85bf1beb48085b042210ae8cc7e5c5e90289ba37/distributed/diagnostics/plugin.py#L212 ) `WorkerPlugin` superseded that, but maybe I'm missing something there.

Anyways +1 on dropping `setuptools`

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/dask/distributed/pull/5963 )

**Comment by jsignell** [comment]
I didn't change the distributed-feedstock, but I am happy to in the next release.
