### ISSUE TITLE
Remove tornado loop kwarg in Server

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#6051]
Our Server classes and Server subclasses are currently accepting a tornado IOLoop as an argument. When removing the tornado IOLoop from the code base, we'll need to introduce appropriate replacements

- Server likely doesn't need a kwarg. It is always async, we can just use `asyncio.get_running_loop`
- Client, Cluster, Scheduler, etc. might want to use a `LoopRunner` instance or a token instead

**Comment by graingert** [comment]
yes this ticket is mostly completed by

https://github.com/dask/distributed/pull/6473
https://github.com/dask/distributed/pull/6443

when working on https://github.com/dask/distributed/issues/6163 I discovered that passing a non-current `loop` to Scheduler, Server, Worker or Nanny was already broken and so could be deprecated without any disruption.

howerver, the Client and Cluster (and any other SyncMethodMixin) classes, still require a either a running loop or `None` so that they can determine if they are being run from a synchronous or asynchronous 'perspective'

**Comment by fjetter** [comment]
Great, I'll close this then as a duplicate
