### ISSUE TITLE
Work stealing cpu load with high numbers of tasks

### ISSUE THREAD

**Issue by mrocklin** [dask/distributed#6178]
I was speaking with @bnaul .  He mentioned that he noticed the scheduler at 100% CPU usage when it should have been in a somewhat quiet state.  He had on the order of 100,000 tasks and it was spending all of its time in work stealing, in particular the maybe_move_task function.  Something there may not be O(1).

![image](https://user-images.githubusercontent.com/306380/164762718-8317cd5b-fe6f-4a83-bb83-bd203e8e3978.png)

![image (1)](https://user-images.githubusercontent.com/306380/164762720-02ced04c-dd3f-4023-ad02-ad6aa08b8b9c.png)

**Comment by fjetter** [comment]
I can't see anything that's not O(1) at first glance. We changed one thing about `move_task_request` recently that slows it down but is constant time. We introduced a UUID generation in there

https://github.com/dask/distributed/blame/main/distributed/stealing.py#L221-L223

Note: this is the *only* place where we're abusing the stimulus_id for anything functional

- https://github.com/dask/distributed/pull/5379 (this was the deadlock)
- https://github.com/dask/distributed/pull/5620 (here we introduced the UUID since the simple time caused duplicates)

I opened https://github.com/dask/distributed/pull/6179 to remove the UUID

**Comment by mrocklin** [comment]
I think that we should just remember to run a larger workload and track
profiling here.  It also might be O(1) in number of tasks, but O(n) in
number of workers, for example.

**Comment by gjoseph92** [comment]
If there's a reproducible workload, `pyspy_on_scheduler` could easily give a definitive answer to the question.

https://github.com/gjoseph92/scheduler-profilers
