### ISSUE TITLE
Design and prototype for root-ish task deprioritization by withholding tasks on the scheduler

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#6560]
Root task overproduction is a significant problem for memory pressure and runtime

https://github.com/dask/distributed/issues/6360 has shown that we can find a way to deal with the problem isolated in the scheduler (e.g. w/out full STA) by limiting the number of tasks assigned to the worker at a given time

Implementing this logic might have significant impact on our scheduling policies and we want to review the design and implementation thoroughly and perform necessary performance benchmark before committing to it

## Expectations

- A draft PR is created that implements a version of the in https://github.com/dask/distributed/issues/6360 proposed algorithm  that **does not** preserve root-task co-assignment
- (Best effort) A draft PR is created that implements a version of the in https://github.com/dask/distributed/issues/6360 proposed algorithm  that **does** preserve root-task co-assignment
- The algorithm should be able to run on large graphs
- Implementation can be tested by OSS users (e.g. pangeo) 
- There is consensus about how to withhold tasks on the scheduler by Friday June 24th, 2022
- PRs are only merged iff there are thorough performance benchmarks available confirming this works for non-root-task cases as well, e.g. traditional shuffle, map overlap, other-evil-graph-problem

## Out of scope / Follow up
- Thorough performance benchmarks exist (as part of coiled-runtime)

**Comment by crusaderky** [comment]
> There is consensus about how to withhold tasks on the scheduler by Friday 24th, 2022

@fjetter missing the month

**Comment by gjoseph92** [comment]
We now have draft PRs for:
* https://github.com/dask/distributed/pull/6614
* _One possible implementation_ of https://github.com/dask/distributed/pull/6598

Obviously, ignoring co-assignment makes the implementation much simpler.

The key question is going to be, how important is co-assignment? I imagine we'll want it eventually. But perhaps fixing root task overproduction is such a big win that workloads that currently only succeed thanks to co-assignment will still succeed under a naive root-task-withholding implementation that doesn't co-assign. (Some example workloads to try in https://github.com/dask/distributed/issues/2602#issuecomment-870930134.)

So I think the next step is to do some basic benchmarking between these two PRs (and `main`) and see how much of a marginal benefit we get from co-assignment + fixing overproduction vs just fixing overproduction. (Even if https://github.com/dask/distributed/pull/6598 is not the implementation we'd want to merge, it still should work well enough to test this.)

That's what I plan to do today.

**Comment by gjoseph92** [comment]
If it turns out co-assignment isn't that important, then we can just focus on https://github.com/dask/distributed/pull/6614, and possibly merging it soon under a feature flag (there are still a couple bugs to fix).

If it turns out co-assignment is still critical for some workloads, or offers a huge performance/memory gain, then that means that we probably have to accept some complexity if we are going to withhold tasks at all.

Aside: the question of "maybe we shouldn't withhold tasks then, maybe we should just do STA" has come up. IMO we're probably going to want root task withholding even with STA. Or at least, I don't think we have nearly enough understanding of what the STA heuristics would be to confidently say we _won't_ need root task withholding with STA. One big question with STA will be how to steal/rebalance tasks when workers join/leave. Stealing is already problematic enough on just runnable tasks (https://github.com/dask/distributed/issues/6600). The idea of having nearly every task pre-assigned to a worker and needing rebalance them all while maintaining consistency seems daunting. A great way to limit the complexity of rebalancing under STA would be to withhold root tasks, which brings the number of tasks workers actually know about and need to be rebalanced down from O(n_tasks) to O(n_threads), which is probably a 10-100x reduction.

So that's one reason why I don't think withholding root tasks (as an overall approach) is necessarily a stopgap we'd throw out during a major scheduling overhaul like STA.

Therefore, if benchmarking shows that co-assignment is critical, then we should think about _where_ we'd be willing to accept the complexity (in a task-batch-identifying algorithm, or in a load-rebalancing algorithm).

If it isn't critical, then we should get task withholding merged without it, and think about co-assignment as another incremental change sometime in the future.

**Comment by gjoseph92** [comment]
## Benchmarking results

I ran #6614 and #6598 on a few representative workloads.

**I don't think co-assignment has enough of a _memory_ benefit for it to be an immediate requirement.**

Adding co-assignment to root-task withholding seems to somewhat reduce runtimes, but confusingly, tends to somewhat _increase_ memory usage. (That's such an odd result, it makes a a little skeptical of my implementation of https://github.com/dask/distributed/pull/6598, but I've tested it and it seems to be correct?)

Across the board, withholding root tasks improves memory usage, often significantly (5x-100x), though occasionally it's the same. It sometimes decreases runtime, and sometimes increases it, by significant factors (up to 2x) both ways.

Bottom line: fixing root task overproduction seems to make workloads feasible that are not feasible today (without absurd memory requirements). Removing co-assignment does not seem to make anything _infeasible_ that works today—just maybe slower.

-----

### `anom-mean`
* @rabernat's classic example from https://github.com/dask/distributed/issues/2602#issuecomment-498718651
* Ryan wanted dask to "stop generating new data before the downstream data could be consumed". Since that's exactly what this fixes, it's good to see it has such a significant effect on memory (at the cost of runtime)

![anom-mean-combined](https://user-images.githubusercontent.com/3309802/175465002-73c714d9-9cb0-4657-af31-4196e040a43b.png)

<details>

```python
import xarray as xr
import dask.array as da
from dask.utils import format_bytes
import numpy as np
import sneks

# From https://github.com/dask/distributed/issues/2602#issuecomment-498718651

from run_trial import run

if __name__ == "__main__":
    data = da.random.random((10000, 1000000), chunks=(1, 1000000))
    arr = xr.DataArray(
        data, dims=["time", "x"], coords={"day": ("time", np.arange(10000) % 100)}
    )
    print(
        f"{format_bytes(data.nbytes)} - {data.npartitions} {format_bytes(data.blocks[0, 0].nbytes)} chunks"
    )
    # 74.51 GiB - 10000 7.63 MiB chunks

    clim = arr.groupby("day").mean(dim="time")
    anom = arr.groupby("day") - clim
    anom_mean = anom.mean(dim="time")

    client = sneks.get_client(
        name="anom-mean",
        n_workers=20,
        worker_vm_types=["r5a.large"],  # 2 CPU, 16GiB
        environ={"MALLOC_TRIM_THRESHOLD_": 0},
        wait_for_workers=True,
    )
    print(client.dashboard_link)

    run(anom_mean, __file__)
```

</details>

### `basic-sum`
* @JSKenyon's example from https://github.com/dask/distributed/pull/4864
* Originally motivated implementing the co-assignment logic

![basic-sum-combined](https://user-images.githubusercontent.com/3309802/175465219-3d50f14a-5e8d-4990-9fc5-e7567bf2eafa.png)

<details>

```python
import dask.array as da
from dask.utils import format_bytes
import sneks

# From https://github.com/dask/distributed/pull/4864

from run_trial import run

if __name__ == "__main__":
    data = da.zeros((12500000, 5000), chunks=(12500000, 1))
    print(
        f"{format_bytes(data.nbytes)} - {data.npartitions} {format_bytes(data.blocks[0, 0].nbytes)} chunks"
    )
    # 465.66 GiB - 5000 95.37 MiB chunks

    result = da.sum(data, axis=1)

    client = sneks.get_client(
        name="basic-sum",
        n_workers=4,
        worker_vm_types=["t3.xlarge"],  # 4 CPU, 16GiB
        environ={"MALLOC_TRIM_THRESHOLD_": 0},
        wait_for_workers=True,
    )
    print(client.dashboard_link)

    run(result, __file__)
```

</details>

### `climactic-mean`
* @dougiesquire's example from https://github.com/dask/distributed/issues/2602#issuecomment-535009454
* One of the "success stories" of co-assignment

![climactic-mean-combined](https://user-images.githubusercontent.com/3309802/175465668-519e14d1-c45d-4813-a6ce-8eefd8abd5ec.png)

<details>

```python
import xarray as xr
import dask.array as da
from dask.utils import format_bytes
import numpy as np
import pandas as pd
import sneks

# https://github.com/dask/distributed/issues/2602#issuecomment-535009454

from run_trial import run

if __name__ == "__main__":
    size = (28, 237, 96, 21, 90, 144)
    chunks = (1, 1, 96, 21, 90, 144)
    arr = da.random.random(size, chunks=chunks)
    print(
        f"{format_bytes(arr.nbytes)} - {arr.npartitions} {format_bytes(arr.blocks[(0,) * arr.ndim].nbytes)} chunks"
    )
    # 1.26 TiB - 6636 199.34 MiB chunks

    items = dict(
        ensemble=np.arange(size[0]),
        init_date=pd.date_range(start="1960", periods=size[1]),
        lat=np.arange(size[2]).astype(float),
        lead_time=np.arange(size[3]),
        level=np.arange(size[4]).astype(float),
        lon=np.arange(size[5]).astype(float),
    )
    dims, coords = zip(*list(items.items()))

    array = xr.DataArray(arr, coords=coords, dims=dims)
    arr_clim = array.groupby("init_date.month").mean(dim="init_date")

    client = sneks.get_client(
        name="climactic-mean",
        n_workers=20,
        worker_vm_types=["r6i.xlarge"],  # 4 CPU, 32 GiB
        environ={"MALLOC_TRIM_THRESHOLD_": 0},
        wait_for_workers=True,
    )
    print(client.dashboard_link)

    run(arr_clim, __file__)
```

</details>

### `jobqueue`
* Just submitting 10,000 independent CPU-bound tasks (simulating usage of dask for embarrassingly-parallel jobs)
* Should be a case where root task overproduction helps / doesn't matter, since workers just need to crank through tasks as fast at they can
* Removing root task overproduction only added a 1% slowdown
* Notice the y-axis values; all that matters here is runtime
![jobqueue-combined](https://user-images.githubusercontent.com/3309802/175466452-f6ab73a8-0afb-48b1-8acc-24977e63fad8.png)

<details>

```python
from dask import delayed
from dask.utils import parse_bytes
import time
import random
import sneks


from run_trial import run

if __name__ == "__main__":

    @delayed(pure=True)
    def task(i: int) -> int:
        stuff = "x" * parse_bytes("400MiB")
        time.sleep(random.uniform(0, 3))
        return i

    tasks = [task(i) for i in range(10_000)]
    result = delayed(sum)(*tasks)  # just so we have a single object

    client = sneks.get_client(
        name="jobqueue",
        n_workers=20,
        worker_vm_types=["c6a.xlarge"],  # 4 CPU, 8GB
        environ={"MALLOC_TRIM_THRESHOLD_": 0},
        wait_for_workers=True,
    )
    print(client.dashboard_link)

    run(result, __file__)
```

</details>

### `shuffle-enrich`
* (task-based) shuffle a 160GB DataFrame, aggregate it, subtract the aggregated value from a second 80GB DataFrame
* Task-based shuffle is another case we wouldn't expect to benefit from fixing root task overproduction
* I don't quite understand how fixing overproduction enormously reduced both memory usage and runtime? @mrocklin this seems like an important result?

![shuffle-enrich-combined](https://user-images.githubusercontent.com/3309802/175467207-b60e078c-a009-4b62-829c-b982c903590d.png)

<details>

```python
import dask
from dask.utils import format_bytes
from dask.sizeof import sizeof
import sneks


from run_trial import run

if __name__ == "__main__":
    df = dask.datasets.timeseries(
        start="2020-01-01",
        end="2024-01-01",
        freq="600ms",
        partition_freq="12h",
        dtypes={i: float for i in range(100)},
    )

    p = df.partitions[0].compute(scheduler="threads")
    partition_size = sizeof(p)
    total_size = partition_size * df.npartitions
    print(
        f"~{len(p) * df.npartitions:,} rows x {len(df.columns)} columns, "
        f"{format_bytes(total_size)} total, "
        f"{df.npartitions:,} {format_bytes(partition_size)} partitions"
    )
    # ~210,384,000 rows x 100 columns, 158.32 GiB total, 2,922 55.48 MiB partitions

    shuf = df.shuffle(0)
    counts = shuf.map_partitions(lambda df: df.value_counts())
    res = counts.mean()

    df2 = dask.datasets.timeseries(
        start="2010-01-01",
        end="2012-01-01",
        freq="600ms",
        partition_freq="12h",
        dtypes={i: float for i in range(100)},
    )

    final = (df2 - df).mean()

    client = sneks.get_client(
        name="shuffle",
        n_workers=20,
        worker_vm_types=["t3.xlarge"],  # 4 CPU, 16 GiB
        environ={"MALLOC_TRIM_THRESHOLD_": 0},
        wait_for_workers=True,
    )
    print(client.dashboard_link)

    run(final, __file__)
```

</details>

## `vorticity`
* @TomNicholas's example from https://github.com/dask/distributed/issues/6571
* I think something else is going on here

![vorticity-combined](https://user-images.githubusercontent.com/3309802/175469032-2305ba6a-def6-4641-bc86-4772376a47cf.png)

**Comment by JSKenyon** [comment]
Thanks @gjoseph92 - those are some really interesting results! I definitely think that the improvements in memory footprint are compelling. That said, I would be really interested to see these benchmarks for different (mainly larger) numbers of workers. I haven't looked at any of the implementation in detail, but it would be good to show that these improvements are approximately independent of `n_workers`. I agree that co-assignment doesn't have a large impact on memory footprint, but it is interesting how much of a difference it can make to run times. Again, this would be really interesting to look at as a function of `n_workers`. Thanks again to everyone who is working on this problem!

**Comment by fjetter** [comment]
Great benchmark results @gjoseph92 ! I agree with @JSKenyon that we will want a couple more benchmarks to confirm these results and we'll likely need to iterate on the implementation and review it more thorouhgly.

I opened a follow up ticket to pursue the implementation **without co-assignment** (see ticket for some explanation why)

- https://github.com/dask/distributed/issues/6631

Instead of doing more manual benchmarking I would rather like us to put this into an automated benchmarks, see (using [Coiled](https://coiled.io/) and [coiled-runtime](https://github.com/coiled/coiled-runtime))

- https://github.com/coiled/coiled-runtime/issues/191
- https://github.com/coiled/coiled-runtime/issues/148

**Comment by TomNicholas** [comment]
This looks great so far @gjoseph92 !

For my vorticity example from #6571, is the "something else going on here" related to "widely-shared dependencies" #5325? (I'm not sure if you ran the full problem or a simplified version for that benchmarking case.)

**Comment by mrocklin** [comment]
First, exciting results.  I'm excited.  Also, kudos on the clear presentation of those results.  

If it is easy to share performance reports for the shuffling case I would be curious to see them.

**Comment by mrocklin** [comment]
@gjoseph92 I'm curious, any luck digging into these and seeing what was going on?

**Comment by gjoseph92** [comment]
There was a small typo in my code for the `shuffle-enrich` test case, which made a large difference: the shuffle didn't run, because I was referencing the original DataFrame, not the shuffled one.

So the results showing an enormous decrease in shuffle memory were inaccurate, in that they didn't apply to shuffling. They were accurate in that the workload I accidentally tested (which is also a common workload) did see ~9x lower memory usage without production and shorter runtime, but it was definitely mis-named.

I've edited https://github.com/dask/distributed/issues/6560#issuecomment-1165215417 to correct this.
* I added a pure `shuffle` workload. Unsurprisingly, this doesn't show any benefit, but also not much detriment. 
* `dataframe-align` is the workload I had originally mis-named `shuffle-enrich`. I've renamed it and re-run it to confirm the results still hold (they do).
