### ISSUE TITLE
Root-ish tasks all schedule onto one worker

### ISSUE THREAD

**Issue by gjoseph92** [dask/distributed#6573]
```python
import time
import dask
import distributed

client = distributed.Client(n_workers=4, threads_per_worker=1)

root = dask.delayed(lambda n: "x" * n)(dask.utils.parse_bytes("1MiB"), dask_key_name="root")
results = [dask.delayed(lambda *args: None)(root, i) for i in range(10000)]
dask.compute(results)
```
Initially a few `results` tasks run on other workers, but after about .5 sec, all tasks are just running on a single worker and the other three are idle.
![Screen Shot 2022-06-13 at 8 08 48 PM](https://user-images.githubusercontent.com/3309802/173478512-4dc5332e-c577-4159-90b1-94de3ef0f52e.png)

I would have expected these tasks to be evenly assigned to all workers up front

Some variables to play with:
* If the size of the root task is smaller, tasks will be assigned to other workers
* If you remove `dask_key_name="root"`, then _all_ tasks (including the root) will all run on the same worker. I assume this is because they have similar same key names (`lambda`) and therefore the same task group, and some scheduling heuristics are based not on graph structure but on naming heuristics

Distributed version: 2022.6.0

**Comment by fjetter** [comment]
This is a work stealing problem. If we disable work stealing, it works as expected

```python
import time
import dask
import distributed
with dask.config.set({"distributed.scheduler.work-stealing": False}):
    client = distributed.Client(n_workers=4, threads_per_worker=1)
root = dask.delayed(lambda n: "x" * n)(dask.utils.parse_bytes("1MiB"), dask_key_name="root")
results = [dask.delayed(lambda *args: None)(root, i) for i in range(10000)]
dask.compute(results)
```

![Jun-14-2022 10-26-27](https://user-images.githubusercontent.com/8629629/173530952-2e073ec8-eb96-45a8-90aa-d692d6833ab6.gif)

**Comment by fjetter** [comment]
I looked into this briefly today and could narrow this down to a couple of issues

- Initially, before the execution time could be learned, [unknown-task-duration](https://github.com/dask/distributed/blob/99a2db1cb75e4edf3c9e1c4ed8c691a0a47e71c5/distributed/distributed.yaml#L29) is used for the compute time which basically enables work stealing for all tasks initially for a brief moment. This causes the imbalance.
- After the first couple of tasks finished we will learn the actual execution time and will see that it is merely a couple of microseconds, i.e. work stealing will always ignore them https://github.com/dask/distributed/blob/99a2db1cb75e4edf3c9e1c4ed8c691a0a47e71c5/distributed/stealing.py#L226-L227 I'm already arguing in https://github.com/dask/distributed/pull/4920 that this approach is wrong. This causes the initial imbalance never to be corrected. If these two lines are removed, the occupancy fluctuates but stays roughly homogeneous. Of course, in this situation, no work stealing would still be a better choice

Whether or not unknown tasks are allowed to be stolen is actually a disputed topic.
https://github.com/dask/distributed/pull/5392 disabled this behavior based on a previously written test and https://github.com/dask/distributed/issues/5564 reported this as a regression which caused a revert in https://github.com/dask/distributed/pull/5572

**Comment by fjetter** [comment]
The initial imbalance is cause by work stealing being selecting potential victims greedily in case there are no saturated workers around.

Specifically the following lines https://github.com/dask/distributed/blob/99a2db1cb75e4edf3c9e1c4ed8c691a0a47e71c5/distributed/stealing.py#L424-L429 are responsible for quite astonishing stealing decisions, e.g. even between two as idle classified workers.

Therefore, as soon as at least one of the workers is classified as idle due to being slightly faster than another worker, this idle worker is allowed to steal work from basically everywhere causing all work to gravitate towards this specific worker.

Finally, [this](https://github.com/dask/distributed/blob/99a2db1cb75e4edf3c9e1c4ed8c691a0a47e71c5/distributed/stealing.py#L443-L466) for-loop is exhausting the entire stealable set for the targeted victim/"saturated" worker without accounting for any in-flight occupancy. in-flight occupancy is used for sorting and therefore picking a victim (see `combined_occupancy`) but we never reevaluate if we should stop stealing from the victim which ultimately causes a severe overcorrection that is very likely responsible for the very aggressive fluctuations we see in stealing often (e.g. https://github.com/dask/distributed/issues/5243)

**Comment by fjetter** [comment]
I investigated what's causing the initial spike of stealing events. Very early in the computation we see that slightly less than 7.5k stealing decisions are enacted which causes this initial imbalance.

Assuming perfect initial task placement, this is explained by the way we update occupancies. Right after the root task finished and all tasks are assigned we can see that the occupancies are already biased due to https://github.com/dask/distributed/issues/7004

![image](https://user-images.githubusercontent.com/8629629/188892351-d7993928-b501-4bc9-9d61-6332a800e784.png)

this bias is amplified in this example due to a double counting problem of occupancies https://github.com/dask/distributed/issues/7003 

after an update of the task duration, [`_reevaluate_occupancy_worker `](https://github.com/dask/distributed/blob/3655f13666ba9f38966de26c12f559cc4761ab4c/distributed/scheduler.py#L3045-L3058) which is [ran periodically](https://github.com/dask/distributed/blob/3655f13666ba9f38966de26c12f559cc4761ab4c/distributed/scheduler.py#L7452-L7474) and selects one worker to recompute the results assuming CPU load is not above a threshold

will reevaluate this, causing in this example the occupancy of the selected worker to drop dramatically since the unknown-duration is, by default 0.5s but the runtime of these tasks is much smaller. This drastic drop causes this worker to be classified as idle and it will steal **all** the tasks.

Even if this round robin recalculation is replaced with an exact, "always compute all workers" function, the bias introduced by the double counting causes the worker with the dependency to always be classified as idle which causes heavy stealing as well

![image](https://user-images.githubusercontent.com/8629629/188893975-3163ec31-8673-4d53-b87d-5092e225a322.png)

xref https://github.com/dask/distributed/issues/5243

**Comment by fjetter** [comment]
After #7036 the original reproducer was timing dependent (pending on a reevaluate_occupancy)

https://github.com/dask/distributed/pull/7075 closes this. It added the original reproducer as a test case
