### ISSUE TITLE
Tornado 6.2 compatibility

### ISSUE THREAD

**Issue by fjetter** [dask/distributed#6669]
Tornado 6.2 was just released and we're hitting a few errors on CI. So far, the only thing I observed was a deprecation warning that is converted to an error. We should restore compatibility and remove the pinning introduced in https://github.com/dask/distributed/pull/6668

cc @graingert

**Comment by jrbourbeau** [comment]
@gabicca noted in https://github.com/dask/distributed/issues/6979#issue-1357245420 that package solve conflicts are showing up with Jupyter because the latest `jupyter-clinet==7.3.5` release requires [`tornado >=6.2`](https://github.com/conda-forge/jupyter_client-feedstock/blob/331c1f792886e115ebcc0140743e67a630ff4355/recipe/meta.yaml#L32)

**Comment by jrbourbeau** [comment]
Another `jupyter`-related report https://github.com/dask/distributed/issues/6984

**Comment by crusaderky** [comment]
There are several failing tests; moving this back to in progress

**Comment by gabicca** [comment]
Hello, can you please give us an update on how this work is going? When can we expect distributed to be compatible with tornado==6.2?

**Comment by graingert** [comment]
> Hello, can you please give us an update on how this work is going? When can we expect distributed to be compatible with tornado==6.2?

hopefully in the next release!
