### ISSUE TITLE
`_transition_from_resumed` contains legacy code and documentation

### ISSUE THREAD

**Issue by hendrikmakait** [dask/distributed#6693]
`_transition_from_resumed` should not be reachable from a code path where `ts._previous == "executing"`. Yet, it states this in the docstring and performs checks for this behavior. We should revisit the code and explanation and clean it up to improve readability.

**Comment by crusaderky** [comment]
This is heavily related to #6689.

https://github.com/dask/distributed/blob/40867c7fb4e6c40c3689874b17b9c04b2b616b74/distributed/worker_state_machine.py#L1948-L1968

Lines 1949-1953 are unreachable, because `if ts._previous == finish: ` does not do what the author thought: 
- `ts._previous` is either executing, long-running, or flight
- `finish` is either waiting, or fetch, or missing

As a side note, I'm unsure how a transition resumed->missing can ever happen, but I'm fairly sure there's no unit test for it.

As a consequence, the use case

- flight->cancelled->resumed(waiting)->fetch 
- executing->cancelled->resumed(fetch)->executing
- long-running->cancelled->resumed(fetch)->long-running

is unwittingly covered by lines 1958+.

Those lines do *not* cover the use case `# Flight/executing finished unsuccessfully, i.e. not in memory`.
- If executing fails, the transition resumed->error is performed by `_transition_generic_error`, which causes all sorts of problems (#6689).
- if flight fails with GatherDepFailureEvent, you also have the same `_transition_generic_error` which... might? ... work as intended (missing a test).
- if flight fails with GatherDepNetworkFailureEvent or GatherDepSuccessEvent (but no data), then you do have a transition to executing served by lines 1958+, and that's tested by `test_workerstate_flight_failure_to_executing`.
