### ISSUE TITLE
why does Client.wait_for_workers() have a default `n_workers` kwarg of zero?

### ISSUE THREAD

**Issue by dchudz** [dask/distributed#6900]
I just helped a user who was confused because `client.wait_for_workers()` wasn't waiting for any workers.

It looks like the default `n_workers` is zero, `wait_for_workers()` doesn't wait for any workers. I'm having trouble understanding why `wait_for_workers()` (waiting for zero workers) would ever be desired behavior.

Would this method be easier to use correctly if `n_workers` were required rather than having a default of zero?

(A more complicated alternative that might work: When we don't have an `n_workers` arg, interrogate `self.cluster` (if there is one) to find out the intended cluster size, and wait for some portion (100% or 90%?) of that.)

**Comment by phobson** [comment]
Thanks for writing up the issue, @dchudz. My 2 cents would be to default to waiting for e.g., 90% of the workers

**Comment by fjetter** [comment]
> My 2 cents would be to default to waiting for e.g., 90% of the workers

In general, the client doesn't have this kind of information. This info is only available if the Client was initialized with a cluster object. If only an address is used, the client doesn't have this info. In this case it doesn't know how many workers were requested but aren't there yet.

I'm wondering why there even is a default value. Zero does not make any sense. I suggest to remove this default value.

We can investigate exposing an auto parameter that uses the cluster, if available, but I'm not sure if this is a great API since we still would raise in many cases by default

**Comment by dchudz** [comment]
>  I suggest to remove this default value.

Yeah, let's do that. Thanks Florian!
