### ISSUE TITLE
Resumed tasks may not deallocate (or over-deallocate) resources

### ISSUE THREAD

**Issue by crusaderky** [dask/distributed#6915]
### Use case
In jupyter notebook, a user starts a long-ish task. Then, they realise that it should have resources, so they resubmit it before the original task terminated.
Or the other way around, they submit a task with resources, realise they should have no or different resources, and resubmit.

### Expected behaviour
After the original task terminates, `available_resources == total_resources`.

### Actual behaviour
`available_resources` are released according to the second invocation of `client.submit`. 
This could keep them occupied forever or send them above `total_resources`.

### Reproducer
given `available_resources = {"R": 1}, total_resources={"R": 1}`:
```python
f = client.submit(sleep, 2)
sleep(1)
f = client.submit(sleep, 2, resources={"R": 1})
```
Now we have `available_resources = {"R": 2}, total_resources={"R": 1}`.

**Comment by fjetter** [comment]
I think this is an interesting case because I'm not entirely convinced that both submits should be treated as the same key.

we default of treating keys as pure functions but either a function requires resources or it doesn't. In my mind, these two submits are supposed to be different functions, aren't they?

The key generation in this case does not account for arguments that could/should affect our treatment
https://github.com/dask/distributed/blob/a1d2011e7d5d5ba26bea8bd4b0dec65f485f2b43/distributed/client.py#L1781

should this be a `tokenize(func, kwargs, resources, *args)`?

I think resources are the only argument that could be interpreted this way. I think it's not a straightforward call with resources since they can be used in so many generic ways.

**Comment by fjetter** [comment]
FWIW, I think in this case the cleanest solution from a UX perspective would be to raise an error if we detected such a drift and ask the user to clear the scheduler state before continuing. That is technically much more difficult to pull off, I believe.

The behavior for scheduler and worker might also need to be different: scheduler could be strict and not allow any overwrites but workers need to handle this more gracefully because of the latency.

thoughts?

**Comment by crusaderky** [comment]
Resources can't really be part of key generation in dask/dask because they're annotations, which means they can be added afterwards, aren't they?

> ask the user to clear the scheduler state before continuing

the scheduler state *is* clean. The user released the original future. It's the worker state that isn't.

> scheduler could be strict and not allow any overwrites but workers need to handle this more gracefully because of the latency.

The worker must be graceful because task cancellation is not immediate. So once we necessarily build in such behaviour in the worker (see PR that closes this issue) I think it's overkill to add extra logic to the scheduler. I think we're talking about an edge case after all.
