### ISSUE TITLE
`HeapSet` may not update position of item re-added with different priority

### ISSUE THREAD

**Issue by gjoseph92** [dask/distributed#6950]
Just a small thing I noticed:

```python
    def test_heapset_update_key():
        heap = HeapSet(key=operator.attrgetter("i"))
    
        cx = C("x", 1)
        c2 = C("2", 2)
    
        heap.add(cx)
        heap.add(c2)
    
        heap.discard(cx)
        cx.i = 3
        heap.add(cx)
    
>       assert heap.pop() is c2
E       assert C(x, 3) is C(2, 2)
E        +  where C(x, 3) = <bound method HeapSet.pop of <HeapSet: 1 items>>()
E        +    where <bound method HeapSet.pop of <HeapSet: 1 items>> = <HeapSet: 1 items>.pop
```

**I don't think this actually affects us currently** since we currently only track tasks in HeapSets, and their priorities can't change. So it might be fine to fix this just by mentioning it in the docstring.

Otherwise, to actually fix, we'd probably need to make `_data` into a dict instead of a set, and store the `_inc` for each element. When retrieving elements, we wouldn't just check `if value in self._data`, we'd check `if self._data.get(value) == v_tuple[1]`.

cc @crusaderky

**Comment by crusaderky** [comment]
> **I don't think this actually affects us currently** since we currently only track tasks in HeapSets, and their priorities can't change.

Your use case requires the task to be discarded from the heap. In the WorkerState, that will happen if the task transitions from `ready` or `fetch` to `released`. THEN, the task must not transition immediately to forgotten; if it doesn't when it re-enters the heap it's going to be a brand new TaskState object so the problem won't appear.
I don't think we should worry.

There is a use case, which does not involve removal from the set:

```python
ws.handle_stimulus(
    AcquireReplicasEvent(who_has={"clog": ws2}),
    ComputeTaskEvent.dummy("y", who_has={"x": ws2}, priority=(0, )),
    ComputeTaskEvent.dummy("z", who_has={"x": ws2}, priority=(-1, )),
)
```
In the above example, x will be fetched with priority 0 instead of -1; in other words, with the priority of the first dependent to be scheduled instead of its highest-priority dependent.

**I don't think we should care.** The impact of priorities for task gathering is probably negligible in most cases anyway. Here we are talking about a very specific case where a task has multiple dependents with different priorities AND the network is saturated.

**Comment by gjoseph92** [comment]
Sounds good. And I agree that this doesn't seem important for our actual use-case.

I do think we should mention it in the `HeapSet` docstring at least though. In the future, someone may want to use the collection for a new purpose (like I've been using it in various ways with task queuing), and it would be good to not get bitten by this. Want to add that message in https://github.com/dask/distributed/pull/6952 and close both these issues with it?
