### ISSUE TITLE
Storing directly in data dict on worker crashes worker

### ISSUE THREAD

**Issue by adbreind** [dask/distributed#7436]
**Describe the issue**: When storing a key/val pair directly into the worker's `data` dict, task appears to succeed but worker crashes immediately after with a traceback like:
```
2022-12-27 22:31:55,486 - distributed.worker - ERROR - Unexpected exception during heartbeat. Closing worker.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/distributed/worker.py", line 1219, in heartbeat
    metrics=await self.get_metrics(),
  File "/opt/conda/lib/python3.9/site-packages/distributed/worker.py", line 1012, in get_metrics
    task_counts=self.state.task_counts,
  File "/opt/conda/lib/python3.9/site-packages/distributed/worker_state_machine.py", line 3323, in task_counts
    assert other >= 0
AssertionError
```

**Minimal Complete Verifiable Example**:

```python
from dask.distributed import get_worker, Client, LocalCluster

cluster = LocalCluster(n_workers=3, threads_per_worker=1, memory_limit='1GiB')
client = Client(cluster)

def worker_local_demo():
    try:
        local_val = get_worker().data['my_key']
    except KeyError:    
        get_worker().data['my_key'] = 'my_val'
        return 'stored'
    return local_val

client.submit(worker_local_demo).result()
```

**Anything else we need to know?**: This is a regression (used to work).

AFAIK, this technique (using data dict) has always been a sort of "advanced workaround when absolutely needed" more than a best practice -- is this deprecated/removed, rather than a bug? If so, what is the recommended alternative for non-serializable objects that need to persist in worker (e.g., network connection)?

**Environment**:

- Dask version: 2022.12.1 (distributed ver 2022.12.1 also)
- Python version: 3.9.15
- Operating System: Ubuntu kernel 5.15.0
- Install method (conda, pip, source): conda (mamba)

**Comment by mrocklin** [comment]
A sensible workaround would be to put something on the worker object
itself, assuming we don't use slots or anything.

**Comment by fjetter** [comment]
> AFAIK, this technique (using data dict) has always been a sort of "advanced workaround when absolutely needed" more than a best practice

I strongly suggest not to set anything on `data` yourself. `Worker.data` is much more complicated than just a simple dictionary and it is relatively tightly integrated with how we spill data to disk and monitor memory usage.
Moving forward this might not even be a dict/mapping any longer (discussions here https://github.com/dask/distributed/issues/4424)

Specifically for non-serializable objects, the data mapping is actually dangerous since dask may actually try to spill the object to disk.

> If so, what is the recommended alternative for non-serializable objects that need to persist in worker (e.g., network connection)?

Is there a reason why this needs to be bound per worker? Wouldn't a global python constant already do the trick? This would not bind data per worker but data per python process which is basically the same thing unless you're running an async cluster.


```python
cluster = LocalCluster(n_workers=3, threads_per_worker=1, memory_limit="1GiB")
client = Client(cluster)

my_cache = None

def worker_local_demo():
    global my_cache
    if my_cache is not None:
        return my_cache
    my_cache = "cache"
    return "new"

print(f"Local before: {my_cache}")
workers = list(client.run(lambda: None))
print(
    f"First: {client.submit(worker_local_demo, workers=[workers[0]], pure=False).result()}"
)
print(
    f"Same: {client.submit(worker_local_demo, workers=[workers[0]], pure=False).result()}"
)
print(
    f"Other: {client.submit(worker_local_demo, workers=[workers[1]], pure=False).result()}"
)
print(f"Local after: {my_cache}")
```

Which gives what I think you're looking for. If executed a second time on the same worker, we'll hit the cache but otherwise we'll miss it.


```
Local before: None
First: new
Same: cache
Other: new
Local after: None
```

This is on Python 3.10.5

**Comment by adbreind** [comment]
Thanks @mrocklin and @fjetter! 

I think my old code was based on an ancient Stack Overflow answer ... but looking now, I see a few more recent answers capturing the above: use worker or use global, but don't use worker.data (for many reasons) ... 

So I'm going to close this as Won't Fix (as users messing with .data is unsupported/undefined functionality).
