### ISSUE TITLE
Questions about worker spilling to disk and associated logs

### ISSUE THREAD

**Issue by jmif** [dask/distributed#7493]
We're running a cluster that:
- Loads data from an external data source
- Selects one of five large ML models and runs the data through that model
- Saves the output somewhere else

So we have a fairly straightforward "embarrassingly parallel" pipeline but the models that we load are heavy.    The data / model processing is fairly quick, so we don't need to keep the data around in memory for long, just until we can run the model and save it to it's destination.  This means that we need a big chunk of (unmanaged) memory for the models and a smaller (relative to the amount of model memory) amount of (managed) memory necessary for the actual data.  The majority of the time the workers keep up with the data just fine but every now and then the models processing runs slower (generalizing here - happy to provide more information if helpful) and the data ingestion ends up filling in memory and spilling to disk.  This is what we want to happen: the majority of the time we only need a small amount of memory to hold the managed data and would prefer to not allocate more memory when not necessary and instead have the data spill to disk.

When this happens, our logs get flooded with [this](https://github.com/dask/distributed/blob/1be54991020caa0cd3ccdd7bb4d9e2be16517ba7/distributed/worker_memory.py#L266) log, the rate at which the logs flood varies but sometimes its 20+ lines per second (this job had workers with a high number of threads, not sure if thats related but calling out in case).

I'm working to understand how this memory spill works and what options we have here.  A few questions regarding this:

- The code block in question is triggered by `if not data.fast:` and ends with `break`, which makes me think this is run when there is no data to spill to disk, so we're in a situation where we are over our threshold but there is no data to spill, am I interpreting that right?
- Looking at the code in the memory management loop and cross referencing with the [threshold docs](https://distributed.dask.org/en/stable/worker-memory.html#thresholds-configuration), it looks like I can set my target threshold higher to avoid this log flood, but if I'm reading the code correctly as soon as our memory exceeds the target limit (or the spill limit) we'll start spilling and thus logging again even if .  Are there any recommendations for how to handle this?  The spilling behavior is working well for us in this current configuration, the problem really is the log line.  In our setup we actually expect managed memory usage to be high and thus the log line is hurting us when we try to be cost effective.
- I'm not aware of a way to disable this log via logger config or via configuration options, am I missing one?
- I can think of a few ways to fix / improve this (listed below), would love to hear thoughts on them and any other ideas as well.  I'd be open to submitting a PR to fix.
  - A few warnings being logged out are totally fine, it's the flood that is the problem.  We could simply throttle the log statements.
  - We could add another memory parameter to address this use case of expected large amounts of unmanaged memory, could be as simple as a threshold value that specifies the expected amount of unmanaged memory we expect.  We could then calculate a warning threshold such as "

**Comment by fjetter** [comment]
Could you please repost this question in https://dask.discourse.group/? We try to keep the issue tracker for bugs/features/etc. and use discourse for help around usage, etc.

**Comment by jmif** [comment]
Happy to move to discourse, before I do I want to confirm my intention with this issue is clear: I opened to discuss a potential improvement to the code here that I'm happy to contribute.  I can certainly see how that wasn't clear as I asked a few clarifying questions to make sure I was understanding how the code should work.  Is Discourse also where we should have a discussion about how to improve this code path?

**Comment by fjetter** [comment]
I like the idea of reducing the frequency of the log message but am less excited about adding another configuration option.

@crusaderky any suggestions?

FWIW if a log message pops up too often you could use filterwarings `once`, see https://docs.python.org/3/library/warnings.html#the-warnings-filter but I agree that we're too verbose here

**Comment by crusaderky** [comment]
The log message is telling you that 70% (`distributed.worker.memory.spill`) of your worker's memory_limit is nothing the worker knows about (unmanaged memory), and it's run out of ideas on how to mitigate the situation because it already spilled out all the managed memory. It's also telling you that very soon you may reach 95% (`distributed.worker.memory.terminate`) and it will be game over for your worker.

Please have a read through https://distributed.dask.org/en/stable/worker-memory.html#using-the-dashboard-to-monitor-memory-usage for the most common forms of unmanaged memory. Quick tip: if you have tasks running, and your process memory plot looks like a sawtooth, then it's almost certainly a disproportionate amount of heap allocated by your tasks.

The easiest solution to reduce heap size is to reduce your chunk size. If that were not possible, you should consider using workers with more memory, or tweaking the spill threshold to be higher - although if you worry that you'll reach it anyway no matter how high, then I must say that you'll reach the terminate threshold soon enough - which will kill off your worker.

On our side it's sensible to introduce some sort of throttling in how frequently you receive the warning. We already coded ad-hoc something like that in distributed.spill and it makes sense to build a general purpose facility instead.
