### ISSUE TITLE
client.run() generates a tornado event loop freeze (ie: long GIL-hold)

### ISSUE THREAD

**Issue by epizut** [dask/distributed#7495]
It looks like `client.run()` and `client.register_worker_callbacks()` hold the GIL for too long resulting in a tornado event loop freeze:

```python
import dask
import dask.distributed
client = dask.distributed.Client(n_workers=1)

client.register_worker_plugin(dask.distributed.diagnostics.plugin.ForwardOutput())

def sleep_10():
    import time
    import logging
    # Make sure to allow INFO log forwarding
    logging.getLogger('distributed').handlers[0].setLevel(logging.INFO)
    time.sleep(10)
    return 42
```

```python
client.run(sleep_10) # Unexpected tornado freeze
```
![image](https://user-images.githubusercontent.com/1694892/213700858-48a06795-a63e-418a-8254-126bd9111ad5.png)

```python
client.register_worker_callbacks(sleep_10) # Unexpected tornado freeze
```
![image](https://user-images.githubusercontent.com/1694892/213701115-915cbd0d-a3be-4139-a33c-b68f0a85a49b.png)

Please note that using a delayed do not generate such message:
```python
dask.delayed(sleep_10)().compute()  # Do not freeze the tornado loop
```

**Environment**:

- Dask version: 2023.1.0
- Python version: 3.9
- Operating System: Windows
- Install method (conda, pip, source): pip

**Comment by fjetter** [comment]
This is actually expected behavior. `Client.run` executes the submitted function as a coroutine on the worker. Sleep(10) is not asynchronous and will therefore block the event loop. It is not executed in a separated thread like ordinary tasks. FYI this does not block the GIL, just the event loop. These are two different concepts.

A similar argument is true for the plugin registration.

If this is a problem for you, you can write the functions you are runnign (and most of the plugin methods) as coroutine functions for which you have more control over the event loop.

e.g.

```python
async def sleep10_async(duration):
    await asyncio.sleep(duration)
    print("success!")
    return 42

client.run(sleep10_async, duration=10)
```

You can also write the plugin setup and teardown methods asynchronously

**Comment by epizut** [comment]
Sure, I am well aware of the GIL vs event loop distinction.
I thought `.run()` used the same code path as a regular task.

My bad, sorry for losing your time

**Comment by fjetter** [comment]
> My bad, sorry for losing your time

Don't worry :)

> I thought .run() used the same code path as a regular task.

You might be looking for `client.submit` instead. This is scheduling the submitted function as an ordinary task which is executed on a dedicated thread

**Comment by epizut** [comment]
My goal was to preload long running imports (ie ~4s) without triggering any
tornado freeze message. I missed the new preload argument in LocalCluster.

Thanks

Le ven. 20 janv. 2023 à 14:38, Florian Jetter ***@***.***> a
écrit :
