### ISSUE TITLE
Multiprocessing Connection cannot be serialized

### ISSUE THREAD

**Issue by eddiebergman** [dask/distributed#7792]
**Describe the issue**:
Passing a [`Connection`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.connection.Connection) object made from [`Pipe`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Pipe) as a argument to
`submit()` on the client raises an `OSError: [Errno 9] Bad file descriptor`. This only happens in `dask==2023.4.0` and did not happen in `dask==2023.3.2`.

I tracked down the error to happen at [`os.dup`](https://docs.python.org/3/library/os.html#os.dup) in [`multiprocessing.resource_sharer.py::DupFd::__init__`](https://github.com/python/cpython/blob/da2273fec7b1644786b9616592b53b04fdec4024/Lib/multiprocessing/resource_sharer.py#L48).

This happens during the `reduction` step of pickling, where the `multiprocessing.connection.py` file registers how to `__reduce__` a `Connection` object and then how to rebuild it. Essentially this pickles the file descriptor number and a reference of how to reconstruct the `Connection` with that filde descriptor:
* https://github.com/python/cpython/blob/da2273fec7b1644786b9616592b53b04fdec4024/Lib/multiprocessing/connection.py#L1035
* https://github.com/python/cpython/blob/da2273fec7b1644786b9616592b53b04fdec4024/Lib/multiprocessing/reduction.py#L198

**Minimal Complete Verifiable Example**:

```python
import time
from multiprocessing.connection import Connection, Pipe

from dask.distributed import Client, LocalCluster, Worker


def func(connection: Connection) -> None:
    connection.send("Hello World!")


def main():
    cluster = LocalCluster(n_workers=1, worker_class=Worker, processes=True)
    client = Client(cluster)

    reader, writer = Pipe()

    client.submit(func, writer)

    time.sleep(1)
    print("recievied", reader.recv())

    reader.close()

    client.close()
    cluster.close()


if __name__ == "__main__":
    main()
```

**Anything else we need to know?**:

This didn't work with `worker_class=Nanny` in either circumstance. I'm not sure of the internal reasons why.

Is there a better way to handle two-way communication with workers submitted with dask? I couldn't find any reasonable documentation on how to implement it. In the example I only advertise one way communication but in practice I would like to have two way.

**Environment**:

- Dask version: 2023.4.0
- Python version: Python 3.10.8
- Operating System: 5.15.106-1-MANJARO
- Install method (conda, pip, source): pip

**Comment by jrbourbeau** [comment]
Thanks for the issue @eddiebergman. My guess is this is related to the recent pickle serialization changes (see https://blog.dask.org/2023/04/14/scheduler-environment-requirements for a description). 

> Is there a better way to handle two-way communication with workers submitted with dask? 

This isn't a common request. Could you elaborate a bit more on your use case? Maybe the pub-sub API would come in handy https://docs.dask.org/en/stable/futures.html#publish-subscribe

**Comment by eddiebergman** [comment]
Ahhh thanks for the Blogpost, helps clear things up. I saw the commit changes between the two tags and I was surprised but such a major internal change.

My use case is from developing a library that works off of the `Executor` class native to python, specially the `submit` abstraction. The goal was to allow users to scale up experiments from something like a `ProcessPoolExecutor` to some other distributed workload system, i.e. `dask_jobqueue` for scaling to a cluster or `airflow` for other distributed systems.

The "fire and wait for return" functionality still works but some users may have workloads that depends on "talking" workers that the main process can send and receive messages from, acting accordingly. I have a `Comm` class with a simple `send` and `recieve` interface that was built from `Connection` objects from native python but understandably they're broken now. I looked into possibly making a concrete implementation of this with dasks `Comm` object but I found little documentation on this.

Ideally dasks pickling procedure should not break file descriptorsl (as I tested this on our cluster and the environment is the same) but I would also be willing to look at the above option.

I feel it would be a good thing for dask to fix as it technically doesn't break the requirements specified in the blog post but I understand if it's beyond the possible scope of things now.

Best
Eddie

**Comment by fjetter** [comment]
This is actually not a bug and it's not related scheduler environments. You just cannot pickle / serialize a Connection, Pipe, Process, etc. These objects are wrappers around OS resources, e.g. a file or a socket. They are basically direct interfaces to your hardware which we cannot serialize and ship over the network (Dasks architecture is built to support distributed computing on many machines).
The reason why you can pass these things to a `ProcessPoolExecutor` is because they were built for this and it's guaranteed to run on the same machine.
We can't just "not break filedescriptors" (FWIW we're not breaking anything). 

Instead, you should rely on the synchronization primitive dask is offering. This way we'll ensure the data is submitted correctly and you won't encounter any weird serialization problems. From what you are describing [`Queue`](https://distributed.dask.org/en/stable/api.html#distributed.Queue) might be a suitable abstraction (or the pub/sub James is talking about, or Variables, see https://docs.dask.org/en/stable/futures.html#coordination-primitives for a list of available interfaces).

Depending on what you are actually doing, even an [`Actor`](https://distributed.dask.org/en/stable/actors.html) might work for you.
