### ISSUE TITLE
get_worker doesn't find worker within register_worker_callbacks

### ISSUE THREAD

**Issue by twoertwein** [dask/distributed#8152]
**Describe the issue**:

get_worker is not able to find a worker when it is called within register_worker_callbacks. I'm very sure this worked in an older version (haven't yet tested how many versions ago it worked)

**Minimal Complete Verifiable Example**:

```python
from dask.distributed import Client, LocalCluster
from distributed.worker_client import get_worker


def setup():
    get_worker()  # ValueError

if __name__ == "__main__":
    with LocalCluster(processes=True, n_workers=1) as cluster:
        with Client(cluster) as client:
            client.register_worker_callbacks(setup)

```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2023.8.1
- Python version: 3.11.4
- Operating System: bookworm docker python 3.11 image 
- Install method (conda, pip, source): poetry

**Comment by fjetter** [comment]
This was indeed removed in https://github.com/dask/distributed/pull/7580, see also https://github.com/dask/distributed/issues/7696

xref https://github.com/dask/distributed/issues/5485

This functionality was changed because the "detect worker" mechanism relied on thread local storage which caused some weird side effects.

The cleanest way for you to get access to the correct worker here is to use the `dask_worker` kwarg in setup and we will inject the appropriate worker for you. This is also backwards compatible.

i.e.

```python
def setup(dask_worker):
    from distributed import Worker
    assert isinstance(dask_worker, Worker)
    ...

client.register_worker_callbacks(setup)
```

This does not require any context and will always work

**Comment by twoertwein** [comment]
> The cleanest way for you to get access to the correct worker here is to use the `dask_worker` kwarg in setup and we will inject the appropriate worker for you. 

Thank you, I am using that now :)
