### ISSUE TITLE
Should distributed have "broadcast" functionality for explicit one-to-many data transfers?

### ISSUE THREAD

**Issue by broxtronix** [dask/distributed#84]
Certain workloads reference an identical, large piece of data on all worker nodes.  For example, a distributed algorithm might have a large hash or lookup table that all nodes need to access.  In these cases, it can be useful to be able to pre-cache this data by "broadcasting" it out to all workers.  

This requires some care, though, because a one-to-many data transfer can easily overwhelm the node on which the data is originating.  In Apache Spark, this is handled using the `spark_context.broadcast()` method, and I believe this method uses special network transfer mechanisms (possibly something akin to Bittorrent?) to scatter the data efficiently.

I would like to use something like Spark's `broadcast()` mechanism in `distributed,` but I'm curious to generate some discussion here to see if this is really a good fit.  My understanding (based on conversation with @mrocklin) is that `distributed` will scatter and cache blocks of data on workers on an as-needed basis, so a piece of data used by all workers will eventually be copied everywhere.  But my question, then, is how efficient the current copying scheme is compared to a broadcast mechanism that is specifically designed to distributed data to all nodes efficiently.

Another related question: what is the practical limit on the size of data that `distributed` can easily copy between nodes?  What sets this limit?  Is there a certain size for data transfers below which the `distributed` cluster performs much better?  And do workers block and become unresponsive while transferring large chunks of data?

**Comment by mrocklin** [comment]
There is a limit on message size currently set to either 2GB or half of the total virtual memory (if the `psutil` library is around.)  I haven't benchmarked networks here though.  These transfers use non-blocking sockets during data movement, although the deserialization phase after data has been transferred will block.

We can probably add some of this to the `scatter` function.  It would be good to see an application where this failed explicitly so that we could have something to optimize while building this out.

**Comment by mrocklin** [comment]
OK, scatter has a `broadcast=` keyword for data going from local->cluster.  We've also added a `e.replicate(futures, n=, workers=)` method to the executor to replicate data already on the cluster.  Closing.

**Comment by rainwoodman** [comment]
What is the algorithm behind the broadcast? I don't really know the technical name of the algorithm, but this post described the efficient broadcast implementation used in MPI: 

https://stackoverflow.com/a/6959982/3781929

BTW: what happens if during the broadcast a new worker is registered? Will it get the object or not?

**Comment by rainwoodman** [comment]
I have the answer to my first question: the `replicate` method uses a tree algorithm.
I do not know of the second answer.

**Comment by mrocklin** [comment]
Workers now throttle connections, so transfers tend to be ok even in one-to-many situations.  Explicit broadcasting is rarely required.  However, if you want to go more deeply into this topic I recommend raising a new issue or a stack overflow question.
