### ISSUE TITLE
Drop `yaml` support in `cluster_dump`

### ISSUE THREAD

**Issue by hendrikmakait** [dask/distributed#8541]
Our `cluster_dump` functionality is currently broken wrt. key roundtrips (#8540), which we need to fix. Since I do not see the added value in supporting both `msgpack` _and_ `yaml`, I'm inclined to limit the fix for roundtripping to `msgpack` and drop support for `yaml` _without a deprecation cycle_. (It's mostly broken anyways.) Note that we will still have `DumpArtefact.to_yamls` in case users want to create human-readable files. Also, `msgpack` is already a required dependency.

**Comment by fjetter** [comment]
Actually, msgpack was added only later because the dumps grew too large. the benefit of yaml is that it is human readable. I often analyzed those dumps by grepping/searching and reading the files.
I'm fine with dropping support for the dump to be written directly to yaml but there is also `DumpArtefact.to_yamls` which probably has the same problem

**Comment by hendrikmakait** [comment]
> I'm fine with dropping support for the dump to be written directly to yaml but there is also `DumpArtefact.to_yamls` which probably has the same problem

It will. Since we won't have to be able to roundtrip, I think we can get away with a simpler implementation here, i.e., simply stringifying keys. You could then grep for the stringified key in the `yaml` files.

**Comment by crusaderky** [comment]
+1. I like human-readable but converting from msgpack when needed is 3 lines

**Comment by hendrikmakait** [comment]
Closing this as not planned. In #8540, we decided against touching cluster dumps at all for now.
