### ISSUE TITLE
Deadlock with python 3.11

### ISSUE THREAD

**Issue by epizut** [dask/distributed#8616]
I spent a lot of time digging into a deadlock issue with Dask distributed and Python 3.11.
This issue was created so other people won't have to lose the same amount of time debugging endless dask and CPython stacks.

Thanks to @diegorusso we now have a pending fix https://github.com/python/cpython/issues/116969

Solutions:
- Wait for [#116969](https://github.com/python/cpython/issues/116969) if you are forced to use py3.11, but be aware that you need either python<3.11.9 or dask>=2024.4.1 due to [#11035](https://github.com/dask/dask/pull/11035)
- Skip 3.11 and move to 3.12

**Comment by fjetter** [comment]
Thanks a lot for tracking this down and reporting it here!

**Comment by epizut** [comment]
Sure, thanks again for your work on this.
In the meamtime, we could make the dask gc diagnostic optional or even better try to make it non re-entrant on the CPython lock by avoiding calling _current_frames()

**Comment by epizut** [comment]
I haven't taken the time to find a fix. Unfortunately, I selfishly skipped over version 3.11 and jumped straight to 3.12

**Comment by diegorusso** [comment]
Do you think this could be a good solution for dask distributed users? I mean, could/should this be documented somewhere?

**Comment by fjetter** [comment]
Apologies for the slow reply.

IIUC this deadlock can happen in pretty much every situation since our profiling thread is using `sys._current_frames()`. Do you know how easy it is to trigger this?

The CPython PR discusses enabling/disabling the GC. Is this a workaround that could work for us? (Not sure about perf implications)

Beyond this, I guess the only workaround we could provide is to disable the profiling thread entirely on python 3.11. Any other advice?

**Comment by diegorusso** [comment]
Just to let you know that the PR https://github.com/python/cpython/pull/117332 has been merged. It will go in the next security release of CPython.
