### ISSUE TITLE
dscheduler seems to be finding the wrong Python distribution

### ISSUE THREAD

**Issue by izaid** [dask/distributed#90]
```
0280-Izaid:Desktop izaid$ python
Python 2.7.11 (default, Dec 11 2015, 00:08:45)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import six
>>> six.__version__
>>> '1.10.0'
````

```
0280-Izaid:~ izaid$ dscheduler
Traceback (most recent call last):
  File "/usr/local/bin/dscheduler", line 4, in <module>
    import pkg_resources
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2797, in <module>
    parse_requirements(__requires__), Environment()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 580, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (six 1.4.1 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('six>=1.5'))
```

**Comment by mrocklin** [comment]
Has this been resolved?

**Comment by izaid** [comment]
As far as I can see, the only issue now is that I have to run "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/dscheduler" instead of just "dscheduler". We could either modify the setup.py to put this in the usr bin, or we could modify our documentation to say this is where these things get installed, or we could suggest users add  "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin" to their $PATH (is that safe?).

In any case, it's still true that a user can't just install distributed and do "dscheduler", "dworker ..." on OS X. So we need to do something about that.

**Comment by mrocklin** [comment]
@danielfrg is it possible to cleanly solve @izaid 's problem?

**Comment by danielfrg** [comment]
I would not say that an user cannot install distributed and do `dscheduler`, `dworker` on OS X.

I have tested the following:
- Anaconda py2 and py3
- Python from homebrew
- Python from homebrew using virutualenvs - only py2 on this one but py3 should work
- pyenv from homebrew
- pyenv from homebrew with virutalenvs with py2 and py3

And I was able to use `dworker` and `dscheduler` without any issues.

The problem here is apparently macports and the python they install. https://trac.macports.org/ticket/50058

> One should NOT use pip to install packages on the macports directory tree (which is what a macports-installed pip would do by default!). The recommended procedure would be:

> Install with macports your python distribution
if that python doesn't have its own standard virtualenv and pip (like Python 3.4 and later include venv and ensurepip), then install with macports the appropriate pip and virtualenv for that python
Prepare a "new place" to install pip packages (like a virtualenv)
Once into the "new place", use pip to install whatever

Personally I would solve this with a note in the docs saying that if you have macports you should add: `/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin` to the `$PATH`.

@izaid have you never seen this problem with other packages you install using `pip`? Did you try to install it since we did #95?

**Comment by izaid** [comment]
Yeah, this is clearly a Macports problem, I agree with that. I'm not using pip here, I'm just cloning from master and installing with `setup.py`.

Adding the note in the documentation that @danielfrg suggested is fine with me, so long as it's safe to do that.

**Comment by mrocklin** [comment]
@danielfrg can I interest you in writing up a brief `install` section for the distributed docs?

**Comment by mrocklin** [comment]
Stale and hasn't recurred.  Closing.
